/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.gtk3;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long GdkEvent_SIZEOF = 96L;

public static void GdkEvent_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEvent o) {
	o.type = s.get(JAVA_INT_UNALIGNED, 0L);
}

public static void GdkEvent_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEvent o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.type);
}

public static final long GdkEventButton_SIZEOF = 80L;

public static void GdkEventButton_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventButton o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_read(s, o);
	o.window = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_BYTE, 16L);
	o.time = s.get(JAVA_INT_UNALIGNED, 20L);
	o.x = s.get(JAVA_DOUBLE_UNALIGNED, 24L);
	o.y = s.get(JAVA_DOUBLE_UNALIGNED, 32L);
	o.axes = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.state = s.get(JAVA_INT_UNALIGNED, 48L);
	o.button = s.get(JAVA_INT_UNALIGNED, 52L);
	o.device = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.x_root = s.get(JAVA_DOUBLE_UNALIGNED, 64L);
	o.y_root = s.get(JAVA_DOUBLE_UNALIGNED, 72L);
}

public static void GdkEventButton_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventButton o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.window);
	s.set(JAVA_BYTE, 16L, o.send_event);
	s.set(JAVA_INT_UNALIGNED, 20L, o.time);
	s.set(JAVA_DOUBLE_UNALIGNED, 24L, o.x);
	s.set(JAVA_DOUBLE_UNALIGNED, 32L, o.y);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.axes);
	s.set(JAVA_INT_UNALIGNED, 48L, o.state);
	s.set(JAVA_INT_UNALIGNED, 52L, o.button);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.device);
	s.set(JAVA_DOUBLE_UNALIGNED, 64L, o.x_root);
	s.set(JAVA_DOUBLE_UNALIGNED, 72L, o.y_root);
}

public static final long GdkEventCrossing_SIZEOF = 88L;

public static void GdkEventCrossing_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventCrossing o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_read(s, o);
	o.window = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_BYTE, 16L);
	o.subwindow = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.time = s.get(JAVA_INT_UNALIGNED, 32L);
	o.x = s.get(JAVA_DOUBLE_UNALIGNED, 40L);
	o.y = s.get(JAVA_DOUBLE_UNALIGNED, 48L);
	o.x_root = s.get(JAVA_DOUBLE_UNALIGNED, 56L);
	o.y_root = s.get(JAVA_DOUBLE_UNALIGNED, 64L);
	o.mode = s.get(JAVA_INT_UNALIGNED, 72L);
	o.detail = s.get(JAVA_INT_UNALIGNED, 76L);
	o.focus = (s.get(JAVA_INT_UNALIGNED, 80L) & 1) != 0;
	o.state = s.get(JAVA_INT_UNALIGNED, 84L);
}

public static void GdkEventCrossing_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventCrossing o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.window);
	s.set(JAVA_BYTE, 16L, o.send_event);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.subwindow);
	s.set(JAVA_INT_UNALIGNED, 32L, o.time);
	s.set(JAVA_DOUBLE_UNALIGNED, 40L, o.x);
	s.set(JAVA_DOUBLE_UNALIGNED, 48L, o.y);
	s.set(JAVA_DOUBLE_UNALIGNED, 56L, o.x_root);
	s.set(JAVA_DOUBLE_UNALIGNED, 64L, o.y_root);
	s.set(JAVA_INT_UNALIGNED, 72L, o.mode);
	s.set(JAVA_INT_UNALIGNED, 76L, o.detail);
	s.set(JAVA_INT_UNALIGNED, 80L, (int) (o.focus ? 1 : 0));
	s.set(JAVA_INT_UNALIGNED, 84L, o.state);
}

public static final long GdkEventFocus_SIZEOF = 24L;

public static void GdkEventFocus_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventFocus o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_read(s, o);
	o.window = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_BYTE, 16L);
	o.in = s.get(JAVA_SHORT_UNALIGNED, 18L);
}

public static void GdkEventFocus_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventFocus o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.window);
	s.set(JAVA_BYTE, 16L, o.send_event);
	s.set(JAVA_SHORT_UNALIGNED, 18L, o.in);
}

public static final long GdkEventKey_SIZEOF = 56L;

public static void GdkEventKey_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventKey o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_read(s, o);
	o.window = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_BYTE, 16L);
	o.time = s.get(JAVA_INT_UNALIGNED, 20L);
	o.state = s.get(JAVA_INT_UNALIGNED, 24L);
	o.keyval = s.get(JAVA_INT_UNALIGNED, 28L);
	o.length = s.get(JAVA_INT_UNALIGNED, 32L);
	o.string = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.hardware_keycode = s.get(JAVA_SHORT_UNALIGNED, 48L);
	o.group = s.get(JAVA_BYTE, 50L);
	o.is_modifier = (int) FFM.getBits(s, 408L, 1);
}

public static void GdkEventKey_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventKey o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.window);
	s.set(JAVA_BYTE, 16L, o.send_event);
	s.set(JAVA_INT_UNALIGNED, 20L, o.time);
	s.set(JAVA_INT_UNALIGNED, 24L, o.state);
	s.set(JAVA_INT_UNALIGNED, 28L, o.keyval);
	s.set(JAVA_INT_UNALIGNED, 32L, o.length);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.string);
	s.set(JAVA_SHORT_UNALIGNED, 48L, o.hardware_keycode);
	s.set(JAVA_BYTE, 50L, o.group);
	FFM.setBits(s, 408L, 1, (long) o.is_modifier);
}

public static final long GdkEventMotion_SIZEOF = 80L;

public static void GdkEventMotion_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventMotion o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_read(s, o);
	o.window = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_BYTE, 16L);
	o.time = s.get(JAVA_INT_UNALIGNED, 20L);
	o.x = s.get(JAVA_DOUBLE_UNALIGNED, 24L);
	o.y = s.get(JAVA_DOUBLE_UNALIGNED, 32L);
	o.axes = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.state = s.get(JAVA_INT_UNALIGNED, 48L);
	o.is_hint = s.get(JAVA_SHORT_UNALIGNED, 52L);
	o.device = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.x_root = s.get(JAVA_DOUBLE_UNALIGNED, 64L);
	o.y_root = s.get(JAVA_DOUBLE_UNALIGNED, 72L);
}

public static void GdkEventMotion_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventMotion o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.window);
	s.set(JAVA_BYTE, 16L, o.send_event);
	s.set(JAVA_INT_UNALIGNED, 20L, o.time);
	s.set(JAVA_DOUBLE_UNALIGNED, 24L, o.x);
	s.set(JAVA_DOUBLE_UNALIGNED, 32L, o.y);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.axes);
	s.set(JAVA_INT_UNALIGNED, 48L, o.state);
	s.set(JAVA_SHORT_UNALIGNED, 52L, o.is_hint);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.device);
	s.set(JAVA_DOUBLE_UNALIGNED, 64L, o.x_root);
	s.set(JAVA_DOUBLE_UNALIGNED, 72L, o.y_root);
}

public static final long GdkEventWindowState_SIZEOF = 32L;

public static void GdkEventWindowState_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventWindowState o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_read(s, o);
	o.window = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_BYTE, 16L);
	o.changed_mask = s.get(JAVA_INT_UNALIGNED, 20L);
	o.new_window_state = s.get(JAVA_INT_UNALIGNED, 24L);
}

public static void GdkEventWindowState_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkEventWindowState o) {
	org.eclipse.swt.internal.gtk3.Structs_FFM.GdkEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.window);
	s.set(JAVA_BYTE, 16L, o.send_event);
	s.set(JAVA_INT_UNALIGNED, 20L, o.changed_mask);
	s.set(JAVA_INT_UNALIGNED, 24L, o.new_window_state);
}

public static final long GdkGeometry_SIZEOF = 56L;

public static void GdkGeometry_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkGeometry o) {
	o.min_width = s.get(JAVA_INT_UNALIGNED, 0L);
	o.min_height = s.get(JAVA_INT_UNALIGNED, 4L);
	o.max_width = s.get(JAVA_INT_UNALIGNED, 8L);
	o.max_height = s.get(JAVA_INT_UNALIGNED, 12L);
	o.base_width = s.get(JAVA_INT_UNALIGNED, 16L);
	o.base_height = s.get(JAVA_INT_UNALIGNED, 20L);
	o.width_inc = s.get(JAVA_INT_UNALIGNED, 24L);
	o.height_inc = s.get(JAVA_INT_UNALIGNED, 28L);
	o.min_aspect = s.get(JAVA_DOUBLE_UNALIGNED, 32L);
	o.max_aspect = s.get(JAVA_DOUBLE_UNALIGNED, 40L);
	o.win_gravity = s.get(JAVA_INT_UNALIGNED, 48L);
}

public static void GdkGeometry_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkGeometry o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.min_width);
	s.set(JAVA_INT_UNALIGNED, 4L, o.min_height);
	s.set(JAVA_INT_UNALIGNED, 8L, o.max_width);
	s.set(JAVA_INT_UNALIGNED, 12L, o.max_height);
	s.set(JAVA_INT_UNALIGNED, 16L, o.base_width);
	s.set(JAVA_INT_UNALIGNED, 20L, o.base_height);
	s.set(JAVA_INT_UNALIGNED, 24L, o.width_inc);
	s.set(JAVA_INT_UNALIGNED, 28L, o.height_inc);
	s.set(JAVA_DOUBLE_UNALIGNED, 32L, o.min_aspect);
	s.set(JAVA_DOUBLE_UNALIGNED, 40L, o.max_aspect);
	s.set(JAVA_INT_UNALIGNED, 48L, o.win_gravity);
}

public static final long GdkWindowAttr_SIZEOF = 80L;

public static void GdkWindowAttr_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkWindowAttr o) {
	o.title = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.event_mask = s.get(JAVA_INT_UNALIGNED, 8L);
	o.x = s.get(JAVA_INT_UNALIGNED, 12L);
	o.y = s.get(JAVA_INT_UNALIGNED, 16L);
	o.width = s.get(JAVA_INT_UNALIGNED, 20L);
	o.height = s.get(JAVA_INT_UNALIGNED, 24L);
	o.wclass = s.get(JAVA_INT_UNALIGNED, 28L);
	o.visual = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.window_type = s.get(JAVA_INT_UNALIGNED, 40L);
	o.cursor = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.wmclass_name = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.wmclass_class = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.override_redirect = (s.get(JAVA_INT_UNALIGNED, 72L) & 1) != 0;
}

public static void GdkWindowAttr_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GdkWindowAttr o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.title);
	s.set(JAVA_INT_UNALIGNED, 8L, o.event_mask);
	s.set(JAVA_INT_UNALIGNED, 12L, o.x);
	s.set(JAVA_INT_UNALIGNED, 16L, o.y);
	s.set(JAVA_INT_UNALIGNED, 20L, o.width);
	s.set(JAVA_INT_UNALIGNED, 24L, o.height);
	s.set(JAVA_INT_UNALIGNED, 28L, o.wclass);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.visual);
	s.set(JAVA_INT_UNALIGNED, 40L, o.window_type);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.cursor);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.wmclass_name);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.wmclass_class);
	s.set(JAVA_INT_UNALIGNED, 72L, (int) (o.override_redirect ? 1 : 0));
}

public static final long GtkTargetEntry_SIZEOF = 16L;

public static void GtkTargetEntry_read(MemorySegment s, org.eclipse.swt.internal.gtk3.GtkTargetEntry o) {
	o.target = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.flags = s.get(JAVA_INT_UNALIGNED, 8L);
	o.info = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void GtkTargetEntry_write(MemorySegment s, org.eclipse.swt.internal.gtk3.GtkTargetEntry o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.target);
	s.set(JAVA_INT_UNALIGNED, 8L, o.flags);
	s.set(JAVA_INT_UNALIGNED, 12L, o.info);
}

}
