package org.eclipse.swt.internal.win32;

/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */

/** Sizes and field offsets of C types that have no Java struct class. */
public final class Extra_FFM {

	public static final long LOGPEN = 16L;
	public static final long PROPVARIANT = 24L;
	public static final long SCRIPT_STRING_ANALYSIS = 8L;
}
