/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.cairo;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Cairo_FFM {

private static final class MH_cairo_1append_1path {
	static final MethodHandle MH = FFM.downcall("cairo_append_path", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void cairo_append_path(long arg0, long arg1) {
	try {
		MH_cairo_1append_1path.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1arc {
	static final MethodHandle MH = FFM.downcall("cairo_arc", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_arc(long arg0, double arg1, double arg2, double arg3, double arg4, double arg5) {
	try {
		MH_cairo_1arc.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1arc_1negative {
	static final MethodHandle MH = FFM.downcall("cairo_arc_negative", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_arc_negative(long arg0, double arg1, double arg2, double arg3, double arg4, double arg5) {
	try {
		MH_cairo_1arc_1negative.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1clip {
	static final MethodHandle MH = FFM.downcall("cairo_clip", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_clip(long arg0) {
	try {
		MH_cairo_1clip.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1close_1path {
	static final MethodHandle MH = FFM.downcall("cairo_close_path", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_close_path(long arg0) {
	try {
		MH_cairo_1close_1path.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1copy_1path {
	static final MethodHandle MH = FFM.downcall("cairo_copy_path", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_copy_path(long arg0) {
	try {
		long rc = (long) MH_cairo_1copy_1path.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1copy_1path_1flat {
	static final MethodHandle MH = FFM.downcall("cairo_copy_path_flat", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_copy_path_flat(long arg0) {
	try {
		long rc = (long) MH_cairo_1copy_1path_1flat.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1create {
	static final MethodHandle MH = FFM.downcall("cairo_create", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_create(long arg0) {
	try {
		long rc = (long) MH_cairo_1create.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1curve_1to {
	static final MethodHandle MH = FFM.downcall("cairo_curve_to", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_curve_to(long arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6) {
	try {
		MH_cairo_1curve_1to.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1destroy {
	static final MethodHandle MH = FFM.downcall("cairo_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_destroy(long arg0) {
	try {
		MH_cairo_1destroy.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1fill {
	static final MethodHandle MH = FFM.downcall("cairo_fill", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_fill(long arg0) {
	try {
		MH_cairo_1fill.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1font_1options_1create {
	static final MethodHandle MH = FFM.downcall("cairo_font_options_create", FunctionDescriptor.of(JAVA_LONG));
}
public static long cairo_font_options_create() {
	try {
		long rc = (long) MH_cairo_1font_1options_1create.MH.invokeExact();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1font_1options_1destroy {
	static final MethodHandle MH = FFM.downcall("cairo_font_options_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_font_options_destroy(long arg0) {
	try {
		MH_cairo_1font_1options_1destroy.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1font_1options_1get_1antialias {
	static final MethodHandle MH = FFM.downcall("cairo_font_options_get_antialias", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_font_options_get_antialias(long arg0) {
	try {
		int rc = (int) MH_cairo_1font_1options_1get_1antialias.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1font_1options_1set_1antialias {
	static final MethodHandle MH = FFM.downcall("cairo_font_options_set_antialias", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_font_options_set_antialias(long arg0, int arg1) {
	try {
		MH_cairo_1font_1options_1set_1antialias.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1antialias {
	static final MethodHandle MH = FFM.downcall("cairo_get_antialias", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_get_antialias(long arg0) {
	try {
		int rc = (int) MH_cairo_1get_1antialias.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1current_1point {
	static final MethodHandle MH = FFM.downcall("cairo_get_current_point", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, ADDRESS));
}
public static void cairo_get_current_point(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MH_cairo_1get_1current_1point.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1fill_1rule {
	static final MethodHandle MH = FFM.downcall("cairo_get_fill_rule", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_get_fill_rule(long arg0) {
	try {
		int rc = (int) MH_cairo_1get_1fill_1rule.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1font_1face {
	static final MethodHandle MH = FFM.downcall("cairo_get_font_face", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_get_font_face(long arg0) {
	try {
		long rc = (long) MH_cairo_1get_1font_1face.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1matrix {
	static final MethodHandle MH = FFM.downcall("cairo_get_matrix", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void cairo_get_matrix(long arg0, double[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_cairo_1get_1matrix.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1source {
	static final MethodHandle MH = FFM.downcall("cairo_get_source", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_get_source(long arg0) {
	try {
		long rc = (long) MH_cairo_1get_1source.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1target {
	static final MethodHandle MH = FFM.downcall("cairo_get_target", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_get_target(long arg0) {
	try {
		long rc = (long) MH_cairo_1get_1target.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1get_1tolerance {
	static final MethodHandle MH = FFM.downcall("cairo_get_tolerance", FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
}
public static double cairo_get_tolerance(long arg0) {
	try {
		double rc = (double) MH_cairo_1get_1tolerance.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1identity_1matrix {
	static final MethodHandle MH = FFM.downcall("cairo_identity_matrix", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_identity_matrix(long arg0) {
	try {
		MH_cairo_1identity_1matrix.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1image_1surface_1create {
	static final MethodHandle MH = FFM.downcall("cairo_image_surface_create", FunctionDescriptor.of(JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static long cairo_image_surface_create(int arg0, int arg1, int arg2) {
	try {
		long rc = (long) MH_cairo_1image_1surface_1create.MH.invokeExact(arg0, arg1, arg2);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1image_1surface_1get_1data {
	static final MethodHandle MH = FFM.downcall("cairo_image_surface_get_data", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_image_surface_get_data(long arg0) {
	try {
		long rc = (long) MH_cairo_1image_1surface_1get_1data.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1image_1surface_1get_1format {
	static final MethodHandle MH = FFM.downcall("cairo_image_surface_get_format", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_image_surface_get_format(long arg0) {
	try {
		int rc = (int) MH_cairo_1image_1surface_1get_1format.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1image_1surface_1get_1height {
	static final MethodHandle MH = FFM.downcall("cairo_image_surface_get_height", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_image_surface_get_height(long arg0) {
	try {
		int rc = (int) MH_cairo_1image_1surface_1get_1height.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1image_1surface_1get_1stride {
	static final MethodHandle MH = FFM.downcall("cairo_image_surface_get_stride", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_image_surface_get_stride(long arg0) {
	try {
		int rc = (int) MH_cairo_1image_1surface_1get_1stride.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1image_1surface_1get_1width {
	static final MethodHandle MH = FFM.downcall("cairo_image_surface_get_width", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_image_surface_get_width(long arg0) {
	try {
		int rc = (int) MH_cairo_1image_1surface_1get_1width.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1in_1fill {
	static final MethodHandle MH = FFM.downcall("cairo_in_fill", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static int cairo_in_fill(long arg0, double arg1, double arg2) {
	try {
		int rc = (int) MH_cairo_1in_1fill.MH.invokeExact(arg0, arg1, arg2);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1in_1stroke {
	static final MethodHandle MH = FFM.downcall("cairo_in_stroke", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static int cairo_in_stroke(long arg0, double arg1, double arg2) {
	try {
		int rc = (int) MH_cairo_1in_1stroke.MH.invokeExact(arg0, arg1, arg2);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1line_1to {
	static final MethodHandle MH = FFM.downcall("cairo_line_to", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_line_to(long arg0, double arg1, double arg2) {
	try {
		MH_cairo_1line_1to.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1init {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_init", FunctionDescriptor.ofVoid(ADDRESS, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_matrix_init(double[] arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MH_cairo_1matrix_1init.MH.invokeExact(lparg0, arg1, arg2, arg3, arg4, arg5, arg6);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1init_1identity {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_init_identity", FunctionDescriptor.ofVoid(ADDRESS));
}
public static void cairo_matrix_init_identity(double[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MH_cairo_1matrix_1init_1identity.MH.invokeExact(lparg0);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1invert {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_invert", FunctionDescriptor.of(JAVA_INT, ADDRESS));
}
public static int cairo_matrix_invert(double[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		int rc = (int) MH_cairo_1matrix_1invert.MH.invokeExact(lparg0);
		FFM.copyOut(lparg0, arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1multiply {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_multiply", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, ADDRESS));
}
public static void cairo_matrix_multiply(double[] arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MH_cairo_1matrix_1multiply.MH.invokeExact(lparg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1rotate {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_rotate", FunctionDescriptor.ofVoid(ADDRESS, JAVA_DOUBLE));
}
public static void cairo_matrix_rotate(double[] arg0, double arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MH_cairo_1matrix_1rotate.MH.invokeExact(lparg0, arg1);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1scale {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_scale", FunctionDescriptor.ofVoid(ADDRESS, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_matrix_scale(double[] arg0, double arg1, double arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MH_cairo_1matrix_1scale.MH.invokeExact(lparg0, arg1, arg2);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1transform_1point {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_transform_point", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, ADDRESS));
}
public static void cairo_matrix_transform_point(double[] arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MH_cairo_1matrix_1transform_1point.MH.invokeExact(lparg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1matrix_1translate {
	static final MethodHandle MH = FFM.downcall("cairo_matrix_translate", FunctionDescriptor.ofVoid(ADDRESS, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_matrix_translate(double[] arg0, double arg1, double arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MH_cairo_1matrix_1translate.MH.invokeExact(lparg0, arg1, arg2);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1move_1to {
	static final MethodHandle MH = FFM.downcall("cairo_move_to", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_move_to(long arg0, double arg1, double arg2) {
	try {
		MH_cairo_1move_1to.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1new_1path {
	static final MethodHandle MH = FFM.downcall("cairo_new_path", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_new_path(long arg0) {
	try {
		MH_cairo_1new_1path.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1paint {
	static final MethodHandle MH = FFM.downcall("cairo_paint", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_paint(long arg0) {
	try {
		MH_cairo_1paint.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1paint_1with_1alpha {
	static final MethodHandle MH = FFM.downcall("cairo_paint_with_alpha", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE));
}
public static void cairo_paint_with_alpha(long arg0, double arg1) {
	try {
		MH_cairo_1paint_1with_1alpha.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int cairo_path_data_t_sizeof() {
	return (int) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_data_t_SIZEOF;
}

private static final class MH_cairo_1path_1destroy {
	static final MethodHandle MH = FFM.downcall("cairo_path_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_path_destroy(long arg0) {
	try {
		MH_cairo_1path_1destroy.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int cairo_path_t_sizeof() {
	return (int) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_t_SIZEOF;
}

private static final class MH_cairo_1pattern_1add_1color_1stop_1rgba {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_add_color_stop_rgba", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_pattern_add_color_stop_rgba(long arg0, double arg1, double arg2, double arg3, double arg4, double arg5) {
	try {
		MH_cairo_1pattern_1add_1color_1stop_1rgba.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pattern_1create_1for_1surface {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_create_for_surface", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_pattern_create_for_surface(long arg0) {
	try {
		long rc = (long) MH_cairo_1pattern_1create_1for_1surface.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pattern_1create_1linear {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_create_linear", FunctionDescriptor.of(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static long cairo_pattern_create_linear(double arg0, double arg1, double arg2, double arg3) {
	try {
		long rc = (long) MH_cairo_1pattern_1create_1linear.MH.invokeExact(arg0, arg1, arg2, arg3);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pattern_1destroy {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_pattern_destroy(long arg0) {
	try {
		MH_cairo_1pattern_1destroy.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pattern_1set_1extend {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_set_extend", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_pattern_set_extend(long arg0, int arg1) {
	try {
		MH_cairo_1pattern_1set_1extend.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pattern_1set_1filter {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_set_filter", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_pattern_set_filter(long arg0, int arg1) {
	try {
		MH_cairo_1pattern_1set_1filter.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pattern_1set_1matrix {
	static final MethodHandle MH = FFM.downcall("cairo_pattern_set_matrix", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void cairo_pattern_set_matrix(long arg0, double[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_cairo_1pattern_1set_1matrix.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pdf_1surface_1create {
	static final MethodHandle MH = FFM.downcallOptional("cairo_pdf_surface_create", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static long cairo_pdf_surface_create(byte[] arg0, double arg1, double arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_cairo_1pdf_1surface_1create.MH != null) {
			rc = (long) MH_cairo_1pdf_1surface_1create.MH.invokeExact(lparg0, arg1, arg2);
		}
		FFM.copyOut(lparg0, arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pdf_1surface_1set_1size {
	static final MethodHandle MH = FFM.downcallOptional("cairo_pdf_surface_set_size", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_pdf_surface_set_size(long arg0, double arg1, double arg2) {
	try {
		if (MH_cairo_1pdf_1surface_1set_1size.MH != null) {
			MH_cairo_1pdf_1surface_1set_1size.MH.invokeExact(arg0, arg1, arg2);
		}
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1pop_1group_1to_1source {
	static final MethodHandle MH = FFM.downcall("cairo_pop_group_to_source", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_pop_group_to_source(long arg0) {
	try {
		MH_cairo_1pop_1group_1to_1source.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1ps_1surface_1set_1size {
	static final MethodHandle MH = FFM.downcallOptional("cairo_ps_surface_set_size", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_ps_surface_set_size(long arg0, double arg1, double arg2) {
	try {
		if (MH_cairo_1ps_1surface_1set_1size.MH != null) {
			MH_cairo_1ps_1surface_1set_1size.MH.invokeExact(arg0, arg1, arg2);
		}
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1push_1group {
	static final MethodHandle MH = FFM.downcall("cairo_push_group", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_push_group(long arg0) {
	try {
		MH_cairo_1push_1group.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1rectangle {
	static final MethodHandle MH = FFM.downcall("cairo_rectangle", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_rectangle(long arg0, double arg1, double arg2, double arg3, double arg4) {
	try {
		MH_cairo_1rectangle.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int cairo_rectangle_int_t_sizeof() {
	return (int) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_SIZEOF;
}

private static final class MH_cairo_1reference {
	static final MethodHandle MH = FFM.downcall("cairo_reference", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_reference(long arg0) {
	try {
		long rc = (long) MH_cairo_1reference.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1contains_1point {
	static final MethodHandle MH = FFM.downcall("cairo_region_contains_point", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static boolean cairo_region_contains_point(long arg0, int arg1, int arg2) {
	try {
		int rc = (int) MH_cairo_1region_1contains_1point.MH.invokeExact(arg0, arg1, arg2);
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1contains_1rectangle {
	static final MethodHandle MH = FFM.downcall("cairo_region_contains_rectangle", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static long cairo_region_contains_rectangle(long arg0, org.eclipse.swt.internal.cairo.cairo_rectangle_int_t arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_write(lparg1, arg1);
		int rc = (int) MH_cairo_1region_1contains_1rectangle.MH.invokeExact(arg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_read(lparg1, arg1);
		return (long) rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1copy {
	static final MethodHandle MH = FFM.downcall("cairo_region_copy", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long cairo_region_copy(long arg0) {
	try {
		long rc = (long) MH_cairo_1region_1copy.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1create {
	static final MethodHandle MH = FFM.downcall("cairo_region_create", FunctionDescriptor.of(JAVA_LONG));
}
public static long cairo_region_create() {
	try {
		long rc = (long) MH_cairo_1region_1create.MH.invokeExact();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1create_1rectangle {
	static final MethodHandle MH = FFM.downcall("cairo_region_create_rectangle", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long cairo_region_create_rectangle(org.eclipse.swt.internal.cairo.cairo_rectangle_int_t arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_write(lparg0, arg0);
		long rc = (long) MH_cairo_1region_1create_1rectangle.MH.invokeExact(lparg0);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_read(lparg0, arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1destroy {
	static final MethodHandle MH = FFM.downcall("cairo_region_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_region_destroy(long arg0) {
	try {
		MH_cairo_1region_1destroy.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1get_1extents {
	static final MethodHandle MH = FFM.downcall("cairo_region_get_extents", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void cairo_region_get_extents(long arg0, org.eclipse.swt.internal.cairo.cairo_rectangle_int_t arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_SIZEOF, 16);
		MH_cairo_1region_1get_1extents.MH.invokeExact(arg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_read(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1get_1rectangle {
	static final MethodHandle MH = FFM.downcall("cairo_region_get_rectangle", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_LONG));
}
public static void cairo_region_get_rectangle(long arg0, int arg1, long arg2) {
	try {
		MH_cairo_1region_1get_1rectangle.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1intersect {
	static final MethodHandle MH = FFM.downcall("cairo_region_intersect", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void cairo_region_intersect(long arg0, long arg1) {
	try {
		MH_cairo_1region_1intersect.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1is_1empty {
	static final MethodHandle MH = FFM.downcall("cairo_region_is_empty", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static boolean cairo_region_is_empty(long arg0) {
	try {
		int rc = (int) MH_cairo_1region_1is_1empty.MH.invokeExact(arg0);
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1num_1rectangles {
	static final MethodHandle MH = FFM.downcall("cairo_region_num_rectangles", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_region_num_rectangles(long arg0) {
	try {
		int rc = (int) MH_cairo_1region_1num_1rectangles.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1subtract {
	static final MethodHandle MH = FFM.downcall("cairo_region_subtract", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void cairo_region_subtract(long arg0, long arg1) {
	try {
		MH_cairo_1region_1subtract.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1translate {
	static final MethodHandle MH = FFM.downcall("cairo_region_translate", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void cairo_region_translate(long arg0, int arg1, int arg2) {
	try {
		MH_cairo_1region_1translate.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1union {
	static final MethodHandle MH = FFM.downcall("cairo_region_union", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void cairo_region_union(long arg0, long arg1) {
	try {
		MH_cairo_1region_1union.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1region_1union_1rectangle {
	static final MethodHandle MH = FFM.downcall("cairo_region_union_rectangle", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void cairo_region_union_rectangle(long arg0, org.eclipse.swt.internal.cairo.cairo_rectangle_int_t arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_write(lparg1, arg1);
		MH_cairo_1region_1union_1rectangle.MH.invokeExact(arg0, lparg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1reset_1clip {
	static final MethodHandle MH = FFM.downcall("cairo_reset_clip", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_reset_clip(long arg0) {
	try {
		MH_cairo_1reset_1clip.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1restore {
	static final MethodHandle MH = FFM.downcall("cairo_restore", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_restore(long arg0) {
	try {
		MH_cairo_1restore.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1save {
	static final MethodHandle MH = FFM.downcall("cairo_save", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_save(long arg0) {
	try {
		MH_cairo_1save.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1scale {
	static final MethodHandle MH = FFM.downcall("cairo_scale", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_scale(long arg0, double arg1, double arg2) {
	try {
		MH_cairo_1scale.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1select_1font_1face {
	static final MethodHandle MH = FFM.downcall("cairo_select_font_face", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT));
}
public static void cairo_select_font_face(long arg0, byte[] arg1, int arg2, int arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_cairo_1select_1font_1face.MH.invokeExact(arg0, lparg1, arg2, arg3);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1antialias {
	static final MethodHandle MH = FFM.downcall("cairo_set_antialias", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_set_antialias(long arg0, int arg1) {
	try {
		MH_cairo_1set_1antialias.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1dash {
	static final MethodHandle MH = FFM.downcall("cairo_set_dash", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_DOUBLE));
}
public static void cairo_set_dash(long arg0, double[] arg1, int arg2, double arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_cairo_1set_1dash.MH.invokeExact(arg0, lparg1, arg2, arg3);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1fill_1rule {
	static final MethodHandle MH = FFM.downcall("cairo_set_fill_rule", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_set_fill_rule(long arg0, int arg1) {
	try {
		MH_cairo_1set_1fill_1rule.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1font_1size {
	static final MethodHandle MH = FFM.downcall("cairo_set_font_size", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE));
}
public static void cairo_set_font_size(long arg0, double arg1) {
	try {
		MH_cairo_1set_1font_1size.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1line_1cap {
	static final MethodHandle MH = FFM.downcall("cairo_set_line_cap", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_set_line_cap(long arg0, int arg1) {
	try {
		MH_cairo_1set_1line_1cap.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1line_1join {
	static final MethodHandle MH = FFM.downcall("cairo_set_line_join", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_set_line_join(long arg0, int arg1) {
	try {
		MH_cairo_1set_1line_1join.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1line_1width {
	static final MethodHandle MH = FFM.downcall("cairo_set_line_width", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE));
}
public static void cairo_set_line_width(long arg0, double arg1) {
	try {
		MH_cairo_1set_1line_1width.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1matrix {
	static final MethodHandle MH = FFM.downcall("cairo_set_matrix", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void cairo_set_matrix(long arg0, double[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_cairo_1set_1matrix.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1miter_1limit {
	static final MethodHandle MH = FFM.downcall("cairo_set_miter_limit", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE));
}
public static void cairo_set_miter_limit(long arg0, double arg1) {
	try {
		MH_cairo_1set_1miter_1limit.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1operator {
	static final MethodHandle MH = FFM.downcall("cairo_set_operator", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void cairo_set_operator(long arg0, int arg1) {
	try {
		MH_cairo_1set_1operator.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1source {
	static final MethodHandle MH = FFM.downcall("cairo_set_source", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void cairo_set_source(long arg0, long arg1) {
	try {
		MH_cairo_1set_1source.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1source_1rgb {
	static final MethodHandle MH = FFM.downcall("cairo_set_source_rgb", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_set_source_rgb(long arg0, double arg1, double arg2, double arg3) {
	try {
		MH_cairo_1set_1source_1rgb.MH.invokeExact(arg0, arg1, arg2, arg3);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1source_1rgba {
	static final MethodHandle MH = FFM.downcall("cairo_set_source_rgba", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_set_source_rgba(long arg0, double arg1, double arg2, double arg3, double arg4) {
	try {
		MH_cairo_1set_1source_1rgba.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1source_1surface {
	static final MethodHandle MH = FFM.downcall("cairo_set_source_surface", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_set_source_surface(long arg0, long arg1, double arg2, double arg3) {
	try {
		MH_cairo_1set_1source_1surface.MH.invokeExact(arg0, arg1, arg2, arg3);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1set_1tolerance {
	static final MethodHandle MH = FFM.downcall("cairo_set_tolerance", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE));
}
public static void cairo_set_tolerance(long arg0, double arg1) {
	try {
		MH_cairo_1set_1tolerance.MH.invokeExact(arg0, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1show_1page {
	static final MethodHandle MH = FFM.downcall("cairo_show_page", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_show_page(long arg0) {
	try {
		MH_cairo_1show_1page.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1stroke {
	static final MethodHandle MH = FFM.downcall("cairo_stroke", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_stroke(long arg0) {
	try {
		MH_cairo_1stroke.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1destroy {
	static final MethodHandle MH = FFM.downcall("cairo_surface_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_surface_destroy(long arg0) {
	try {
		MH_cairo_1surface_1destroy.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1finish {
	static final MethodHandle MH = FFM.downcall("cairo_surface_finish", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_surface_finish(long arg0) {
	try {
		MH_cairo_1surface_1finish.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1flush {
	static final MethodHandle MH = FFM.downcall("cairo_surface_flush", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_surface_flush(long arg0) {
	try {
		MH_cairo_1surface_1flush.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1get_1content {
	static final MethodHandle MH = FFM.downcall("cairo_surface_get_content", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_surface_get_content(long arg0) {
	try {
		int rc = (int) MH_cairo_1surface_1get_1content.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1get_1device_1scale {
	static final MethodHandle MH = FFM.downcallOptional("cairo_surface_get_device_scale", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, ADDRESS));
}
public static void cairo_surface_get_device_scale(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		if (MH_cairo_1surface_1get_1device_1scale.MH != null) {
			MH_cairo_1surface_1get_1device_1scale.MH.invokeExact(arg0, lparg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1get_1type {
	static final MethodHandle MH = FFM.downcall("cairo_surface_get_type", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_surface_get_type(long arg0) {
	try {
		int rc = (int) MH_cairo_1surface_1get_1type.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1mark_1dirty {
	static final MethodHandle MH = FFM.downcall("cairo_surface_mark_dirty", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_surface_mark_dirty(long arg0) {
	try {
		MH_cairo_1surface_1mark_1dirty.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1reference {
	static final MethodHandle MH = FFM.downcall("cairo_surface_reference", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void cairo_surface_reference(long arg0) {
	try {
		MH_cairo_1surface_1reference.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1surface_1set_1device_1scale {
	static final MethodHandle MH = FFM.downcallOptional("cairo_surface_set_device_scale", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_surface_set_device_scale(long arg0, double arg1, double arg2) {
	try {
		if (MH_cairo_1surface_1set_1device_1scale.MH != null) {
			MH_cairo_1surface_1set_1device_1scale.MH.invokeExact(arg0, arg1, arg2);
		}
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1transform {
	static final MethodHandle MH = FFM.downcall("cairo_transform", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void cairo_transform(long arg0, double[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_cairo_1transform.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1translate {
	static final MethodHandle MH = FFM.downcall("cairo_translate", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void cairo_translate(long arg0, double arg1, double arg2) {
	try {
		MH_cairo_1translate.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1user_1to_1device_1distance {
	static final MethodHandle MH = FFM.downcall("cairo_user_to_device_distance", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, ADDRESS));
}
public static void cairo_user_to_device_distance(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MH_cairo_1user_1to_1device_1distance.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1version {
	static final MethodHandle MH = FFM.downcall("cairo_version", FunctionDescriptor.of(JAVA_INT));
}
public static int cairo_version() {
	try {
		int rc = (int) MH_cairo_1version.MH.invokeExact();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1xlib_1surface_1get_1height {
	static final MethodHandle MH = FFM.downcallOptional("cairo_xlib_surface_get_height", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_xlib_surface_get_height(long arg0) {
	try {
		int rc = 0;
		if (MH_cairo_1xlib_1surface_1get_1height.MH != null) {
			rc = (int) MH_cairo_1xlib_1surface_1get_1height.MH.invokeExact(arg0);
		}
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_cairo_1xlib_1surface_1get_1width {
	static final MethodHandle MH = FFM.downcallOptional("cairo_xlib_surface_get_width", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int cairo_xlib_surface_get_width(long arg0) {
	try {
		int rc = 0;
		if (MH_cairo_1xlib_1surface_1get_1width.MH != null) {
			rc = (int) MH_cairo_1xlib_1surface_1get_1width.MH.invokeExact(arg0);
		}
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__Lorg_eclipse_swt_internal_cairo_cairo_1path_1data_1t_2JJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.cairo.cairo_path_data_t arg0, long arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_data_t_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_data_t_write(lparg0, arg0);
		MH_memmove__Lorg_eclipse_swt_internal_cairo_cairo_1path_1data_1t_2JJ.MH.invokeExact(lparg0, arg1, arg2);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_data_t_read(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__Lorg_eclipse_swt_internal_cairo_cairo_1path_1t_2JJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.cairo.cairo_path_t arg0, long arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_t_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_t_write(lparg0, arg0);
		MH_memmove__Lorg_eclipse_swt_internal_cairo_cairo_1path_1t_2JJ.MH.invokeExact(lparg0, arg1, arg2);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_path_t_read(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__Lorg_eclipse_swt_internal_cairo_cairo_1rectangle_1int_1t_2JJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.cairo.cairo_rectangle_int_t arg0, long arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_write(lparg0, arg0);
		MH_memmove__Lorg_eclipse_swt_internal_cairo_cairo_1rectangle_1int_1t_2JJ.MH.invokeExact(lparg0, arg1, arg2);
		if (arg0 != null) org.eclipse.swt.internal.cairo.Structs_FFM.cairo_rectangle_int_t_read(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3DJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(double[] arg0, long arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MH_memmove___3DJJ.MH.invokeExact(lparg0, arg1, arg2);
		FFM.copyOut(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
