/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.cairo;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long cairo_path_data_t_SIZEOF = 16L;
public static final long cairo_path_data_t_TYPE_OFFSET = 0L;
public static final long cairo_path_data_t_LENGTH_OFFSET = 4L;

public static void cairo_path_data_t_read(MemorySegment s, org.eclipse.swt.internal.cairo.cairo_path_data_t o) {
	o.type = s.get(JAVA_INT_UNALIGNED, 0L);
	o.length = s.get(JAVA_INT_UNALIGNED, 4L);
}

public static void cairo_path_data_t_write(MemorySegment s, org.eclipse.swt.internal.cairo.cairo_path_data_t o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.type);
	s.set(JAVA_INT_UNALIGNED, 4L, o.length);
}

public static final long cairo_path_t_SIZEOF = 24L;
public static final long cairo_path_t_STATUS_OFFSET = 0L;
public static final long cairo_path_t_DATA_OFFSET = 8L;
public static final long cairo_path_t_NUM_DATA_OFFSET = 16L;

public static void cairo_path_t_read(MemorySegment s, org.eclipse.swt.internal.cairo.cairo_path_t o) {
	o.status = s.get(JAVA_INT_UNALIGNED, 0L);
	o.data = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.num_data = s.get(JAVA_INT_UNALIGNED, 16L);
}

public static void cairo_path_t_write(MemorySegment s, org.eclipse.swt.internal.cairo.cairo_path_t o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.status);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.data);
	s.set(JAVA_INT_UNALIGNED, 16L, o.num_data);
}

public static final long cairo_rectangle_int_t_SIZEOF = 16L;
public static final long cairo_rectangle_int_t_X_OFFSET = 0L;
public static final long cairo_rectangle_int_t_Y_OFFSET = 4L;
public static final long cairo_rectangle_int_t_WIDTH_OFFSET = 8L;
public static final long cairo_rectangle_int_t_HEIGHT_OFFSET = 12L;

public static void cairo_rectangle_int_t_read(MemorySegment s, org.eclipse.swt.internal.cairo.cairo_rectangle_int_t o) {
	o.x = s.get(JAVA_INT_UNALIGNED, 0L);
	o.y = s.get(JAVA_INT_UNALIGNED, 4L);
	o.width = s.get(JAVA_INT_UNALIGNED, 8L);
	o.height = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void cairo_rectangle_int_t_write(MemorySegment s, org.eclipse.swt.internal.cairo.cairo_rectangle_int_t o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.x);
	s.set(JAVA_INT_UNALIGNED, 4L, o.y);
	s.set(JAVA_INT_UNALIGNED, 8L, o.width);
	s.set(JAVA_INT_UNALIGNED, 12L, o.height);
}

}
