/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.accessibility.gtk;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class ATK_FFM {

public static int AtkAttribute_sizeof() {
	return (int) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkAttribute_SIZEOF;
}

public static int AtkTextRange_sizeof() {
	return (int) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRange_SIZEOF;
}

public static int AtkTextRectangle_sizeof() {
	return (int) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_SIZEOF;
}

private static final class MH_atk_1object_1add_1relationship {
	static final MethodHandle MH = FFM.downcall("atk_object_add_relationship", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_LONG));
}
public static boolean atk_object_add_relationship(long arg0, int arg1, long arg2) {
	try {
		int rc = (int) MH_atk_1object_1add_1relationship.MH.invokeExact(arg0, arg1, arg2);
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_atk_1object_1notify_1state_1change {
	static final MethodHandle MH = FFM.downcall("atk_object_notify_state_change", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT));
}
public static void atk_object_notify_state_change(long arg0, int arg1, boolean arg2) {
	try {
		MH_atk_1object_1notify_1state_1change.MH.invokeExact(arg0, (long) arg1, (int) (arg2 ? 1 : 0));
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_atk_1object_1remove_1relationship {
	static final MethodHandle MH = FFM.downcall("atk_object_remove_relationship", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_LONG));
}
public static boolean atk_object_remove_relationship(long arg0, int arg1, long arg2) {
	try {
		int rc = (int) MH_atk_1object_1remove_1relationship.MH.invokeExact(arg0, arg1, arg2);
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_atk_1state_1set_1add_1state {
	static final MethodHandle MH = FFM.downcall("atk_state_set_add_state", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT));
}
public static boolean atk_state_set_add_state(long arg0, int arg1) {
	try {
		int rc = (int) MH_atk_1state_1set_1add_1state.MH.invokeExact(arg0, arg1);
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_atk_1text_1attribute_1get_1name {
	static final MethodHandle MH = FFM.downcall("atk_text_attribute_get_name", FunctionDescriptor.of(JAVA_LONG, JAVA_INT));
}
public static long atk_text_attribute_get_name(int arg0) {
	try {
		long rc = (long) MH_atk_1text_1attribute_1get_1name.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_atk_1text_1attribute_1get_1value {
	static final MethodHandle MH = FFM.downcall("atk_text_attribute_get_value", FunctionDescriptor.of(JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static long atk_text_attribute_get_value(int arg0, int arg1) {
	try {
		long rc = (long) MH_atk_1text_1attribute_1get_1value.MH.invokeExact(arg0, arg1);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__JLorg_eclipse_swt_internal_accessibility_gtk_AtkAttribute_2I {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static void memmove(long arg0, org.eclipse.swt.internal.accessibility.gtk.AtkAttribute arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkAttribute_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkAttribute_write(lparg1, arg1);
		MH_memmove__JLorg_eclipse_swt_internal_accessibility_gtk_AtkAttribute_2I.MH.invokeExact(arg0, lparg1, (long) arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__JLorg_eclipse_swt_internal_accessibility_gtk_AtkTextRange_2I {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static void memmove(long arg0, org.eclipse.swt.internal.accessibility.gtk.AtkTextRange arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRange_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRange_write(lparg1, arg1);
		MH_memmove__JLorg_eclipse_swt_internal_accessibility_gtk_AtkTextRange_2I.MH.invokeExact(arg0, lparg1, (long) arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__JLorg_eclipse_swt_internal_accessibility_gtk_AtkTextRectangle_2I {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static void memmove(long arg0, org.eclipse.swt.internal.accessibility.gtk.AtkTextRectangle arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_write(lparg1, arg1);
		MH_memmove__JLorg_eclipse_swt_internal_accessibility_gtk_AtkTextRectangle_2I.MH.invokeExact(arg0, lparg1, (long) arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkActionIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkActionIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkActionIface_SIZEOF), arg0);
}

private static final class MH_memmove__Lorg_eclipse_swt_internal_accessibility_gtk_AtkAttribute_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkAttribute arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkAttribute_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkAttribute_write(lparg0, arg0);
		MH_memmove__Lorg_eclipse_swt_internal_accessibility_gtk_AtkAttribute_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkAttribute_read(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkComponentIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkComponentIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkComponentIface_SIZEOF), arg0);
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkEditableTextIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkEditableTextIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkEditableTextIface_SIZEOF), arg0);
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkHypertextIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkHypertextIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkHypertextIface_SIZEOF), arg0);
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkObjectClass arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkObjectClass_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkObjectClass_SIZEOF), arg0);
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkSelectionIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkSelectionIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkSelectionIface_SIZEOF), arg0);
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkTableIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTableIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTableIface_SIZEOF), arg0);
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkTextIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextIface_SIZEOF), arg0);
}

private static final class MH_memmove__Lorg_eclipse_swt_internal_accessibility_gtk_AtkTextRange_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkTextRange arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRange_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRange_write(lparg0, arg0);
		MH_memmove__Lorg_eclipse_swt_internal_accessibility_gtk_AtkTextRange_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRange_read(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__Lorg_eclipse_swt_internal_accessibility_gtk_AtkTextRectangle_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkTextRectangle arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_write(lparg0, arg0);
		MH_memmove__Lorg_eclipse_swt_internal_accessibility_gtk_AtkTextRectangle_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_read(lparg0, arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static void memmove(org.eclipse.swt.internal.accessibility.gtk.AtkValueIface arg0, long arg1) {
	if (arg0 != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkValueIface_read(FFM.segment(arg1, org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkValueIface_SIZEOF), arg0);
}

}
