/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.accessibility.gtk;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long AtkActionIface_SIZEOF = 72L;

public static void AtkActionIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkActionIface o) {
	o.do_action = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.get_n_actions = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.get_description = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.get_name = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.get_keybinding = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.set_description = s.get(JAVA_LONG_UNALIGNED, 56L);
}

public static void AtkActionIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkActionIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.do_action);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.get_n_actions);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.get_description);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.get_name);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.get_keybinding);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.set_description);
}

public static final long AtkAttribute_SIZEOF = 16L;

public static void AtkAttribute_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkAttribute o) {
	o.name = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.value = s.get(JAVA_LONG_UNALIGNED, 8L);
}

public static void AtkAttribute_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkAttribute o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.name);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.value);
}

public static final long AtkComponentIface_SIZEOF = 152L;

public static void AtkComponentIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkComponentIface o) {
	o.add_focus_handler = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.contains = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.ref_accessible_at_point = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.get_extents = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.get_position = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.get_size = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.grab_focus = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.remove_focus_handler = s.get(JAVA_LONG_UNALIGNED, 72L);
	o.set_extents = s.get(JAVA_LONG_UNALIGNED, 80L);
	o.set_position = s.get(JAVA_LONG_UNALIGNED, 88L);
	o.set_size = s.get(JAVA_LONG_UNALIGNED, 96L);
	o.get_layer = s.get(JAVA_LONG_UNALIGNED, 104L);
	o.get_mdi_zorder = s.get(JAVA_LONG_UNALIGNED, 112L);
}

public static void AtkComponentIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkComponentIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.add_focus_handler);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.contains);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.ref_accessible_at_point);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.get_extents);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.get_position);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.get_size);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.grab_focus);
	s.set(JAVA_LONG_UNALIGNED, 72L, o.remove_focus_handler);
	s.set(JAVA_LONG_UNALIGNED, 80L, o.set_extents);
	s.set(JAVA_LONG_UNALIGNED, 88L, o.set_position);
	s.set(JAVA_LONG_UNALIGNED, 96L, o.set_size);
	s.set(JAVA_LONG_UNALIGNED, 104L, o.get_layer);
	s.set(JAVA_LONG_UNALIGNED, 112L, o.get_mdi_zorder);
}

public static final long AtkEditableTextIface_SIZEOF = 72L;

public static void AtkEditableTextIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkEditableTextIface o) {
	o.set_run_attributes = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.set_text_contents = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.insert_text = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.copy_text = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.cut_text = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.delete_text = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.paste_text = s.get(JAVA_LONG_UNALIGNED, 64L);
}

public static void AtkEditableTextIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkEditableTextIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.set_run_attributes);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.set_text_contents);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.insert_text);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.copy_text);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.cut_text);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.delete_text);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.paste_text);
}

public static final long AtkHypertextIface_SIZEOF = 48L;

public static void AtkHypertextIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkHypertextIface o) {
	o.get_link = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.get_n_links = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.get_link_index = s.get(JAVA_LONG_UNALIGNED, 32L);
}

public static void AtkHypertextIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkHypertextIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.get_link);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.get_n_links);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.get_link_index);
}

public static final long AtkObjectClass_SIZEOF = 352L;

public static void AtkObjectClass_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkObjectClass o) {
	o.get_name = s.get(JAVA_LONG_UNALIGNED, 136L);
	o.get_description = s.get(JAVA_LONG_UNALIGNED, 144L);
	o.get_parent = s.get(JAVA_LONG_UNALIGNED, 152L);
	o.get_n_children = s.get(JAVA_LONG_UNALIGNED, 160L);
	o.ref_child = s.get(JAVA_LONG_UNALIGNED, 168L);
	o.get_index_in_parent = s.get(JAVA_LONG_UNALIGNED, 176L);
	o.ref_relation_set = s.get(JAVA_LONG_UNALIGNED, 184L);
	o.get_role = s.get(JAVA_LONG_UNALIGNED, 192L);
	o.get_layer = s.get(JAVA_LONG_UNALIGNED, 200L);
	o.get_mdi_zorder = s.get(JAVA_LONG_UNALIGNED, 208L);
	o.ref_state_set = s.get(JAVA_LONG_UNALIGNED, 216L);
	o.set_name = s.get(JAVA_LONG_UNALIGNED, 224L);
	o.set_description = s.get(JAVA_LONG_UNALIGNED, 232L);
	o.set_parent = s.get(JAVA_LONG_UNALIGNED, 240L);
	o.set_role = s.get(JAVA_LONG_UNALIGNED, 248L);
	o.connect_property_change_handler = s.get(JAVA_LONG_UNALIGNED, 256L);
	o.remove_property_change_handler = s.get(JAVA_LONG_UNALIGNED, 264L);
	o.initialize = s.get(JAVA_LONG_UNALIGNED, 272L);
	o.children_changed = s.get(JAVA_LONG_UNALIGNED, 280L);
	o.focus_event = s.get(JAVA_LONG_UNALIGNED, 288L);
	o.property_change = s.get(JAVA_LONG_UNALIGNED, 296L);
	o.state_change = s.get(JAVA_LONG_UNALIGNED, 304L);
	o.visible_data_changed = s.get(JAVA_LONG_UNALIGNED, 312L);
	o.get_attributes = s.get(JAVA_LONG_UNALIGNED, 328L);
}

public static void AtkObjectClass_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkObjectClass o) {
	s.set(JAVA_LONG_UNALIGNED, 136L, o.get_name);
	s.set(JAVA_LONG_UNALIGNED, 144L, o.get_description);
	s.set(JAVA_LONG_UNALIGNED, 152L, o.get_parent);
	s.set(JAVA_LONG_UNALIGNED, 160L, o.get_n_children);
	s.set(JAVA_LONG_UNALIGNED, 168L, o.ref_child);
	s.set(JAVA_LONG_UNALIGNED, 176L, o.get_index_in_parent);
	s.set(JAVA_LONG_UNALIGNED, 184L, o.ref_relation_set);
	s.set(JAVA_LONG_UNALIGNED, 192L, o.get_role);
	s.set(JAVA_LONG_UNALIGNED, 200L, o.get_layer);
	s.set(JAVA_LONG_UNALIGNED, 208L, o.get_mdi_zorder);
	s.set(JAVA_LONG_UNALIGNED, 216L, o.ref_state_set);
	s.set(JAVA_LONG_UNALIGNED, 224L, o.set_name);
	s.set(JAVA_LONG_UNALIGNED, 232L, o.set_description);
	s.set(JAVA_LONG_UNALIGNED, 240L, o.set_parent);
	s.set(JAVA_LONG_UNALIGNED, 248L, o.set_role);
	s.set(JAVA_LONG_UNALIGNED, 256L, o.connect_property_change_handler);
	s.set(JAVA_LONG_UNALIGNED, 264L, o.remove_property_change_handler);
	s.set(JAVA_LONG_UNALIGNED, 272L, o.initialize);
	s.set(JAVA_LONG_UNALIGNED, 280L, o.children_changed);
	s.set(JAVA_LONG_UNALIGNED, 288L, o.focus_event);
	s.set(JAVA_LONG_UNALIGNED, 296L, o.property_change);
	s.set(JAVA_LONG_UNALIGNED, 304L, o.state_change);
	s.set(JAVA_LONG_UNALIGNED, 312L, o.visible_data_changed);
	s.set(JAVA_LONG_UNALIGNED, 328L, o.get_attributes);
}

public static final long AtkSelectionIface_SIZEOF = 80L;

public static void AtkSelectionIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkSelectionIface o) {
	o.add_selection = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.clear_selection = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.ref_selection = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.get_selection_count = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.is_child_selected = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.remove_selection = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.select_all_selection = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.selection_changed = s.get(JAVA_LONG_UNALIGNED, 72L);
}

public static void AtkSelectionIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkSelectionIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.add_selection);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.clear_selection);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.ref_selection);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.get_selection_count);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.is_child_selected);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.remove_selection);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.select_all_selection);
	s.set(JAVA_LONG_UNALIGNED, 72L, o.selection_changed);
}

public static final long AtkTableIface_SIZEOF = 304L;

public static void AtkTableIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTableIface o) {
	o.ref_at = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.get_index_at = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.get_column_at_index = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.get_row_at_index = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.get_n_columns = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.get_n_rows = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.get_column_extent_at = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.get_row_extent_at = s.get(JAVA_LONG_UNALIGNED, 72L);
	o.get_caption = s.get(JAVA_LONG_UNALIGNED, 80L);
	o.get_column_description = s.get(JAVA_LONG_UNALIGNED, 88L);
	o.get_column_header = s.get(JAVA_LONG_UNALIGNED, 96L);
	o.get_row_description = s.get(JAVA_LONG_UNALIGNED, 104L);
	o.get_row_header = s.get(JAVA_LONG_UNALIGNED, 112L);
	o.get_summary = s.get(JAVA_LONG_UNALIGNED, 120L);
	o.set_caption = s.get(JAVA_LONG_UNALIGNED, 128L);
	o.set_column_description = s.get(JAVA_LONG_UNALIGNED, 136L);
	o.set_column_header = s.get(JAVA_LONG_UNALIGNED, 144L);
	o.set_row_description = s.get(JAVA_LONG_UNALIGNED, 152L);
	o.set_row_header = s.get(JAVA_LONG_UNALIGNED, 160L);
	o.set_summary = s.get(JAVA_LONG_UNALIGNED, 168L);
	o.get_selected_columns = s.get(JAVA_LONG_UNALIGNED, 176L);
	o.get_selected_rows = s.get(JAVA_LONG_UNALIGNED, 184L);
	o.is_column_selected = s.get(JAVA_LONG_UNALIGNED, 192L);
	o.is_row_selected = s.get(JAVA_LONG_UNALIGNED, 200L);
	o.is_selected = s.get(JAVA_LONG_UNALIGNED, 208L);
	o.add_row_selection = s.get(JAVA_LONG_UNALIGNED, 216L);
	o.remove_row_selection = s.get(JAVA_LONG_UNALIGNED, 224L);
	o.add_column_selection = s.get(JAVA_LONG_UNALIGNED, 232L);
	o.remove_column_selection = s.get(JAVA_LONG_UNALIGNED, 240L);
	o.row_inserted = s.get(JAVA_LONG_UNALIGNED, 248L);
	o.column_inserted = s.get(JAVA_LONG_UNALIGNED, 256L);
	o.row_deleted = s.get(JAVA_LONG_UNALIGNED, 264L);
	o.column_deleted = s.get(JAVA_LONG_UNALIGNED, 272L);
	o.row_reordered = s.get(JAVA_LONG_UNALIGNED, 280L);
	o.column_reordered = s.get(JAVA_LONG_UNALIGNED, 288L);
	o.model_changed = s.get(JAVA_LONG_UNALIGNED, 296L);
}

public static void AtkTableIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTableIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.ref_at);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.get_index_at);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.get_column_at_index);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.get_row_at_index);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.get_n_columns);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.get_n_rows);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.get_column_extent_at);
	s.set(JAVA_LONG_UNALIGNED, 72L, o.get_row_extent_at);
	s.set(JAVA_LONG_UNALIGNED, 80L, o.get_caption);
	s.set(JAVA_LONG_UNALIGNED, 88L, o.get_column_description);
	s.set(JAVA_LONG_UNALIGNED, 96L, o.get_column_header);
	s.set(JAVA_LONG_UNALIGNED, 104L, o.get_row_description);
	s.set(JAVA_LONG_UNALIGNED, 112L, o.get_row_header);
	s.set(JAVA_LONG_UNALIGNED, 120L, o.get_summary);
	s.set(JAVA_LONG_UNALIGNED, 128L, o.set_caption);
	s.set(JAVA_LONG_UNALIGNED, 136L, o.set_column_description);
	s.set(JAVA_LONG_UNALIGNED, 144L, o.set_column_header);
	s.set(JAVA_LONG_UNALIGNED, 152L, o.set_row_description);
	s.set(JAVA_LONG_UNALIGNED, 160L, o.set_row_header);
	s.set(JAVA_LONG_UNALIGNED, 168L, o.set_summary);
	s.set(JAVA_LONG_UNALIGNED, 176L, o.get_selected_columns);
	s.set(JAVA_LONG_UNALIGNED, 184L, o.get_selected_rows);
	s.set(JAVA_LONG_UNALIGNED, 192L, o.is_column_selected);
	s.set(JAVA_LONG_UNALIGNED, 200L, o.is_row_selected);
	s.set(JAVA_LONG_UNALIGNED, 208L, o.is_selected);
	s.set(JAVA_LONG_UNALIGNED, 216L, o.add_row_selection);
	s.set(JAVA_LONG_UNALIGNED, 224L, o.remove_row_selection);
	s.set(JAVA_LONG_UNALIGNED, 232L, o.add_column_selection);
	s.set(JAVA_LONG_UNALIGNED, 240L, o.remove_column_selection);
	s.set(JAVA_LONG_UNALIGNED, 248L, o.row_inserted);
	s.set(JAVA_LONG_UNALIGNED, 256L, o.column_inserted);
	s.set(JAVA_LONG_UNALIGNED, 264L, o.row_deleted);
	s.set(JAVA_LONG_UNALIGNED, 272L, o.column_deleted);
	s.set(JAVA_LONG_UNALIGNED, 280L, o.row_reordered);
	s.set(JAVA_LONG_UNALIGNED, 288L, o.column_reordered);
	s.set(JAVA_LONG_UNALIGNED, 296L, o.model_changed);
}

public static final long AtkTextIface_SIZEOF = 224L;

public static void AtkTextIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTextIface o) {
	o.get_text = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.get_text_after_offset = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.get_text_at_offset = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.get_character_at_offset = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.get_text_before_offset = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.get_caret_offset = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.get_run_attributes = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.get_default_attributes = s.get(JAVA_LONG_UNALIGNED, 72L);
	o.get_character_extents = s.get(JAVA_LONG_UNALIGNED, 80L);
	o.get_character_count = s.get(JAVA_LONG_UNALIGNED, 88L);
	o.get_offset_at_point = s.get(JAVA_LONG_UNALIGNED, 96L);
	o.get_n_selections = s.get(JAVA_LONG_UNALIGNED, 104L);
	o.get_selection = s.get(JAVA_LONG_UNALIGNED, 112L);
	o.add_selection = s.get(JAVA_LONG_UNALIGNED, 120L);
	o.remove_selection = s.get(JAVA_LONG_UNALIGNED, 128L);
	o.set_selection = s.get(JAVA_LONG_UNALIGNED, 136L);
	o.set_caret_offset = s.get(JAVA_LONG_UNALIGNED, 144L);
	o.text_changed = s.get(JAVA_LONG_UNALIGNED, 152L);
	o.text_caret_moved = s.get(JAVA_LONG_UNALIGNED, 160L);
	o.text_selection_changed = s.get(JAVA_LONG_UNALIGNED, 168L);
	o.get_range_extents = s.get(JAVA_LONG_UNALIGNED, 184L);
	o.get_bounded_ranges = s.get(JAVA_LONG_UNALIGNED, 192L);
}

public static void AtkTextIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTextIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.get_text);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.get_text_after_offset);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.get_text_at_offset);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.get_character_at_offset);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.get_text_before_offset);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.get_caret_offset);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.get_run_attributes);
	s.set(JAVA_LONG_UNALIGNED, 72L, o.get_default_attributes);
	s.set(JAVA_LONG_UNALIGNED, 80L, o.get_character_extents);
	s.set(JAVA_LONG_UNALIGNED, 88L, o.get_character_count);
	s.set(JAVA_LONG_UNALIGNED, 96L, o.get_offset_at_point);
	s.set(JAVA_LONG_UNALIGNED, 104L, o.get_n_selections);
	s.set(JAVA_LONG_UNALIGNED, 112L, o.get_selection);
	s.set(JAVA_LONG_UNALIGNED, 120L, o.add_selection);
	s.set(JAVA_LONG_UNALIGNED, 128L, o.remove_selection);
	s.set(JAVA_LONG_UNALIGNED, 136L, o.set_selection);
	s.set(JAVA_LONG_UNALIGNED, 144L, o.set_caret_offset);
	s.set(JAVA_LONG_UNALIGNED, 152L, o.text_changed);
	s.set(JAVA_LONG_UNALIGNED, 160L, o.text_caret_moved);
	s.set(JAVA_LONG_UNALIGNED, 168L, o.text_selection_changed);
	s.set(JAVA_LONG_UNALIGNED, 184L, o.get_range_extents);
	s.set(JAVA_LONG_UNALIGNED, 192L, o.get_bounded_ranges);
}

public static final long AtkTextRange_SIZEOF = 32L;

public static void AtkTextRange_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTextRange o) {
	if (o.bounds != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_read(s.asSlice(0L), o.bounds);
	o.start_offset = s.get(JAVA_INT_UNALIGNED, 16L);
	o.end_offset = s.get(JAVA_INT_UNALIGNED, 20L);
	o.content = s.get(JAVA_LONG_UNALIGNED, 24L);
}

public static void AtkTextRange_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTextRange o) {
	if (o.bounds != null) org.eclipse.swt.internal.accessibility.gtk.Structs_FFM.AtkTextRectangle_write(s.asSlice(0L), o.bounds);
	s.set(JAVA_INT_UNALIGNED, 16L, o.start_offset);
	s.set(JAVA_INT_UNALIGNED, 20L, o.end_offset);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.content);
}

public static final long AtkTextRectangle_SIZEOF = 16L;

public static void AtkTextRectangle_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTextRectangle o) {
	o.x = s.get(JAVA_INT_UNALIGNED, 0L);
	o.y = s.get(JAVA_INT_UNALIGNED, 4L);
	o.width = s.get(JAVA_INT_UNALIGNED, 8L);
	o.height = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void AtkTextRectangle_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkTextRectangle o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.x);
	s.set(JAVA_INT_UNALIGNED, 4L, o.y);
	s.set(JAVA_INT_UNALIGNED, 8L, o.width);
	s.set(JAVA_INT_UNALIGNED, 12L, o.height);
}

public static final long AtkValueIface_SIZEOF = 96L;

public static void AtkValueIface_read(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkValueIface o) {
	o.get_current_value = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.get_maximum_value = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.get_minimum_value = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.set_current_value = s.get(JAVA_LONG_UNALIGNED, 40L);
}

public static void AtkValueIface_write(MemorySegment s, org.eclipse.swt.internal.accessibility.gtk.AtkValueIface o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.get_current_value);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.get_maximum_value);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.get_minimum_value);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.set_current_value);
}

}
