/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.win32.version;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class OsVersion_FFM {

public static int OSVERSIONINFOEX_sizeof() {
	return (int) org.eclipse.swt.internal.win32.version.Structs_FFM.OSVERSIONINFOEX_SIZEOF;
}

private static final class MH_RtlGetVersion {
	static final MethodHandle MH = FFM.downcallOptional(FFMLibraries.get("ntdll.dll"), "RtlGetVersion", FunctionDescriptor.of(JAVA_INT, ADDRESS));
}
public static int RtlGetVersion(org.eclipse.swt.internal.win32.version.OSVERSIONINFOEX arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.win32.version.Structs_FFM.OSVERSIONINFOEX_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.win32.version.Structs_FFM.OSVERSIONINFOEX_write(lparg0, arg0);
		int rc = 0;
		if (MH_RtlGetVersion.MH != null) {
			rc = (int) MH_RtlGetVersion.MH.invokeExact(lparg0);
		}
		if (arg0 != null) org.eclipse.swt.internal.win32.version.Structs_FFM.OSVERSIONINFOEX_read(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
