/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.win32.version;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long OSVERSIONINFOEX_SIZEOF = 284L;
public static final long OSVERSIONINFOEX_DWOSVERSIONINFOSIZE_OFFSET = 0L;
public static final long OSVERSIONINFOEX_DWMAJORVERSION_OFFSET = 4L;
public static final long OSVERSIONINFOEX_DWMINORVERSION_OFFSET = 8L;
public static final long OSVERSIONINFOEX_DWBUILDNUMBER_OFFSET = 12L;
public static final long OSVERSIONINFOEX_DWPLATFORMID_OFFSET = 16L;
public static final long OSVERSIONINFOEX_SZCSDVERSION_OFFSET = 20L;
public static final long OSVERSIONINFOEX_WSERVICEPACKMAJOR_OFFSET = 276L;
public static final long OSVERSIONINFOEX_WSERVICEPACKMINOR_OFFSET = 278L;
public static final long OSVERSIONINFOEX_WSUITEMASK_OFFSET = 280L;
public static final long OSVERSIONINFOEX_WPRODUCTTYPE_OFFSET = 282L;
public static final long OSVERSIONINFOEX_WRESERVED_OFFSET = 283L;

public static void OSVERSIONINFOEX_read(MemorySegment s, org.eclipse.swt.internal.win32.version.OSVERSIONINFOEX o) {
	o.dwOSVersionInfoSize = s.get(JAVA_INT_UNALIGNED, 0L);
	o.dwMajorVersion = s.get(JAVA_INT_UNALIGNED, 4L);
	o.dwMinorVersion = s.get(JAVA_INT_UNALIGNED, 8L);
	o.dwBuildNumber = s.get(JAVA_INT_UNALIGNED, 12L);
	o.dwPlatformId = s.get(JAVA_INT_UNALIGNED, 16L);
	MemorySegment.copy(s, JAVA_CHAR_UNALIGNED, 20L, o.szCSDVersion, 0, 128);
	o.wServicePackMajor = Short.toUnsignedInt(s.get(JAVA_SHORT_UNALIGNED, 276L));
	o.wServicePackMinor = Short.toUnsignedInt(s.get(JAVA_SHORT_UNALIGNED, 278L));
	o.wSuiteMask = Short.toUnsignedInt(s.get(JAVA_SHORT_UNALIGNED, 280L));
	o.wProductType = Byte.toUnsignedInt(s.get(JAVA_BYTE, 282L));
	o.wReserved = Byte.toUnsignedInt(s.get(JAVA_BYTE, 283L));
}

public static void OSVERSIONINFOEX_write(MemorySegment s, org.eclipse.swt.internal.win32.version.OSVERSIONINFOEX o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.dwOSVersionInfoSize);
	s.set(JAVA_INT_UNALIGNED, 4L, o.dwMajorVersion);
	s.set(JAVA_INT_UNALIGNED, 8L, o.dwMinorVersion);
	s.set(JAVA_INT_UNALIGNED, 12L, o.dwBuildNumber);
	s.set(JAVA_INT_UNALIGNED, 16L, o.dwPlatformId);
	MemorySegment.copy(o.szCSDVersion, 0, s, JAVA_CHAR_UNALIGNED, 20L, 128);
	s.set(JAVA_SHORT_UNALIGNED, 276L, (short) o.wServicePackMajor);
	s.set(JAVA_SHORT_UNALIGNED, 278L, (short) o.wServicePackMinor);
	s.set(JAVA_SHORT_UNALIGNED, 280L, (short) o.wSuiteMask);
	s.set(JAVA_BYTE, 282L, (byte) o.wProductType);
	s.set(JAVA_BYTE, 283L, (byte) o.wReserved);
}

}
