/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.ole.win32;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class COM_FFM {

public static int CAUUID_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.CAUUID_SIZEOF;
}

private static final class MH_CLSIDFromProgID {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "CLSIDFromProgID", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS));
}
public static int CLSIDFromProgID(char[] arg0, org.eclipse.swt.internal.ole.win32.GUID arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		int rc = (int) MH_CLSIDFromProgID.MH.invokeExact(lparg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_CLSIDFromString {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "CLSIDFromString", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS));
}
public static int CLSIDFromString(char[] arg0, org.eclipse.swt.internal.ole.win32.GUID arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		int rc = (int) MH_CLSIDFromString.MH.invokeExact(lparg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int CONTROLINFO_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.CONTROLINFO_SIZEOF;
}

private static final class MH_CoCreateInstance {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "CoCreateInstance", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS, ADDRESS));
}
public static int CoCreateInstance(org.eclipse.swt.internal.ole.win32.GUID arg0, long arg1, int arg2, org.eclipse.swt.internal.ole.win32.GUID arg3, long[] arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg0, arg0);
		MemorySegment lparg3 = arg3 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg3 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg3, arg3);
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		int rc = (int) MH_CoCreateInstance.MH.invokeExact(lparg0, arg1, arg2, lparg3, lparg4);
		FFM.copyOut(lparg4, arg4);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_CoFreeUnusedLibraries {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "CoFreeUnusedLibraries", FunctionDescriptor.ofVoid());
}
public static void CoFreeUnusedLibraries() {
	try {
		MH_CoFreeUnusedLibraries.MH.invokeExact();
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_CoGetClassObject {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "CoGetClassObject", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS));
}
public static int CoGetClassObject(org.eclipse.swt.internal.ole.win32.GUID arg0, int arg1, long arg2, org.eclipse.swt.internal.ole.win32.GUID arg3, long[] arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg0, arg0);
		MemorySegment lparg3 = arg3 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg3 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg3, arg3);
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		int rc = (int) MH_CoGetClassObject.MH.invokeExact(lparg0, arg1, arg2, lparg3, lparg4);
		FFM.copyOut(lparg4, arg4);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_CoLockObjectExternal {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "CoLockObjectExternal", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static int CoLockObjectExternal(long arg0, boolean arg1, boolean arg2) {
	try {
		int rc = (int) MH_CoLockObjectExternal.MH.invokeExact(arg0, (int) (arg1 ? 1 : 0), (int) (arg2 ? 1 : 0));
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_CreateCoreWebView2EnvironmentWithOptions {
	static final MethodHandle MH = FFM.downcallOptional(FFMLibraries.get("WebView2Loader.dll"), "CreateCoreWebView2EnvironmentWithOptions", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static int CreateCoreWebView2EnvironmentWithOptions(char[] arg0, char[] arg1, long arg2, long arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = 0;
		if (MH_CreateCoreWebView2EnvironmentWithOptions.MH != null) {
			rc = (int) MH_CreateCoreWebView2EnvironmentWithOptions.MH.invokeExact(lparg0, lparg1, arg2, arg3);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_CreateStdAccessibleObject {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleacc.dll"), "CreateStdAccessibleObject", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, ADDRESS, ADDRESS));
}
public static int CreateStdAccessibleObject(long arg0, int arg1, org.eclipse.swt.internal.ole.win32.GUID arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = arg2 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg2 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg2, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		int rc = (int) MH_CreateStdAccessibleObject.MH.invokeExact(arg0, arg1, lparg2, lparg3);
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int DISPPARAMS_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.DISPPARAMS_SIZEOF;
}

private static final class MH_DoDragDrop {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "DoDragDrop", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_INT, ADDRESS));
}
public static int DoDragDrop(long arg0, long arg1, int arg2, int[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		int rc = (int) MH_DoDragDrop.MH.invokeExact(arg0, arg1, arg2, lparg3);
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int ELEMDESC_sizeof() {
	return (int) Extra_FFM.ELEMDESC;
}

public static int EXCEPINFO_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.EXCEPINFO_SIZEOF;
}

public static int FORMATETC_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_SIZEOF;
}

public static int FUNCDESC_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.FUNCDESC_SIZEOF;
}

public static int GUID_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF;
}

private static final class MH_GetClassFile {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "GetClassFile", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS));
}
public static int GetClassFile(char[] arg0, org.eclipse.swt.internal.ole.win32.GUID arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		int rc = (int) MH_GetClassFile.MH.invokeExact(lparg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_IIDFromString {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "IIDFromString", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS));
}
public static int IIDFromString(char[] arg0, org.eclipse.swt.internal.ole.win32.GUID arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		int rc = (int) MH_IIDFromString.MH.invokeExact(lparg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int LICINFO_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.LICINFO_SIZEOF;
}

private static final class MH_LresultFromObject {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleacc.dll"), "LresultFromObject", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static long LresultFromObject(org.eclipse.swt.internal.ole.win32.GUID arg0, long arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg0, arg0);
		long rc = (long) MH_LresultFromObject.MH.invokeExact(lparg0, arg1, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__JLorg_eclipse_swt_internal_ole_win32_FORMATETC_2I {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static void MoveMemory(long arg0, org.eclipse.swt.internal.ole.win32.FORMATETC arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_write(lparg1, arg1);
		MH_MoveMemory__JLorg_eclipse_swt_internal_ole_win32_FORMATETC_2I.MH.invokeExact(arg0, lparg1, (long) arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__JLorg_eclipse_swt_internal_ole_win32_OLEINPLACEFRAMEINFO_2I {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static void MoveMemory(long arg0, org.eclipse.swt.internal.ole.win32.OLEINPLACEFRAMEINFO arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.OLEINPLACEFRAMEINFO_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.OLEINPLACEFRAMEINFO_write(lparg1, arg1);
		MH_MoveMemory__JLorg_eclipse_swt_internal_ole_win32_OLEINPLACEFRAMEINFO_2I.MH.invokeExact(arg0, lparg1, (long) arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__JLorg_eclipse_swt_internal_ole_win32_STGMEDIUM_2I {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static void MoveMemory(long arg0, org.eclipse.swt.internal.ole.win32.STGMEDIUM arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.STGMEDIUM_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.STGMEDIUM_write(lparg1, arg1);
		MH_MoveMemory__JLorg_eclipse_swt_internal_ole_win32_STGMEDIUM_2I.MH.invokeExact(arg0, lparg1, (long) arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_DISPPARAMS_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.DISPPARAMS arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.DISPPARAMS_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_DISPPARAMS_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.DISPPARAMS_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_FORMATETC_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.FORMATETC arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_FORMATETC_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_FUNCDESC_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.FUNCDESC arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.FUNCDESC_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_FUNCDESC_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.FUNCDESC_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_GUID_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.GUID arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_GUID_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_STGMEDIUM_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.STGMEDIUM arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.STGMEDIUM_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_STGMEDIUM_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.STGMEDIUM_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_TYPEATTR_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.TYPEATTR arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.TYPEATTR_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_TYPEATTR_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.TYPEATTR_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_VARDESC_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.VARDESC arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.VARDESC_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_VARDESC_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.VARDESC_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_VARIANT_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.ole.win32.VARIANT arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.VARIANT_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_ole_win32_VARIANT_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.VARIANT_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_MoveMemory__Lorg_eclipse_swt_internal_win32_RECT_2JI {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void MoveMemory(org.eclipse.swt.internal.win32.RECT arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.win32.Structs_FFM.RECT_SIZEOF, 16);
		MH_MoveMemory__Lorg_eclipse_swt_internal_win32_RECT_2JI.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.win32.Structs_FFM.RECT_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int OLECMD_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.OLECMD_SIZEOF;
}

public static int OLEINPLACEFRAMEINFO_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.OLEINPLACEFRAMEINFO_SIZEOF;
}

private static final class MH_OleCreate {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleCreate", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static int OleCreate(org.eclipse.swt.internal.ole.win32.GUID arg0, org.eclipse.swt.internal.ole.win32.GUID arg1, int arg2, org.eclipse.swt.internal.ole.win32.FORMATETC arg3, long arg4, long arg5, long[] arg6) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg0, arg0);
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg1, arg1);
		MemorySegment lparg3 = arg3 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_SIZEOF, 16);
		if (arg3 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_write(lparg3, arg3);
		MemorySegment lparg6 = FFM.copyIn(arena, arg6);
		int rc = (int) MH_OleCreate.MH.invokeExact(lparg0, lparg1, arg2, lparg3, arg4, arg5, lparg6);
		FFM.copyOut(lparg6, arg6);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleCreateFromFile {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleCreateFromFile", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS, JAVA_INT, ADDRESS, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static int OleCreateFromFile(org.eclipse.swt.internal.ole.win32.GUID arg0, char[] arg1, org.eclipse.swt.internal.ole.win32.GUID arg2, int arg3, org.eclipse.swt.internal.ole.win32.FORMATETC arg4, long arg5, long arg6, long[] arg7) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg0, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = arg2 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg2 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg2, arg2);
		MemorySegment lparg4 = arg4 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_SIZEOF, 16);
		if (arg4 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.FORMATETC_write(lparg4, arg4);
		MemorySegment lparg7 = FFM.copyIn(arena, arg7);
		int rc = (int) MH_OleCreateFromFile.MH.invokeExact(lparg0, lparg1, lparg2, arg3, lparg4, arg5, arg6, lparg7);
		FFM.copyOut(lparg7, arg7);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleCreatePropertyFrame {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "OleCreatePropertyFrame", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_LONG));
}
public static int OleCreatePropertyFrame(long arg0, int arg1, int arg2, char[] arg3, int arg4, long[] arg5, int arg6, long arg7, int arg8, int arg9, long arg10) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		MemorySegment lparg5 = FFM.copyIn(arena, arg5);
		int rc = (int) MH_OleCreatePropertyFrame.MH.invokeExact(arg0, arg1, arg2, lparg3, arg4, lparg5, arg6, arg7, arg8, arg9, arg10);
		FFM.copyOut(lparg5, arg5);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleDraw {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleDraw", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static int OleDraw(long arg0, int arg1, long arg2, long arg3) {
	try {
		int rc = (int) MH_OleDraw.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleFlushClipboard {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleFlushClipboard", FunctionDescriptor.of(JAVA_INT));
}
public static int OleFlushClipboard() {
	try {
		int rc = (int) MH_OleFlushClipboard.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleGetClipboard {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleGetClipboard", FunctionDescriptor.of(JAVA_INT, ADDRESS));
}
public static int OleGetClipboard(long[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		int rc = (int) MH_OleGetClipboard.MH.invokeExact(lparg0);
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleIsCurrentClipboard {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleIsCurrentClipboard", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int OleIsCurrentClipboard(long arg0) {
	try {
		int rc = (int) MH_OleIsCurrentClipboard.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleIsRunning {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleIsRunning", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static boolean OleIsRunning(long arg0) {
	try {
		int rc = (int) MH_OleIsRunning.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleRun {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleRun", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int OleRun(long arg0) {
	try {
		int rc = (int) MH_OleRun.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleSave {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleSave", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_INT));
}
public static int OleSave(long arg0, long arg1, boolean arg2) {
	try {
		int rc = (int) MH_OleSave.MH.invokeExact(arg0, arg1, (int) (arg2 ? 1 : 0));
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleSetClipboard {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleSetClipboard", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int OleSetClipboard(long arg0) {
	try {
		int rc = (int) MH_OleSetClipboard.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleSetContainedObject {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleSetContainedObject", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT));
}
public static int OleSetContainedObject(long arg0, boolean arg1) {
	try {
		int rc = (int) MH_OleSetContainedObject.MH.invokeExact(arg0, (int) (arg1 ? 1 : 0));
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleSetMenuDescriptor {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "OleSetMenuDescriptor", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static int OleSetMenuDescriptor(long arg0, long arg1, long arg2, long arg3, long arg4) {
	try {
		int rc = (int) MH_OleSetMenuDescriptor.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_OleTranslateColor {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "OleTranslateColor", FunctionDescriptor.of(JAVA_INT, JAVA_INT, JAVA_LONG, ADDRESS));
}
public static int OleTranslateColor(int arg0, long arg1, int[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		int rc = (int) MH_OleTranslateColor.MH.invokeExact(arg0, arg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_ProgIDFromCLSID {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "ProgIDFromCLSID", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS));
}
public static int ProgIDFromCLSID(org.eclipse.swt.internal.ole.win32.GUID arg0, long[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg0, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_ProgIDFromCLSID.MH.invokeExact(lparg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_RegisterDragDrop {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "RegisterDragDrop", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static int RegisterDragDrop(long arg0, long arg1) {
	try {
		int rc = (int) MH_RegisterDragDrop.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_ReleaseStgMedium {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "ReleaseStgMedium", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void ReleaseStgMedium(long arg0) {
	try {
		MH_ReleaseStgMedium.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_RevokeDragDrop {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "RevokeDragDrop", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int RevokeDragDrop(long arg0) {
	try {
		int rc = (int) MH_RevokeDragDrop.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SHCreateItemFromParsingName {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("shell32.dll"), "SHCreateItemFromParsingName", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG, ADDRESS, ADDRESS));
}
public static int SHCreateItemFromParsingName(char[] arg0, long arg1, org.eclipse.swt.internal.ole.win32.GUID arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg2 = arg2 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg2 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg2, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		int rc = (int) MH_SHCreateItemFromParsingName.MH.invokeExact(lparg0, arg1, lparg2, lparg3);
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SHCreateMemStream {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("shlwapi.dll"), "SHCreateMemStream", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_INT), Linker.Option.critical(true));
}
public static long SHCreateMemStream(byte[] arg0, int arg1) {
	try {
		long rc = (long) MH_SHCreateMemStream.MH.invokeExact(FFM.heap(arg0), arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int STGMEDIUM_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.STGMEDIUM_SIZEOF;
}

private static final class MH_StgCreateDocfile {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "StgCreateDocfile", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS));
}
public static int StgCreateDocfile(char[] arg0, int arg1, int arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		int rc = (int) MH_StgCreateDocfile.MH.invokeExact(lparg0, arg1, arg2, lparg3);
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_StgIsStorageFile {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "StgIsStorageFile", FunctionDescriptor.of(JAVA_INT, ADDRESS));
}
public static int StgIsStorageFile(char[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		int rc = (int) MH_StgIsStorageFile.MH.invokeExact(lparg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_StgOpenStorage {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "StgOpenStorage", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG, JAVA_INT, JAVA_LONG, JAVA_INT, ADDRESS));
}
public static int StgOpenStorage(char[] arg0, long arg1, int arg2, long arg3, int arg4, long[] arg5) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg5 = FFM.copyIn(arena, arg5);
		int rc = (int) MH_StgOpenStorage.MH.invokeExact(lparg0, arg1, arg2, arg3, arg4, lparg5);
		FFM.copyOut(lparg5, arg5);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SysAllocString {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "SysAllocString", FunctionDescriptor.of(JAVA_LONG, ADDRESS), Linker.Option.critical(true));
}
public static long SysAllocString(char[] arg0) {
	try {
		long rc = (long) MH_SysAllocString.MH.invokeExact(FFM.heap(arg0));
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SysAllocStringLen {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "SysAllocStringLen", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_INT));
}
public static long SysAllocStringLen(char[] arg0, int arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = (long) MH_SysAllocStringLen.MH.invokeExact(lparg0, arg1);
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SysFreeString {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "SysFreeString", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void SysFreeString(long arg0) {
	try {
		MH_SysFreeString.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SysStringByteLen {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "SysStringByteLen", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int SysStringByteLen(long arg0) {
	try {
		int rc = (int) MH_SysStringByteLen.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_SysStringLen {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "SysStringLen", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int SysStringLen(long arg0) {
	try {
		int rc = (int) MH_SysStringLen.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

public static int TYPEATTR_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.TYPEATTR_SIZEOF;
}

public static int TYPEDESC_sizeof() {
	return (int) Extra_FFM.TYPEDESC;
}

public static int VARDESC_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.VARDESC_SIZEOF;
}

public static int VARIANT_sizeof() {
	return (int) org.eclipse.swt.internal.ole.win32.Structs_FFM.VARIANT_SIZEOF;
}

private static final class MH_VariantChangeType {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "VariantChangeType", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_SHORT, JAVA_SHORT));
}
public static int VariantChangeType(long arg0, long arg1, short arg2, short arg3) {
	try {
		int rc = (int) MH_VariantChangeType.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_VariantClear {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "VariantClear", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int VariantClear(long arg0) {
	try {
		int rc = (int) MH_VariantClear.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_VariantInit {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("oleaut32.dll"), "VariantInit", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void VariantInit(long arg0) {
	try {
		MH_VariantInit.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_WriteClassStg {
	static final MethodHandle MH = FFM.downcall(FFMLibraries.get("ole32.dll"), "WriteClassStg", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static int WriteClassStg(long arg0, org.eclipse.swt.internal.ole.win32.GUID arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_write(lparg1, arg1);
		int rc = (int) MH_WriteClassStg.MH.invokeExact(arg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.ole.win32.Structs_FFM.GUID_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
