package org.eclipse.swt.internal.ole.win32;

/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */

/** Sizes and field offsets of C types that have no Java struct class. */
public final class Extra_FFM {

	public static final long ELEMDESC = 32L;
	public static final long TYPEDESC = 16L;
}
