/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.ole.win32;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long CAUUID_SIZEOF = 16L;
public static final long CAUUID_CELEMS_OFFSET = 0L;
public static final long CAUUID_PELEMS_OFFSET = 8L;

public static void CAUUID_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.CAUUID o) {
	o.cElems = s.get(JAVA_INT_UNALIGNED, 0L);
	o.pElems = s.get(JAVA_LONG_UNALIGNED, 8L);
}

public static void CAUUID_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.CAUUID o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.cElems);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.pElems);
}

public static final long CONTROLINFO_SIZEOF = 24L;
public static final long CONTROLINFO_CB_OFFSET = 0L;
public static final long CONTROLINFO_HACCEL_OFFSET = 8L;
public static final long CONTROLINFO_CACCEL_OFFSET = 16L;
public static final long CONTROLINFO_DWFLAGS_OFFSET = 20L;

public static void CONTROLINFO_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.CONTROLINFO o) {
	o.cb = s.get(JAVA_INT_UNALIGNED, 0L);
	o.hAccel = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.cAccel = s.get(JAVA_SHORT_UNALIGNED, 16L);
	o.dwFlags = s.get(JAVA_INT_UNALIGNED, 20L);
}

public static void CONTROLINFO_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.CONTROLINFO o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.cb);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.hAccel);
	s.set(JAVA_SHORT_UNALIGNED, 16L, o.cAccel);
	s.set(JAVA_INT_UNALIGNED, 20L, o.dwFlags);
}

public static final long DISPPARAMS_SIZEOF = 24L;
public static final long DISPPARAMS_RGVARG_OFFSET = 0L;
public static final long DISPPARAMS_RGDISPIDNAMEDARGS_OFFSET = 8L;
public static final long DISPPARAMS_CARGS_OFFSET = 16L;
public static final long DISPPARAMS_CNAMEDARGS_OFFSET = 20L;

public static void DISPPARAMS_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.DISPPARAMS o) {
	o.rgvarg = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.rgdispidNamedArgs = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.cArgs = s.get(JAVA_INT_UNALIGNED, 16L);
	o.cNamedArgs = s.get(JAVA_INT_UNALIGNED, 20L);
}

public static void DISPPARAMS_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.DISPPARAMS o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.rgvarg);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.rgdispidNamedArgs);
	s.set(JAVA_INT_UNALIGNED, 16L, o.cArgs);
	s.set(JAVA_INT_UNALIGNED, 20L, o.cNamedArgs);
}

public static final long EXCEPINFO_SIZEOF = 64L;
public static final long EXCEPINFO_WCODE_OFFSET = 0L;
public static final long EXCEPINFO_WRESERVED_OFFSET = 2L;
public static final long EXCEPINFO_BSTRSOURCE_OFFSET = 8L;
public static final long EXCEPINFO_BSTRDESCRIPTION_OFFSET = 16L;
public static final long EXCEPINFO_BSTRHELPFILE_OFFSET = 24L;
public static final long EXCEPINFO_DWHELPCONTEXT_OFFSET = 32L;
public static final long EXCEPINFO_PVRESERVED_OFFSET = 40L;
public static final long EXCEPINFO_PFNDEFERREDFILLIN_OFFSET = 48L;
public static final long EXCEPINFO_SCODE_OFFSET = 56L;

public static void EXCEPINFO_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.EXCEPINFO o) {
	o.wCode = s.get(JAVA_SHORT_UNALIGNED, 0L);
	o.wReserved = s.get(JAVA_SHORT_UNALIGNED, 2L);
	o.bstrSource = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.bstrDescription = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.bstrHelpFile = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.dwHelpContext = s.get(JAVA_INT_UNALIGNED, 32L);
	o.pvReserved = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.pfnDeferredFillIn = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.scode = s.get(JAVA_INT_UNALIGNED, 56L);
}

public static void EXCEPINFO_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.EXCEPINFO o) {
	s.set(JAVA_SHORT_UNALIGNED, 0L, o.wCode);
	s.set(JAVA_SHORT_UNALIGNED, 2L, o.wReserved);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.bstrSource);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.bstrDescription);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.bstrHelpFile);
	s.set(JAVA_INT_UNALIGNED, 32L, o.dwHelpContext);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.pvReserved);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.pfnDeferredFillIn);
	s.set(JAVA_INT_UNALIGNED, 56L, o.scode);
}

public static final long FORMATETC_SIZEOF = 32L;
public static final long FORMATETC_CFFORMAT_OFFSET = 0L;
public static final long FORMATETC_PTD_OFFSET = 8L;
public static final long FORMATETC_DWASPECT_OFFSET = 16L;
public static final long FORMATETC_LINDEX_OFFSET = 20L;
public static final long FORMATETC_TYMED_OFFSET = 24L;

public static void FORMATETC_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.FORMATETC o) {
	o.cfFormat = Short.toUnsignedInt(s.get(JAVA_SHORT_UNALIGNED, 0L));
	o.ptd = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.dwAspect = s.get(JAVA_INT_UNALIGNED, 16L);
	o.lindex = s.get(JAVA_INT_UNALIGNED, 20L);
	o.tymed = s.get(JAVA_INT_UNALIGNED, 24L);
}

public static void FORMATETC_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.FORMATETC o) {
	s.set(JAVA_SHORT_UNALIGNED, 0L, (short) o.cfFormat);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.ptd);
	s.set(JAVA_INT_UNALIGNED, 16L, o.dwAspect);
	s.set(JAVA_INT_UNALIGNED, 20L, o.lindex);
	s.set(JAVA_INT_UNALIGNED, 24L, o.tymed);
}

public static final long FUNCDESC_SIZEOF = 88L;
public static final long FUNCDESC_MEMID_OFFSET = 0L;
public static final long FUNCDESC_LPRGSCODE_OFFSET = 8L;
public static final long FUNCDESC_LPRGELEMDESCPARAM_OFFSET = 16L;
public static final long FUNCDESC_FUNCKIND_OFFSET = 24L;
public static final long FUNCDESC_INVKIND_OFFSET = 28L;
public static final long FUNCDESC_CALLCONV_OFFSET = 32L;
public static final long FUNCDESC_CPARAMS_OFFSET = 36L;
public static final long FUNCDESC_CPARAMSOPT_OFFSET = 38L;
public static final long FUNCDESC_OVFT_OFFSET = 40L;
public static final long FUNCDESC_CSCODES_OFFSET = 42L;
public static final long FUNCDESC_ELEMDESCFUNC_TDESC_UNION_OFFSET = 48L;
public static final long FUNCDESC_ELEMDESCFUNC_TDESC_VT_OFFSET = 56L;
public static final long FUNCDESC_ELEMDESCFUNC_PARAMDESC_PPARAMDESCEX_OFFSET = 64L;
public static final long FUNCDESC_ELEMDESCFUNC_PARAMDESC_WPARAMFLAGS_OFFSET = 72L;
public static final long FUNCDESC_WFUNCFLAGS_OFFSET = 80L;

public static void FUNCDESC_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.FUNCDESC o) {
	o.memid = s.get(JAVA_INT_UNALIGNED, 0L);
	o.lprgscode = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.lprgelemdescParam = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.funckind = s.get(JAVA_INT_UNALIGNED, 24L);
	o.invkind = s.get(JAVA_INT_UNALIGNED, 28L);
	o.callconv = s.get(JAVA_INT_UNALIGNED, 32L);
	o.cParams = s.get(JAVA_SHORT_UNALIGNED, 36L);
	o.cParamsOpt = s.get(JAVA_SHORT_UNALIGNED, 38L);
	o.oVft = s.get(JAVA_SHORT_UNALIGNED, 40L);
	o.cScodes = s.get(JAVA_SHORT_UNALIGNED, 42L);
	o.elemdescFunc_tdesc_union = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.elemdescFunc_tdesc_vt = s.get(JAVA_SHORT_UNALIGNED, 56L);
	o.elemdescFunc_paramdesc_pparamdescex = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.elemdescFunc_paramdesc_wParamFlags = s.get(JAVA_SHORT_UNALIGNED, 72L);
	o.wFuncFlags = s.get(JAVA_SHORT_UNALIGNED, 80L);
}

public static void FUNCDESC_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.FUNCDESC o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.memid);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.lprgscode);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.lprgelemdescParam);
	s.set(JAVA_INT_UNALIGNED, 24L, o.funckind);
	s.set(JAVA_INT_UNALIGNED, 28L, o.invkind);
	s.set(JAVA_INT_UNALIGNED, 32L, o.callconv);
	s.set(JAVA_SHORT_UNALIGNED, 36L, o.cParams);
	s.set(JAVA_SHORT_UNALIGNED, 38L, o.cParamsOpt);
	s.set(JAVA_SHORT_UNALIGNED, 40L, o.oVft);
	s.set(JAVA_SHORT_UNALIGNED, 42L, o.cScodes);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.elemdescFunc_tdesc_union);
	s.set(JAVA_SHORT_UNALIGNED, 56L, o.elemdescFunc_tdesc_vt);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.elemdescFunc_paramdesc_pparamdescex);
	s.set(JAVA_SHORT_UNALIGNED, 72L, o.elemdescFunc_paramdesc_wParamFlags);
	s.set(JAVA_SHORT_UNALIGNED, 80L, o.wFuncFlags);
}

public static final long GUID_SIZEOF = 16L;
public static final long GUID_DATA1_OFFSET = 0L;
public static final long GUID_DATA2_OFFSET = 4L;
public static final long GUID_DATA3_OFFSET = 6L;
public static final long GUID_DATA4_OFFSET = 8L;

public static void GUID_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.GUID o) {
	o.Data1 = s.get(JAVA_INT_UNALIGNED, 0L);
	o.Data2 = s.get(JAVA_SHORT_UNALIGNED, 4L);
	o.Data3 = s.get(JAVA_SHORT_UNALIGNED, 6L);
	MemorySegment.copy(s, JAVA_BYTE, 8L, o.Data4, 0, 8);
}

public static void GUID_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.GUID o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.Data1);
	s.set(JAVA_SHORT_UNALIGNED, 4L, o.Data2);
	s.set(JAVA_SHORT_UNALIGNED, 6L, o.Data3);
	MemorySegment.copy(o.Data4, 0, s, JAVA_BYTE, 8L, 8);
}

public static final long LICINFO_SIZEOF = 12L;
public static final long LICINFO_CBLICINFO_OFFSET = 0L;
public static final long LICINFO_FRUNTIMEKEYAVAIL_OFFSET = 4L;
public static final long LICINFO_FLICVERIFIED_OFFSET = 8L;

public static void LICINFO_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.LICINFO o) {
	o.cbLicInfo = s.get(JAVA_INT_UNALIGNED, 0L);
	o.fRuntimeKeyAvail = (s.get(JAVA_INT_UNALIGNED, 4L) & 1) != 0;
	o.fLicVerified = (s.get(JAVA_INT_UNALIGNED, 8L) & 1) != 0;
}

public static void LICINFO_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.LICINFO o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.cbLicInfo);
	s.set(JAVA_INT_UNALIGNED, 4L, (int) (o.fRuntimeKeyAvail ? 1 : 0));
	s.set(JAVA_INT_UNALIGNED, 8L, (int) (o.fLicVerified ? 1 : 0));
}

public static final long OLECMD_SIZEOF = 8L;
public static final long OLECMD_CMDID_OFFSET = 0L;
public static final long OLECMD_CMDF_OFFSET = 4L;

public static void OLECMD_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.OLECMD o) {
	o.cmdID = s.get(JAVA_INT_UNALIGNED, 0L);
	o.cmdf = s.get(JAVA_INT_UNALIGNED, 4L);
}

public static void OLECMD_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.OLECMD o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.cmdID);
	s.set(JAVA_INT_UNALIGNED, 4L, o.cmdf);
}

public static final long OLEINPLACEFRAMEINFO_SIZEOF = 32L;
public static final long OLEINPLACEFRAMEINFO_CB_OFFSET = 0L;
public static final long OLEINPLACEFRAMEINFO_FMDIAPP_OFFSET = 4L;
public static final long OLEINPLACEFRAMEINFO_HWNDFRAME_OFFSET = 8L;
public static final long OLEINPLACEFRAMEINFO_HACCEL_OFFSET = 16L;
public static final long OLEINPLACEFRAMEINFO_CACCELENTRIES_OFFSET = 24L;

public static void OLEINPLACEFRAMEINFO_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.OLEINPLACEFRAMEINFO o) {
	o.cb = s.get(JAVA_INT_UNALIGNED, 0L);
	o.fMDIApp = s.get(JAVA_INT_UNALIGNED, 4L);
	o.hwndFrame = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.haccel = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.cAccelEntries = s.get(JAVA_INT_UNALIGNED, 24L);
}

public static void OLEINPLACEFRAMEINFO_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.OLEINPLACEFRAMEINFO o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.cb);
	s.set(JAVA_INT_UNALIGNED, 4L, o.fMDIApp);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.hwndFrame);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.haccel);
	s.set(JAVA_INT_UNALIGNED, 24L, o.cAccelEntries);
}

public static final long STGMEDIUM_SIZEOF = 24L;
public static final long STGMEDIUM_TYMED_OFFSET = 0L;
public static final long STGMEDIUM_UNIONFIELD_OFFSET = 8L;
public static final long STGMEDIUM_PUNKFORRELEASE_OFFSET = 16L;

public static void STGMEDIUM_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.STGMEDIUM o) {
	o.tymed = s.get(JAVA_INT_UNALIGNED, 0L);
	o.unionField = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.pUnkForRelease = s.get(JAVA_LONG_UNALIGNED, 16L);
}

public static void STGMEDIUM_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.STGMEDIUM o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.tymed);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.unionField);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.pUnkForRelease);
}

public static final long TYPEATTR_SIZEOF = 96L;
public static final long TYPEATTR_GUID_DATA1_OFFSET = 0L;
public static final long TYPEATTR_GUID_DATA2_OFFSET = 4L;
public static final long TYPEATTR_GUID_DATA3_OFFSET = 6L;
public static final long TYPEATTR_GUID_DATA4_OFFSET = 8L;
public static final long TYPEATTR_LCID_OFFSET = 16L;
public static final long TYPEATTR_DWRESERVED_OFFSET = 20L;
public static final long TYPEATTR_MEMIDCONSTRUCTOR_OFFSET = 24L;
public static final long TYPEATTR_MEMIDDESTRUCTOR_OFFSET = 28L;
public static final long TYPEATTR_LPSTRSCHEMA_OFFSET = 32L;
public static final long TYPEATTR_CBSIZEINSTANCE_OFFSET = 40L;
public static final long TYPEATTR_TYPEKIND_OFFSET = 44L;
public static final long TYPEATTR_CFUNCS_OFFSET = 48L;
public static final long TYPEATTR_CVARS_OFFSET = 50L;
public static final long TYPEATTR_CIMPLTYPES_OFFSET = 52L;
public static final long TYPEATTR_CBSIZEVFT_OFFSET = 54L;
public static final long TYPEATTR_CBALIGNMENT_OFFSET = 56L;
public static final long TYPEATTR_WTYPEFLAGS_OFFSET = 58L;
public static final long TYPEATTR_WMAJORVERNUM_OFFSET = 60L;
public static final long TYPEATTR_WMINORVERNUM_OFFSET = 62L;
public static final long TYPEATTR_TDESCALIAS_UNIONFIELD_OFFSET = 64L;
public static final long TYPEATTR_TDESCALIAS_VT_OFFSET = 72L;
public static final long TYPEATTR_IDLDESCTYPE_DWRESERVED_OFFSET = 80L;
public static final long TYPEATTR_IDLDESCTYPE_WIDLFLAGS_OFFSET = 88L;

public static void TYPEATTR_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.TYPEATTR o) {
	o.guid_Data1 = s.get(JAVA_INT_UNALIGNED, 0L);
	o.guid_Data2 = s.get(JAVA_SHORT_UNALIGNED, 4L);
	o.guid_Data3 = s.get(JAVA_SHORT_UNALIGNED, 6L);
	MemorySegment.copy(s, JAVA_BYTE, 8L, o.guid_Data4, 0, 8);
	o.lcid = s.get(JAVA_INT_UNALIGNED, 16L);
	o.dwReserved = s.get(JAVA_INT_UNALIGNED, 20L);
	o.memidConstructor = s.get(JAVA_INT_UNALIGNED, 24L);
	o.memidDestructor = s.get(JAVA_INT_UNALIGNED, 28L);
	o.lpstrSchema = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.cbSizeInstance = s.get(JAVA_INT_UNALIGNED, 40L);
	o.typekind = s.get(JAVA_INT_UNALIGNED, 44L);
	o.cFuncs = s.get(JAVA_SHORT_UNALIGNED, 48L);
	o.cVars = s.get(JAVA_SHORT_UNALIGNED, 50L);
	o.cImplTypes = s.get(JAVA_SHORT_UNALIGNED, 52L);
	o.cbSizeVft = s.get(JAVA_SHORT_UNALIGNED, 54L);
	o.cbAlignment = s.get(JAVA_SHORT_UNALIGNED, 56L);
	o.wTypeFlags = s.get(JAVA_SHORT_UNALIGNED, 58L);
	o.wMajorVerNum = s.get(JAVA_SHORT_UNALIGNED, 60L);
	o.wMinorVerNum = s.get(JAVA_SHORT_UNALIGNED, 62L);
	o.tdescAlias_unionField = s.get(JAVA_LONG_UNALIGNED, 64L);
	o.tdescAlias_vt = s.get(JAVA_SHORT_UNALIGNED, 72L);
	o.idldescType_dwReserved = (int) s.get(JAVA_LONG_UNALIGNED, 80L);
	o.idldescType_wIDLFlags = s.get(JAVA_SHORT_UNALIGNED, 88L);
}

public static void TYPEATTR_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.TYPEATTR o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.guid_Data1);
	s.set(JAVA_SHORT_UNALIGNED, 4L, o.guid_Data2);
	s.set(JAVA_SHORT_UNALIGNED, 6L, o.guid_Data3);
	MemorySegment.copy(o.guid_Data4, 0, s, JAVA_BYTE, 8L, 8);
	s.set(JAVA_INT_UNALIGNED, 16L, o.lcid);
	s.set(JAVA_INT_UNALIGNED, 20L, o.dwReserved);
	s.set(JAVA_INT_UNALIGNED, 24L, o.memidConstructor);
	s.set(JAVA_INT_UNALIGNED, 28L, o.memidDestructor);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.lpstrSchema);
	s.set(JAVA_INT_UNALIGNED, 40L, o.cbSizeInstance);
	s.set(JAVA_INT_UNALIGNED, 44L, o.typekind);
	s.set(JAVA_SHORT_UNALIGNED, 48L, o.cFuncs);
	s.set(JAVA_SHORT_UNALIGNED, 50L, o.cVars);
	s.set(JAVA_SHORT_UNALIGNED, 52L, o.cImplTypes);
	s.set(JAVA_SHORT_UNALIGNED, 54L, o.cbSizeVft);
	s.set(JAVA_SHORT_UNALIGNED, 56L, o.cbAlignment);
	s.set(JAVA_SHORT_UNALIGNED, 58L, o.wTypeFlags);
	s.set(JAVA_SHORT_UNALIGNED, 60L, o.wMajorVerNum);
	s.set(JAVA_SHORT_UNALIGNED, 62L, o.wMinorVerNum);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.tdescAlias_unionField);
	s.set(JAVA_SHORT_UNALIGNED, 72L, o.tdescAlias_vt);
	s.set(JAVA_LONG_UNALIGNED, 80L, (long) o.idldescType_dwReserved);
	s.set(JAVA_SHORT_UNALIGNED, 88L, o.idldescType_wIDLFlags);
}

public static final long VARDESC_SIZEOF = 64L;
public static final long VARDESC_MEMID_OFFSET = 0L;
public static final long VARDESC_LPSTRSCHEMA_OFFSET = 8L;
public static final long VARDESC_OINST_OFFSET = 16L;
public static final long VARDESC_ELEMDESCVAR_TDESC_UNION_OFFSET = 24L;
public static final long VARDESC_ELEMDESCVAR_TDESC_VT_OFFSET = 32L;
public static final long VARDESC_ELEMDESCVAR_PARAMDESC_PPARAMDESCEX_OFFSET = 40L;
public static final long VARDESC_ELEMDESCVAR_PARAMDESC_WPARAMFLAGS_OFFSET = 48L;
public static final long VARDESC_WVARFLAGS_OFFSET = 56L;
public static final long VARDESC_VARKIND_OFFSET = 60L;

public static void VARDESC_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.VARDESC o) {
	o.memid = s.get(JAVA_INT_UNALIGNED, 0L);
	o.lpstrSchema = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.oInst = s.get(JAVA_INT_UNALIGNED, 16L);
	o.elemdescVar_tdesc_union = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.elemdescVar_tdesc_vt = s.get(JAVA_SHORT_UNALIGNED, 32L);
	o.elemdescVar_paramdesc_pparamdescex = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.elemdescVar_paramdesc_wParamFlags = s.get(JAVA_SHORT_UNALIGNED, 48L);
	o.wVarFlags = s.get(JAVA_SHORT_UNALIGNED, 56L);
	o.varkind = s.get(JAVA_INT_UNALIGNED, 60L);
}

public static void VARDESC_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.VARDESC o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.memid);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.lpstrSchema);
	s.set(JAVA_INT_UNALIGNED, 16L, o.oInst);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.elemdescVar_tdesc_union);
	s.set(JAVA_SHORT_UNALIGNED, 32L, o.elemdescVar_tdesc_vt);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.elemdescVar_paramdesc_pparamdescex);
	s.set(JAVA_SHORT_UNALIGNED, 48L, o.elemdescVar_paramdesc_wParamFlags);
	s.set(JAVA_SHORT_UNALIGNED, 56L, o.wVarFlags);
	s.set(JAVA_INT_UNALIGNED, 60L, o.varkind);
}

public static final long VARIANT_SIZEOF = 24L;
public static final long VARIANT_VT_OFFSET = 0L;
public static final long VARIANT_WRESERVED1_OFFSET = 2L;
public static final long VARIANT_WRESERVED2_OFFSET = 4L;
public static final long VARIANT_WRESERVED3_OFFSET = 6L;
public static final long VARIANT_LVAL_OFFSET = 8L;

public static void VARIANT_read(MemorySegment s, org.eclipse.swt.internal.ole.win32.VARIANT o) {
	o.vt = s.get(JAVA_SHORT_UNALIGNED, 0L);
	o.wReserved1 = s.get(JAVA_SHORT_UNALIGNED, 2L);
	o.wReserved2 = s.get(JAVA_SHORT_UNALIGNED, 4L);
	o.wReserved3 = s.get(JAVA_SHORT_UNALIGNED, 6L);
	o.lVal = s.get(JAVA_INT_UNALIGNED, 8L);
}

public static void VARIANT_write(MemorySegment s, org.eclipse.swt.internal.ole.win32.VARIANT o) {
	s.set(JAVA_SHORT_UNALIGNED, 0L, o.vt);
	s.set(JAVA_SHORT_UNALIGNED, 2L, o.wReserved1);
	s.set(JAVA_SHORT_UNALIGNED, 4L, o.wReserved2);
	s.set(JAVA_SHORT_UNALIGNED, 6L, o.wReserved3);
	s.set(JAVA_INT_UNALIGNED, 8L, o.lVal);
}

}
