/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.opengl.glx;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class GLX_FFM {

private static final SymbolLookup LOOKUP = FFM.library("libGL.so.1");

public static int XVisualInfo_sizeof() {
	return (int) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_SIZEOF;
}

private static final class MH_glGetIntegerv {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glGetIntegerv", FunctionDescriptor.ofVoid(JAVA_INT, ADDRESS));
}
public static void glGetIntegerv(int arg0, int[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_glGetIntegerv.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glViewport {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glViewport", FunctionDescriptor.ofVoid(JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static void glViewport(int arg0, int arg1, int arg2, int arg3) {
	try {
		MH_glViewport.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXChooseVisual {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXChooseVisual", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, ADDRESS));
}
public static long glXChooseVisual(long arg0, int arg1, int[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = (long) MH_glXChooseVisual.MH.invokeExact(arg0, arg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXCreateContext {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXCreateContext", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_INT));
}
public static long glXCreateContext(long arg0, org.eclipse.swt.internal.opengl.glx.XVisualInfo arg1, long arg2, boolean arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_write(lparg1, arg1);
		long rc = (long) MH_glXCreateContext.MH.invokeExact(arg0, lparg1, arg2, (int) (arg3 ? 1 : 0));
		if (arg1 != null) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXDestroyContext {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXDestroyContext", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void glXDestroyContext(long arg0, long arg1) {
	try {
		MH_glXDestroyContext.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXGetConfig {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXGetConfig", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
}
public static int glXGetConfig(long arg0, org.eclipse.swt.internal.opengl.glx.XVisualInfo arg1, int arg2, int[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_write(lparg1, arg1);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		int rc = (int) MH_glXGetConfig.MH.invokeExact(arg0, lparg1, arg2, lparg3);
		FFM.copyOut(lparg3, arg3);
		if (arg1 != null) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_read(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXGetCurrentContext {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXGetCurrentContext", FunctionDescriptor.of(JAVA_LONG));
}
public static long glXGetCurrentContext() {
	try {
		long rc = (long) MH_glXGetCurrentContext.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXMakeCurrent {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXMakeCurrent", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static boolean glXMakeCurrent(long arg0, long arg1, long arg2) {
	try {
		int rc = (int) MH_glXMakeCurrent.MH.invokeExact(arg0, arg1, arg2);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_glXSwapBuffers {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "glXSwapBuffers", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void glXSwapBuffers(long arg0, long arg1) {
	try {
		MH_glXSwapBuffers.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove {
	static final MethodHandle MH = FFM.downcall(LOOKUP, "memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG));
}
public static void memmove(org.eclipse.swt.internal.opengl.glx.XVisualInfo arg0, long arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_write(lparg0, arg0);
		MH_memmove.MH.invokeExact(lparg0, arg1, (long) arg2);
		if (arg0 != null) org.eclipse.swt.internal.opengl.glx.Structs_FFM.XVisualInfo_read(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
