/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.opengl.glx;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long XVisualInfo_SIZEOF = 64L;
public static final long XVisualInfo_VISUAL_OFFSET = 0L;
public static final long XVisualInfo_VISUALID_OFFSET = 8L;
public static final long XVisualInfo_SCREEN_OFFSET = 16L;
public static final long XVisualInfo_DEPTH_OFFSET = 20L;
public static final long XVisualInfo_CCLASS_OFFSET = 24L;
public static final long XVisualInfo_RED_MASK_OFFSET = 32L;
public static final long XVisualInfo_GREEN_MASK_OFFSET = 40L;
public static final long XVisualInfo_BLUE_MASK_OFFSET = 48L;
public static final long XVisualInfo_COLORMAP_SIZE_OFFSET = 56L;
public static final long XVisualInfo_BITS_PER_RGB_OFFSET = 60L;

public static void XVisualInfo_read(MemorySegment s, org.eclipse.swt.internal.opengl.glx.XVisualInfo o) {
	o.visual = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.visualid = (int) s.get(JAVA_LONG_UNALIGNED, 8L);
	o.screen = s.get(JAVA_INT_UNALIGNED, 16L);
	o.depth = s.get(JAVA_INT_UNALIGNED, 20L);
	o.cclass = s.get(JAVA_INT_UNALIGNED, 24L);
	o.red_mask = (int) s.get(JAVA_LONG_UNALIGNED, 32L);
	o.green_mask = (int) s.get(JAVA_LONG_UNALIGNED, 40L);
	o.blue_mask = (int) s.get(JAVA_LONG_UNALIGNED, 48L);
	o.colormap_size = s.get(JAVA_INT_UNALIGNED, 56L);
	o.bits_per_rgb = s.get(JAVA_INT_UNALIGNED, 60L);
}

public static void XVisualInfo_write(MemorySegment s, org.eclipse.swt.internal.opengl.glx.XVisualInfo o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.visual);
	s.set(JAVA_LONG_UNALIGNED, 8L, (long) o.visualid);
	s.set(JAVA_INT_UNALIGNED, 16L, o.screen);
	s.set(JAVA_INT_UNALIGNED, 20L, o.depth);
	s.set(JAVA_INT_UNALIGNED, 24L, o.cclass);
	s.set(JAVA_LONG_UNALIGNED, 32L, (long) o.red_mask);
	s.set(JAVA_LONG_UNALIGNED, 40L, (long) o.green_mask);
	s.set(JAVA_LONG_UNALIGNED, 48L, (long) o.blue_mask);
	s.set(JAVA_INT_UNALIGNED, 56L, o.colormap_size);
	s.set(JAVA_INT_UNALIGNED, 60L, o.bits_per_rgb);
}

}
