/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class C_FFM {

private static final class MH_free {
	static final MethodHandle MH = FFM.downcall("free", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void free(long arg0) {
	try {
		MH_free.MH.invokeExact(arg0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_getenv {
	static final MethodHandle MH = FFM.downcall("getenv", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long getenv(byte[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = (long) MH_getenv.MH.invokeExact(lparg0);
		FFM.copyOut(lparg0, arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_malloc {
	static final MethodHandle MH = FFM.downcall("malloc", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long malloc(long arg0) {
	try {
		long rc = (long) MH_malloc.MH.invokeExact(arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__JJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void memmove(long arg0, long arg1, long arg2) {
	try {
		MH_memmove__JJJ.MH.invokeExact(arg0, arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3BJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, byte[] arg1, long arg2) {
	try {
		MH_memmove__J_3BJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3CJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, char[] arg1, long arg2) {
	try {
		MH_memmove__J_3CJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3DJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, double[] arg1, long arg2) {
	try {
		MH_memmove__J_3DJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3FJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, float[] arg1, long arg2) {
	try {
		MH_memmove__J_3FJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3IJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, int[] arg1, long arg2) {
	try {
		MH_memmove__J_3IJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3JJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, long[] arg1, long arg2) {
	try {
		MH_memmove__J_3JJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove__J_3SJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long arg0, short[] arg1, long arg2) {
	try {
		MH_memmove__J_3SJ.MH.invokeExact(arg0, FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3BJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(byte[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3BJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3B_3CJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(byte[] arg0, char[] arg1, long arg2) {
	try {
		MH_memmove___3B_3CJ.MH.invokeExact(FFM.heap(arg0), FFM.heap(arg1), arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3CJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(char[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3CJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3DJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(double[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3DJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3FJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(float[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3FJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3IJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(int[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3IJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3I_3BJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(int[] arg0, byte[] arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_memmove___3I_3BJ.MH.invokeExact(FFM.heap(arg0), lparg1, arg2);
		FFM.copyOut(lparg1, arg1);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3JJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(long[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3JJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memmove___3SJJ {
	static final MethodHandle MH = FFM.downcall("memmove", FunctionDescriptor.ofVoid(ADDRESS, JAVA_LONG, JAVA_LONG), Linker.Option.critical(true));
}
public static void memmove(short[] arg0, long arg1, long arg2) {
	try {
		MH_memmove___3SJJ.MH.invokeExact(FFM.heap(arg0), arg1, arg2);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_memset {
	static final MethodHandle MH = FFM.downcall("memset", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_LONG));
}
public static long memset(long arg0, int arg1, long arg2) {
	try {
		long rc = (long) MH_memset.MH.invokeExact(arg0, arg1, arg2);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_setenv {
	static final MethodHandle MH = FFM.downcall("setenv", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT));
}
public static int setenv(byte[] arg0, byte[] arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_setenv.MH.invokeExact(lparg0, lparg1, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.copyOut(lparg0, arg0);
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_strlen {
	static final MethodHandle MH = FFM.downcall("strlen", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static int strlen(long arg0) {
	try {
		long rc = (long) MH_strlen.MH.invokeExact(arg0);
		return (int) rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
