/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.webkit;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class WebKitGTK_FFM {

private static final SymbolLookup LOOKUP = "1".equals(System.getenv("SWT_GTK4")) ? FFM.library("libwebkitgtk-6.0.so.4") : FFM.library("libwebkit2gtk-4.1.so.0", "libwebkit2gtk-4.0.so.37");

public static int GdkRectangle_sizeof() {
	return (int) org.eclipse.swt.internal.webkit.Structs_FFM.GdkRectangle_SIZEOF;
}

private static final class MH_JSObjectGetProperty {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSObjectGetProperty", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long JSObjectGetProperty(long arg0, long arg1, long arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		long rc = 0;
		if (MH_JSObjectGetProperty.MH != null) {
			rc = (long) MH_JSObjectGetProperty.MH.invokeExact(arg0, arg1, arg2, lparg3);
		}
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSObjectGetPropertyAtIndex {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSObjectGetPropertyAtIndex", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_INT, ADDRESS));
}
public static long JSObjectGetPropertyAtIndex(long arg0, long arg1, int arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		long rc = 0;
		if (MH_JSObjectGetPropertyAtIndex.MH != null) {
			rc = (long) MH_JSObjectGetPropertyAtIndex.MH.invokeExact(arg0, arg1, arg2, lparg3);
		}
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSStringCreateWithUTF8CString {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSStringCreateWithUTF8CString", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long JSStringCreateWithUTF8CString(byte[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_JSStringCreateWithUTF8CString.MH != null) {
			rc = (long) MH_JSStringCreateWithUTF8CString.MH.invokeExact(lparg0);
		}
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSStringGetMaximumUTF8CStringSize {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSStringGetMaximumUTF8CStringSize", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long JSStringGetMaximumUTF8CStringSize(long arg0) {
	try {
		long rc = 0;
		if (MH_JSStringGetMaximumUTF8CStringSize.MH != null) {
			rc = (long) MH_JSStringGetMaximumUTF8CStringSize.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSStringGetUTF8CString {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSStringGetUTF8CString", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static long JSStringGetUTF8CString(long arg0, byte[] arg1, long arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		long rc = 0;
		if (MH_JSStringGetUTF8CString.MH != null) {
			rc = (long) MH_JSStringGetUTF8CString.MH.invokeExact(arg0, lparg1, arg2);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSStringRelease {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSStringRelease", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void JSStringRelease(long arg0) {
	try {
		if (MH_JSStringRelease.MH != null) {
			MH_JSStringRelease.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSValueGetType {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSValueGetType", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static int JSValueGetType(long arg0, long arg1) {
	try {
		int rc = 0;
		if (MH_JSValueGetType.MH != null) {
			rc = (int) MH_JSValueGetType.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSValueToNumber {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSValueToNumber", FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static double JSValueToNumber(long arg0, long arg1, long[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		double rc = 0;
		if (MH_JSValueToNumber.MH != null) {
			rc = (double) MH_JSValueToNumber.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_JSValueToStringCopy {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "JSValueToStringCopy", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long JSValueToStringCopy(long arg0, long arg1, long[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_JSValueToStringCopy.MH != null) {
			rc = (long) MH_JSValueToStringCopy.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1boolean {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_boolean", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_boolean(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1boolean.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1boolean.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1null {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_null", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_null(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1null.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1null.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1number {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_number", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_number(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1number.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1number.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1object {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_object", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_object(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1object.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1object.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1string {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_string", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_string(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1string.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1string.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1typed_1array {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_typed_array", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_typed_array(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1typed_1array.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1typed_1array.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1is_1undefined {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_is_undefined", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_is_undefined(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1is_1undefined.MH != null) {
			rc = (byte) MH_jsc_1value_1is_1undefined.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1object_1get_1property {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_object_get_property", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long jsc_value_object_get_property(long arg0, byte[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		long rc = 0;
		if (MH_jsc_1value_1object_1get_1property.MH != null) {
			rc = (long) MH_jsc_1value_1object_1get_1property.MH.invokeExact(arg0, lparg1);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1object_1get_1property_1at_1index {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_object_get_property_at_index", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT));
}
public static long jsc_value_object_get_property_at_index(long arg0, int arg1) {
	try {
		long rc = 0;
		if (MH_jsc_1value_1object_1get_1property_1at_1index.MH != null) {
			rc = (long) MH_jsc_1value_1object_1get_1property_1at_1index.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1to_1boolean {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_to_boolean", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean jsc_value_to_boolean(long arg0) {
	try {
		byte rc = 0;
		if (MH_jsc_1value_1to_1boolean.MH != null) {
			rc = (byte) MH_jsc_1value_1to_1boolean.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1to_1double {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_to_double", FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
}
public static double jsc_value_to_double(long arg0) {
	try {
		double rc = 0;
		if (MH_jsc_1value_1to_1double.MH != null) {
			rc = (double) MH_jsc_1value_1to_1double.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1to_1int32 {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_to_int32", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int jsc_value_to_int32(long arg0) {
	try {
		int rc = 0;
		if (MH_jsc_1value_1to_1int32.MH != null) {
			rc = (int) MH_jsc_1value_1to_1int32.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_jsc_1value_1to_1string {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "jsc_value_to_string", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long jsc_value_to_string(long arg0) {
	try {
		long rc = 0;
		if (MH_jsc_1value_1to_1string.MH != null) {
			rc = (long) MH_jsc_1value_1to_1string.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1cookie_1get_1name {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_cookie_get_name", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long soup_cookie_get_name(long arg0) {
	try {
		long rc = 0;
		if (MH_soup_1cookie_1get_1name.MH != null) {
			rc = (long) MH_soup_1cookie_1get_1name.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1cookie_1get_1value {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_cookie_get_value", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long soup_cookie_get_value(long arg0) {
	try {
		long rc = 0;
		if (MH_soup_1cookie_1get_1value.MH != null) {
			rc = (long) MH_soup_1cookie_1get_1value.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1cookie_1parse {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_cookie_parse", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static long soup_cookie_parse(byte[] arg0, long arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_soup_1cookie_1parse.MH != null) {
			rc = (long) MH_soup_1cookie_1parse.MH.invokeExact(lparg0, arg1);
		}
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1get_1major_1version {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_get_major_version", FunctionDescriptor.of(JAVA_INT));
}
public static int soup_get_major_version() {
	try {
		int rc = 0;
		if (MH_soup_1get_1major_1version.MH != null) {
			rc = (int) MH_soup_1get_1major_1version.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1message_1headers_1append {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_message_headers_append", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, ADDRESS));
}
public static void soup_message_headers_append(long arg0, byte[] arg1, byte[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		if (MH_soup_1message_1headers_1append.MH != null) {
			MH_soup_1message_1headers_1append.MH.invokeExact(arg0, lparg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1uri_1free {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_uri_free", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void soup_uri_free(long arg0) {
	try {
		if (MH_soup_1uri_1free.MH != null) {
			MH_soup_1uri_1free.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_soup_1uri_1new {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "soup_uri_new", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long soup_uri_new(byte[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_soup_1uri_1new.MH != null) {
			rc = (long) MH_soup_1uri_1new.MH.invokeExact(lparg0);
		}
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1authentication_1request_1authenticate {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_authentication_request_authenticate", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void webkit_authentication_request_authenticate(long arg0, long arg1) {
	try {
		if (MH_webkit_1authentication_1request_1authenticate.MH != null) {
			MH_webkit_1authentication_1request_1authenticate.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1authentication_1request_1cancel {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_authentication_request_cancel", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_authentication_request_cancel(long arg0) {
	try {
		if (MH_webkit_1authentication_1request_1cancel.MH != null) {
			MH_webkit_1authentication_1request_1cancel.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1authentication_1request_1is_1retry {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_authentication_request_is_retry", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean webkit_authentication_request_is_retry(long arg0) {
	try {
		byte rc = 0;
		if (MH_webkit_1authentication_1request_1is_1retry.MH != null) {
			rc = (byte) MH_webkit_1authentication_1request_1is_1retry.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1cookie_1manager_1add_1cookie {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_cookie_manager_add_cookie", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_cookie_manager_add_cookie(long arg0, long arg1, long arg2, long arg3, long arg4) {
	try {
		if (MH_webkit_1cookie_1manager_1add_1cookie.MH != null) {
			MH_webkit_1cookie_1manager_1add_1cookie.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1cookie_1manager_1add_1cookie_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_cookie_manager_add_cookie_finish", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static boolean webkit_cookie_manager_add_cookie_finish(long arg0, long arg1, long[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		byte rc = 0;
		if (MH_webkit_1cookie_1manager_1add_1cookie_1finish.MH != null) {
			rc = (byte) MH_webkit_1cookie_1manager_1add_1cookie_1finish.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1cookie_1manager_1get_1cookies {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_cookie_manager_get_cookies", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_cookie_manager_get_cookies(long arg0, byte[] arg1, long arg2, long arg3, long arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1cookie_1manager_1get_1cookies.MH != null) {
			MH_webkit_1cookie_1manager_1get_1cookies.MH.invokeExact(arg0, lparg1, arg2, arg3, arg4);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1cookie_1manager_1get_1cookies_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_cookie_manager_get_cookies_finish", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long webkit_cookie_manager_get_cookies_finish(long arg0, long arg1, long[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_webkit_1cookie_1manager_1get_1cookies_1finish.MH != null) {
			rc = (long) MH_webkit_1cookie_1manager_1get_1cookies_1finish.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1credential_1free {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_credential_free", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_credential_free(long arg0) {
	try {
		if (MH_webkit_1credential_1free.MH != null) {
			MH_webkit_1credential_1free.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1credential_1new {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_credential_new", FunctionDescriptor.of(JAVA_LONG, ADDRESS, ADDRESS, JAVA_INT));
}
public static long webkit_credential_new(byte[] arg0, byte[] arg1, int arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		long rc = 0;
		if (MH_webkit_1credential_1new.MH != null) {
			rc = (long) MH_webkit_1credential_1new.MH.invokeExact(lparg0, lparg1, arg2);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1event_1target_1add_1event_1listener {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_event_target_add_event_listener", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_INT, JAVA_LONG));
}
public static int webkit_dom_event_target_add_event_listener(long arg0, byte[] arg1, long arg2, int arg3, long arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = 0;
		if (MH_webkit_1dom_1event_1target_1add_1event_1listener.MH != null) {
			rc = (int) MH_webkit_1dom_1event_1target_1add_1event_1listener.MH.invokeExact(arg0, lparg1, arg2, arg3, arg4);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1alt_1key {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_alt_key", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int webkit_dom_mouse_event_get_alt_key(long arg0) {
	try {
		int rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1alt_1key.MH != null) {
			rc = (int) MH_webkit_1dom_1mouse_1event_1get_1alt_1key.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1button {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_button", FunctionDescriptor.of(JAVA_SHORT, JAVA_LONG));
}
public static short webkit_dom_mouse_event_get_button(long arg0) {
	try {
		short rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1button.MH != null) {
			rc = (short) MH_webkit_1dom_1mouse_1event_1get_1button.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1ctrl_1key {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_ctrl_key", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int webkit_dom_mouse_event_get_ctrl_key(long arg0) {
	try {
		int rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1ctrl_1key.MH != null) {
			rc = (int) MH_webkit_1dom_1mouse_1event_1get_1ctrl_1key.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1meta_1key {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_meta_key", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int webkit_dom_mouse_event_get_meta_key(long arg0) {
	try {
		int rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1meta_1key.MH != null) {
			rc = (int) MH_webkit_1dom_1mouse_1event_1get_1meta_1key.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1screen_1x {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_screen_x", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_dom_mouse_event_get_screen_x(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1screen_1x.MH != null) {
			rc = (long) MH_webkit_1dom_1mouse_1event_1get_1screen_1x.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1screen_1y {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_screen_y", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_dom_mouse_event_get_screen_y(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1screen_1y.MH != null) {
			rc = (long) MH_webkit_1dom_1mouse_1event_1get_1screen_1y.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1mouse_1event_1get_1shift_1key {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_mouse_event_get_shift_key", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int webkit_dom_mouse_event_get_shift_key(long arg0) {
	try {
		int rc = 0;
		if (MH_webkit_1dom_1mouse_1event_1get_1shift_1key.MH != null) {
			rc = (int) MH_webkit_1dom_1mouse_1event_1get_1shift_1key.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1ui_1event_1get_1char_1code {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_ui_event_get_char_code", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_dom_ui_event_get_char_code(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1dom_1ui_1event_1get_1char_1code.MH != null) {
			rc = (long) MH_webkit_1dom_1ui_1event_1get_1char_1code.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1ui_1event_1get_1detail {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_ui_event_get_detail", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_dom_ui_event_get_detail(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1dom_1ui_1event_1get_1detail.MH != null) {
			rc = (long) MH_webkit_1dom_1ui_1event_1get_1detail.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1dom_1ui_1event_1get_1key_1code {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_dom_ui_event_get_key_code", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_dom_ui_event_get_key_code(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1dom_1ui_1event_1get_1key_1code.MH != null) {
			rc = (long) MH_webkit_1dom_1ui_1event_1get_1key_1code.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1cancel {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_cancel", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_download_cancel(long arg0) {
	try {
		if (MH_webkit_1download_1cancel.MH != null) {
			MH_webkit_1download_1cancel.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1get_1received_1data_1length {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_get_received_data_length", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_download_get_received_data_length(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1download_1get_1received_1data_1length.MH != null) {
			rc = (long) MH_webkit_1download_1get_1received_1data_1length.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1get_1request {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_get_request", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_download_get_request(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1download_1get_1request.MH != null) {
			rc = (long) MH_webkit_1download_1get_1request.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1get_1response {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_get_response", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_download_get_response(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1download_1get_1response.MH != null) {
			rc = (long) MH_webkit_1download_1get_1response.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1get_1type {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_get_type", FunctionDescriptor.of(JAVA_LONG));
}
public static long webkit_download_get_type() {
	try {
		long rc = 0;
		if (MH_webkit_1download_1get_1type.MH != null) {
			rc = (long) MH_webkit_1download_1get_1type.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1get_1web_1view {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_get_web_view", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_download_get_web_view(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1download_1get_1web_1view.MH != null) {
			rc = (long) MH_webkit_1download_1get_1web_1view.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1set_1allow_1overwrite {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_set_allow_overwrite", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_BYTE));
}
public static void webkit_download_set_allow_overwrite(long arg0, boolean arg1) {
	try {
		if (MH_webkit_1download_1set_1allow_1overwrite.MH != null) {
			MH_webkit_1download_1set_1allow_1overwrite.MH.invokeExact(arg0, (byte) (arg1 ? 1 : 0));
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1download_1set_1destination {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_download_set_destination", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void webkit_download_set_destination(long arg0, byte[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1download_1set_1destination.MH != null) {
			MH_webkit_1download_1set_1destination.MH.invokeExact(arg0, lparg1);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1find_1controller_1search {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_find_controller_search", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT));
}
public static void webkit_find_controller_search(long arg0, byte[] arg1, int arg2, int arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1find_1controller_1search.MH != null) {
			MH_webkit_1find_1controller_1search.MH.invokeExact(arg0, lparg1, arg2, arg3);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1find_1controller_1search_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_find_controller_search_finish", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_find_controller_search_finish(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1find_1controller_1search_1finish.MH != null) {
			rc = (long) MH_webkit_1find_1controller_1search_1finish.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1find_1controller_1search_1next {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_find_controller_search_next", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_find_controller_search_next(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1find_1controller_1search_1next.MH != null) {
			rc = (long) MH_webkit_1find_1controller_1search_1next.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1find_1controller_1search_1previous {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_find_controller_search_previous", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_find_controller_search_previous(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1find_1controller_1search_1previous.MH != null) {
			rc = (long) MH_webkit_1find_1controller_1search_1previous.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1get_1major_1version {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_get_major_version", FunctionDescriptor.of(JAVA_INT));
}
public static int webkit_get_major_version() {
	try {
		int rc = 0;
		if (MH_webkit_1get_1major_1version.MH != null) {
			rc = (int) MH_webkit_1get_1major_1version.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1get_1micro_1version {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_get_micro_version", FunctionDescriptor.of(JAVA_INT));
}
public static int webkit_get_micro_version() {
	try {
		int rc = 0;
		if (MH_webkit_1get_1micro_1version.MH != null) {
			rc = (int) MH_webkit_1get_1micro_1version.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1get_1minor_1version {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_get_minor_version", FunctionDescriptor.of(JAVA_INT));
}
public static int webkit_get_minor_version() {
	try {
		int rc = 0;
		if (MH_webkit_1get_1minor_1version.MH != null) {
			rc = (int) MH_webkit_1get_1minor_1version.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1hit_1test_1result_1context_1is_1link {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_hit_test_result_context_is_link", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean webkit_hit_test_result_context_is_link(long arg0) {
	try {
		byte rc = 0;
		if (MH_webkit_1hit_1test_1result_1context_1is_1link.MH != null) {
			rc = (byte) MH_webkit_1hit_1test_1result_1context_1is_1link.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1hit_1test_1result_1get_1link_1title {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_hit_test_result_get_link_title", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_hit_test_result_get_link_title(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1hit_1test_1result_1get_1link_1title.MH != null) {
			rc = (long) MH_webkit_1hit_1test_1result_1get_1link_1title.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1hit_1test_1result_1get_1link_1uri {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_hit_test_result_get_link_uri", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_hit_test_result_get_link_uri(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1hit_1test_1result_1get_1link_1uri.MH != null) {
			rc = (long) MH_webkit_1hit_1test_1result_1get_1link_1uri.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1javascript_1result_1get_1global_1context {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_javascript_result_get_global_context", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_javascript_result_get_global_context(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1javascript_1result_1get_1global_1context.MH != null) {
			rc = (long) MH_webkit_1javascript_1result_1get_1global_1context.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1javascript_1result_1get_1value {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_javascript_result_get_value", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_javascript_result_get_value(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1javascript_1result_1get_1value.MH != null) {
			rc = (long) MH_webkit_1javascript_1result_1get_1value.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1javascript_1result_1unref {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_javascript_result_unref", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_javascript_result_unref(long arg0) {
	try {
		if (MH_webkit_1javascript_1result_1unref.MH != null) {
			MH_webkit_1javascript_1result_1unref.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1navigation_1action_1get_1request {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_navigation_action_get_request", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_navigation_action_get_request(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1navigation_1action_1get_1request.MH != null) {
			rc = (long) MH_webkit_1navigation_1action_1get_1request.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1navigation_1policy_1decision_1get_1navigation_1action {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_navigation_policy_decision_get_navigation_action", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_navigation_policy_decision_get_navigation_action(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1navigation_1policy_1decision_1get_1navigation_1action.MH != null) {
			rc = (long) MH_webkit_1navigation_1policy_1decision_1get_1navigation_1action.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1navigation_1policy_1decision_1get_1request {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_navigation_policy_decision_get_request", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_navigation_policy_decision_get_request(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1navigation_1policy_1decision_1get_1request.MH != null) {
			rc = (long) MH_webkit_1navigation_1policy_1decision_1get_1request.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1network_1session_1allow_1tls_1certificate_1for_1host {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_network_session_allow_tls_certificate_for_host", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long webkit_network_session_allow_tls_certificate_for_host(long arg0, long arg1, byte[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_webkit_1network_1session_1allow_1tls_1certificate_1for_1host.MH != null) {
			rc = (long) MH_webkit_1network_1session_1allow_1tls_1certificate_1for_1host.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1network_1session_1get_1cookie_1manager {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_network_session_get_cookie_manager", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_network_session_get_cookie_manager(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1network_1session_1get_1cookie_1manager.MH != null) {
			rc = (long) MH_webkit_1network_1session_1get_1cookie_1manager.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1network_1session_1get_1default {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_network_session_get_default", FunctionDescriptor.of(JAVA_LONG));
}
public static long webkit_network_session_get_default() {
	try {
		long rc = 0;
		if (MH_webkit_1network_1session_1get_1default.MH != null) {
			rc = (long) MH_webkit_1network_1session_1get_1default.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1network_1session_1get_1website_1data_1manager {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_network_session_get_website_data_manager", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_network_session_get_website_data_manager(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1network_1session_1get_1website_1data_1manager.MH != null) {
			rc = (long) MH_webkit_1network_1session_1get_1website_1data_1manager.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1network_1session_1set_1tls_1errors_1policy {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_network_session_set_tls_errors_policy", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void webkit_network_session_set_tls_errors_policy(long arg0, int arg1) {
	try {
		if (MH_webkit_1network_1session_1set_1tls_1errors_1policy.MH != null) {
			MH_webkit_1network_1session_1set_1tls_1errors_1policy.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1policy_1decision_1download {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_policy_decision_download", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_policy_decision_download(long arg0) {
	try {
		if (MH_webkit_1policy_1decision_1download.MH != null) {
			MH_webkit_1policy_1decision_1download.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1policy_1decision_1ignore {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_policy_decision_ignore", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_policy_decision_ignore(long arg0) {
	try {
		if (MH_webkit_1policy_1decision_1ignore.MH != null) {
			MH_webkit_1policy_1decision_1ignore.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1response_1policy_1decision_1get_1request {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_response_policy_decision_get_request", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_response_policy_decision_get_request(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1response_1policy_1decision_1get_1request.MH != null) {
			rc = (long) MH_webkit_1response_1policy_1decision_1get_1request.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1response_1policy_1decision_1get_1response {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_response_policy_decision_get_response", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_response_policy_decision_get_response(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1response_1policy_1decision_1get_1response.MH != null) {
			rc = (long) MH_webkit_1response_1policy_1decision_1get_1response.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1security_1manager_1register_1uri_1scheme_1as_1secure {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_security_manager_register_uri_scheme_as_secure", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void webkit_security_manager_register_uri_scheme_as_secure(long arg0, byte[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1security_1manager_1register_1uri_1scheme_1as_1secure.MH != null) {
			MH_webkit_1security_1manager_1register_1uri_1scheme_1as_1secure.MH.invokeExact(arg0, lparg1);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1request_1get_1http_1headers {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_request_get_http_headers", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_uri_request_get_http_headers(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1uri_1request_1get_1http_1headers.MH != null) {
			rc = (long) MH_webkit_1uri_1request_1get_1http_1headers.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1request_1get_1uri {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_request_get_uri", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_uri_request_get_uri(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1uri_1request_1get_1uri.MH != null) {
			rc = (long) MH_webkit_1uri_1request_1get_1uri.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1request_1new {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_request_new", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long webkit_uri_request_new(byte[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_webkit_1uri_1request_1new.MH != null) {
			rc = (long) MH_webkit_1uri_1request_1new.MH.invokeExact(lparg0);
		}
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1response_1get_1content_1length {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_response_get_content_length", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_uri_response_get_content_length(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1uri_1response_1get_1content_1length.MH != null) {
			rc = (long) MH_webkit_1uri_1response_1get_1content_1length.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1response_1get_1mime_1type {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_response_get_mime_type", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_uri_response_get_mime_type(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1uri_1response_1get_1mime_1type.MH != null) {
			rc = (long) MH_webkit_1uri_1response_1get_1mime_1type.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1scheme_1request_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_scheme_request_finish", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static void webkit_uri_scheme_request_finish(long arg0, long arg1, long arg2, byte[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		if (MH_webkit_1uri_1scheme_1request_1finish.MH != null) {
			MH_webkit_1uri_1scheme_1request_1finish.MH.invokeExact(arg0, arg1, arg2, lparg3);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1scheme_1request_1get_1uri {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_scheme_request_get_uri", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_uri_scheme_request_get_uri(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1uri_1scheme_1request_1get_1uri.MH != null) {
			rc = (long) MH_webkit_1uri_1scheme_1request_1get_1uri.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1uri_1scheme_1request_1get_1web_1view {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_uri_scheme_request_get_web_view", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_uri_scheme_request_get_web_view(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1uri_1scheme_1request_1get_1web_1view.MH != null) {
			rc = (long) MH_webkit_1uri_1scheme_1request_1get_1web_1view.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1user_1content_1manager_1add_1script {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_user_content_manager_add_script", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static long webkit_user_content_manager_add_script(long arg0, long arg1) {
	try {
		long rc = 0;
		if (MH_webkit_1user_1content_1manager_1add_1script.MH != null) {
			rc = (long) MH_webkit_1user_1content_1manager_1add_1script.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1user_1content_1manager_1remove_1all_1scripts {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_user_content_manager_remove_all_scripts", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_user_content_manager_remove_all_scripts(long arg0) {
	try {
		if (MH_webkit_1user_1content_1manager_1remove_1all_1scripts.MH != null) {
			MH_webkit_1user_1content_1manager_1remove_1all_1scripts.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1user_1script_1new {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_user_script_new", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static long webkit_user_script_new(byte[] arg0, int arg1, int arg2, long arg3, long arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_webkit_1user_1script_1new.MH != null) {
			rc = (long) MH_webkit_1user_1script_1new.MH.invokeExact(lparg0, arg1, arg2, arg3, arg4);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1user_1script_1unref {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_user_script_unref", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_user_script_unref(long arg0) {
	try {
		if (MH_webkit_1user_1script_1unref.MH != null) {
			MH_webkit_1user_1script_1unref.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1add_1path_1to_1sandbox {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_add_path_to_sandbox", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_BYTE));
}
public static void webkit_web_context_add_path_to_sandbox(long arg0, byte[] arg1, boolean arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1web_1context_1add_1path_1to_1sandbox.MH != null) {
			MH_webkit_1web_1context_1add_1path_1to_1sandbox.MH.invokeExact(arg0, lparg1, (byte) (arg2 ? 1 : 0));
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1allow_1tls_1certificate_1for_1host {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_allow_tls_certificate_for_host", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long webkit_web_context_allow_tls_certificate_for_host(long arg0, long arg1, byte[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_webkit_1web_1context_1allow_1tls_1certificate_1for_1host.MH != null) {
			rc = (long) MH_webkit_1web_1context_1allow_1tls_1certificate_1for_1host.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1get_1cookie_1manager {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_get_cookie_manager", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_context_get_cookie_manager(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1context_1get_1cookie_1manager.MH != null) {
			rc = (long) MH_webkit_1web_1context_1get_1cookie_1manager.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1get_1default {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_get_default", FunctionDescriptor.of(JAVA_LONG));
}
public static long webkit_web_context_get_default() {
	try {
		long rc = 0;
		if (MH_webkit_1web_1context_1get_1default.MH != null) {
			rc = (long) MH_webkit_1web_1context_1get_1default.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1get_1security_1manager {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_get_security_manager", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_context_get_security_manager(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1context_1get_1security_1manager.MH != null) {
			rc = (long) MH_webkit_1web_1context_1get_1security_1manager.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1get_1type {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_get_type", FunctionDescriptor.of(JAVA_LONG));
}
public static long webkit_web_context_get_type() {
	try {
		long rc = 0;
		if (MH_webkit_1web_1context_1get_1type.MH != null) {
			rc = (long) MH_webkit_1web_1context_1get_1type.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1get_1website_1data_1manager {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_get_website_data_manager", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_context_get_website_data_manager(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1context_1get_1website_1data_1manager.MH != null) {
			rc = (long) MH_webkit_1web_1context_1get_1website_1data_1manager.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1register_1uri_1scheme {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_register_uri_scheme", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_web_context_register_uri_scheme(long arg0, byte[] arg1, long arg2, long arg3, long arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1web_1context_1register_1uri_1scheme.MH != null) {
			MH_webkit_1web_1context_1register_1uri_1scheme.MH.invokeExact(arg0, lparg1, arg2, arg3, arg4);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1context_1set_1tls_1errors_1policy {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_context_set_tls_errors_policy", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void webkit_web_context_set_tls_errors_policy(long arg0, int arg1) {
	try {
		if (MH_webkit_1web_1context_1set_1tls_1errors_1policy.MH != null) {
			MH_webkit_1web_1context_1set_1tls_1errors_1policy.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1resource_1get_1data {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_resource_get_data", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_web_resource_get_data(long arg0, long arg1, long arg2, long arg3) {
	try {
		if (MH_webkit_1web_1resource_1get_1data.MH != null) {
			MH_webkit_1web_1resource_1get_1data.MH.invokeExact(arg0, arg1, arg2, arg3);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1resource_1get_1data_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_resource_get_data_finish", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS, ADDRESS));
}
public static long webkit_web_resource_get_data_finish(long arg0, long arg1, long[] arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		long rc = 0;
		if (MH_webkit_1web_1resource_1get_1data_1finish.MH != null) {
			rc = (long) MH_webkit_1web_1resource_1get_1data_1finish.MH.invokeExact(arg0, arg1, lparg2, lparg3);
		}
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1can_1go_1back {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_can_go_back", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int webkit_web_view_can_go_back(long arg0) {
	try {
		int rc = 0;
		if (MH_webkit_1web_1view_1can_1go_1back.MH != null) {
			rc = (int) MH_webkit_1web_1view_1can_1go_1back.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1can_1go_1forward {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_can_go_forward", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int webkit_web_view_can_go_forward(long arg0) {
	try {
		int rc = 0;
		if (MH_webkit_1web_1view_1can_1go_1forward.MH != null) {
			rc = (int) MH_webkit_1web_1view_1can_1go_1forward.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1can_1show_1mime_1type {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_can_show_mime_type", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static int webkit_web_view_can_show_mime_type(long arg0, long arg1) {
	try {
		int rc = 0;
		if (MH_webkit_1web_1view_1can_1show_1mime_1type.MH != null) {
			rc = (int) MH_webkit_1web_1view_1can_1show_1mime_1type.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1evaluate_1javascript {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_evaluate_javascript", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_web_view_evaluate_javascript(long arg0, byte[] arg1, long arg2, long arg3, long arg4, long arg5, long arg6, long arg7) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1web_1view_1evaluate_1javascript.MH != null) {
			MH_webkit_1web_1view_1evaluate_1javascript.MH.invokeExact(arg0, lparg1, arg2, arg3, arg4, arg5, arg6, arg7);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1evaluate_1javascript_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_evaluate_javascript_finish", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long webkit_web_view_evaluate_javascript_finish(long arg0, long arg1, long[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_webkit_1web_1view_1evaluate_1javascript_1finish.MH != null) {
			rc = (long) MH_webkit_1web_1view_1evaluate_1javascript_1finish.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1context {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_context", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_context(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1context.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1context.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1estimated_1load_1progress {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_estimated_load_progress", FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
}
public static double webkit_web_view_get_estimated_load_progress(long arg0) {
	try {
		double rc = 0;
		if (MH_webkit_1web_1view_1get_1estimated_1load_1progress.MH != null) {
			rc = (double) MH_webkit_1web_1view_1get_1estimated_1load_1progress.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1find_1controller {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_find_controller", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_find_controller(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1find_1controller.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1find_1controller.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1main_1resource {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_main_resource", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_main_resource(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1main_1resource.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1main_1resource.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1page_1id {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_page_id", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_page_id(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1page_1id.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1page_1id.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1settings {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_settings", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_settings(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1settings.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1settings.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1title {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_title", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_title(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1title.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1title.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1uri {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_uri", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_uri(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1uri.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1uri.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1user_1content_1manager {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_user_content_manager", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_user_content_manager(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1user_1content_1manager.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1user_1content_1manager.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1get_1window_1properties {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_get_window_properties", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_get_window_properties(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1get_1window_1properties.MH != null) {
			rc = (long) MH_webkit_1web_1view_1get_1window_1properties.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1go_1back {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_go_back", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_web_view_go_back(long arg0) {
	try {
		if (MH_webkit_1web_1view_1go_1back.MH != null) {
			MH_webkit_1web_1view_1go_1back.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1go_1forward {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_go_forward", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_web_view_go_forward(long arg0) {
	try {
		if (MH_webkit_1web_1view_1go_1forward.MH != null) {
			MH_webkit_1web_1view_1go_1forward.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1load_1bytes {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_load_bytes", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, ADDRESS, ADDRESS, ADDRESS));
}
public static void webkit_web_view_load_bytes(long arg0, long arg1, byte[] arg2, byte[] arg3, byte[] arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		if (MH_webkit_1web_1view_1load_1bytes.MH != null) {
			MH_webkit_1web_1view_1load_1bytes.MH.invokeExact(arg0, arg1, lparg2, lparg3, lparg4);
		}
		FFM.copyOut(lparg4, arg4);
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1load_1html {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_load_html", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, ADDRESS));
}
public static void webkit_web_view_load_html(long arg0, byte[] arg1, byte[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		if (MH_webkit_1web_1view_1load_1html.MH != null) {
			MH_webkit_1web_1view_1load_1html.MH.invokeExact(arg0, lparg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1load_1request {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_load_request", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void webkit_web_view_load_request(long arg0, long arg1) {
	try {
		if (MH_webkit_1web_1view_1load_1request.MH != null) {
			MH_webkit_1web_1view_1load_1request.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1load_1uri {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_load_uri", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void webkit_web_view_load_uri(long arg0, byte[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1web_1view_1load_1uri.MH != null) {
			MH_webkit_1web_1view_1load_1uri.MH.invokeExact(arg0, lparg1);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1new {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_new", FunctionDescriptor.of(JAVA_LONG));
}
public static long webkit_web_view_new() {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1new.MH != null) {
			rc = (long) MH_webkit_1web_1view_1new.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1new_1with_1related_1view {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_new_with_related_view", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long webkit_web_view_new_with_related_view(long arg0) {
	try {
		long rc = 0;
		if (MH_webkit_1web_1view_1new_1with_1related_1view.MH != null) {
			rc = (long) MH_webkit_1web_1view_1new_1with_1related_1view.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1reload {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_reload", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_web_view_reload(long arg0) {
	try {
		if (MH_webkit_1web_1view_1reload.MH != null) {
			MH_webkit_1web_1view_1reload.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1run_1javascript {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_run_javascript", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_web_view_run_javascript(long arg0, byte[] arg1, long arg2, long arg3, long arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		if (MH_webkit_1web_1view_1run_1javascript.MH != null) {
			MH_webkit_1web_1view_1run_1javascript.MH.invokeExact(arg0, lparg1, arg2, arg3, arg4);
		}
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1run_1javascript_1finish {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_run_javascript_finish", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long webkit_web_view_run_javascript_finish(long arg0, long arg1, long[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_webkit_1web_1view_1run_1javascript_1finish.MH != null) {
			rc = (long) MH_webkit_1web_1view_1run_1javascript_1finish.MH.invokeExact(arg0, arg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1web_1view_1stop_1loading {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_web_view_stop_loading", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void webkit_web_view_stop_loading(long arg0) {
	try {
		if (MH_webkit_1web_1view_1stop_1loading.MH != null) {
			MH_webkit_1web_1view_1stop_1loading.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1website_1data_1manager_1clear {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_website_data_manager_clear", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void webkit_website_data_manager_clear(long arg0, long arg1, long arg2, long arg3, long arg4, long arg5) {
	try {
		if (MH_webkit_1website_1data_1manager_1clear.MH != null) {
			MH_webkit_1website_1data_1manager_1clear.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_webkit_1window_1properties_1get_1geometry {
	static final MethodHandle MH = FFM.downcallOptional(LOOKUP, "webkit_window_properties_get_geometry", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void webkit_window_properties_get_geometry(long arg0, org.eclipse.swt.internal.webkit.GdkRectangle arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.webkit.Structs_FFM.GdkRectangle_SIZEOF, 16);
		if (MH_webkit_1window_1properties_1get_1geometry.MH != null) {
			MH_webkit_1window_1properties_1get_1geometry.MH.invokeExact(arg0, lparg1);
		}
		if (arg1 != null) org.eclipse.swt.internal.webkit.Structs_FFM.GdkRectangle_read(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
