package org.eclipse.swt.internal.gtk;

/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */

import org.eclipse.swt.internal.ffm.*;

/** Sizes and field offsets of C types that have no Java struct class. */
public final class Extra_FFM {

	public static final long GINTERFACEINFO = 24L;
	public static final long GINTERFACEINFO_INTERFACE_INIT = 0L;
	public static final long GOBJECT = 24L;
	public static final long GPOLLFD = 8L;
	public static final long GVALUE = 24L;
	public static final long GDKPAINTABLEINTERFACE = FFM.GTK4 ? 64L : -1L;
	public static final long GDKPAINTABLEINTERFACE_GET_FLAGS = FFM.GTK4 ? 32L : -1L;
	public static final long GDKPAINTABLEINTERFACE_GET_INTRINSIC_ASPECT_RATIO = FFM.GTK4 ? 56L : -1L;
	public static final long GDKPAINTABLEINTERFACE_GET_INTRINSIC_HEIGHT = FFM.GTK4 ? 48L : -1L;
	public static final long GDKPAINTABLEINTERFACE_GET_INTRINSIC_WIDTH = FFM.GTK4 ? 40L : -1L;
	public static final long GDKPAINTABLEINTERFACE_SNAPSHOT = FFM.GTK4 ? 16L : -1L;
	public static final long GTKCELLRENDERERPIXBUF = FFM.GTK4 ? -1L : 40L;
	public static final long GTKCELLRENDERERPIXBUFCLASS = FFM.GTK4 ? -1L : 296L;
	public static final long GTKCELLRENDERERTEXT = FFM.GTK4 ? 32L : 40L;
	public static final long GTKCELLRENDERERTEXTCLASS = FFM.GTK4 ? 360L : 304L;
	public static final long GTKCELLRENDERERTOGGLE = FFM.GTK4 ? -1L : 40L;
	public static final long GTKCELLRENDERERTOGGLECLASS = FFM.GTK4 ? -1L : 304L;
	public static final long GTKCONTAINER = FFM.GTK4 ? -1L : 40L;
	public static final long GTKCONTAINERACCESSIBLE = FFM.GTK4 ? -1L : 96L;
	public static final long GTKCONTAINERACCESSIBLECLASS = FFM.GTK4 ? -1L : 416L;
	public static final long GTKCONTAINERCLASS = FFM.GTK4 ? -1L : 976L;
	public static final long GTKCONTAINERCLASS_ADD = FFM.GTK4 ? -1L : 824L;
	public static final long GTKCONTAINERCLASS_FORALL = FFM.GTK4 ? -1L : 848L;
	public static final long GTKCONTAINERCLASS_REMOVE = FFM.GTK4 ? -1L : 832L;
	public static final long GTKTEXTITER = 80L;
	public static final long GTKTREEITER = 32L;
	public static final long GTKWIDGET = 32L;
	public static final long GTKWIDGETCLASS_GET_ACCESSIBLE = FFM.GTK4 ? -1L : 688L;
	public static final long GTKWIDGETCLASS_GET_PREFERRED_HEIGHT = FFM.GTK4 ? -1L : 304L;
	public static final long GTKWIDGETCLASS_GET_PREFERRED_WIDTH = FFM.GTK4 ? -1L : 320L;
	public static final long GTKWIDGETCLASS_MAP = FFM.GTK4 ? 152L : 184L;
	public static final long GTKWIDGETCLASS_MEASURE = FFM.GTK4 ? 232L : -1L;
	public static final long GTKWIDGETCLASS_REALIZE = FFM.GTK4 ? 168L : 200L;
	public static final long GTKWIDGETCLASS_SIZE_ALLOCATE = FFM.GTK4 ? 200L : 216L;
}
