package org.eclipse.swt.internal.gtk;

/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */

/** Sizes and field offsets of C types that have no Java struct class. */
public final class Extra_FFM {

	public static final long GTKCONTAINER = 40L;
	public static final long GTKCONTAINERCLASS = 976L;
	public static final long GTKCONTAINERCLASS_ADD = 824L;
	public static final long GTKCONTAINERCLASS_FORALL = 848L;
	public static final long GTKCONTAINERCLASS_REMOVE = 832L;
	public static final long GTKWIDGETCLASS_GET_ACCESSIBLE = 688L;
	public static final long GTKWIDGETCLASS_GET_PREFERRED_HEIGHT = 304L;
	public static final long GTKWIDGETCLASS_GET_PREFERRED_WIDTH = 320L;
	public static final long GTKWIDGETCLASS_MAP = 184L;
	public static final long GTKWIDGETCLASS_REALIZE = 200L;
	public static final long GTKWIDGETCLASS_SIZE_ALLOCATE = 216L;
}
