/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.gtk;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class GDK_FFM {

public static int GdkKeymapKey_sizeof() {
	return (int) org.eclipse.swt.internal.gtk.Structs_FFM.GdkKeymapKey_SIZEOF;
}

public static int GdkRGBA_sizeof() {
	return (int) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_SIZEOF;
}

public static int GdkRectangle_sizeof() {
	return (int) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_SIZEOF;
}

private static final class MH_gdk_1atom_1intern {
	static final MethodHandle MH = FFM.downcallOptional("gdk_atom_intern", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_BYTE), Linker.Option.critical(true));
}
public static long gdk_atom_intern(byte[] arg0, boolean arg1) {
	try {
		long rc = 0;
		if (MH_gdk_1atom_1intern.MH != null) {
			rc = (long) MH_gdk_1atom_1intern.MH.invokeExact(FFM.heap(arg0), (byte) (arg1 ? 1 : 0));
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1atom_1name {
	static final MethodHandle MH = FFM.downcall("gdk_atom_name", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_atom_name(long arg0) {
	try {
		long rc = (long) MH_gdk_1atom_1name.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1create {
	static final MethodHandle MH = FFM.downcallOptional("gdk_cairo_create", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_cairo_create(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1cairo_1create.MH != null) {
			rc = (long) MH_gdk_1cairo_1create.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1get_1clip_1rectangle {
	static final MethodHandle MH = FFM.downcallOptional("gdk_cairo_get_clip_rectangle", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG, ADDRESS));
}
public static boolean gdk_cairo_get_clip_rectangle(long arg0, org.eclipse.swt.internal.gtk.GdkRectangle arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_SIZEOF, 16);
		byte rc = 0;
		if (MH_gdk_1cairo_1get_1clip_1rectangle.MH != null) {
			rc = (byte) MH_gdk_1cairo_1get_1clip_1rectangle.MH.invokeExact(arg0, lparg1);
		}
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_read(lparg1, arg1);
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1region {
	static final MethodHandle MH = FFM.downcall("gdk_cairo_region", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void gdk_cairo_region(long arg0, long arg1) {
	try {
		MH_gdk_1cairo_1region.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1region_1create_1from_1surface {
	static final MethodHandle MH = FFM.downcall("gdk_cairo_region_create_from_surface", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_cairo_region_create_from_surface(long arg0) {
	try {
		long rc = (long) MH_gdk_1cairo_1region_1create_1from_1surface.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1set_1source_1pixbuf {
	static final MethodHandle MH = FFM.downcall("gdk_cairo_set_source_pixbuf", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void gdk_cairo_set_source_pixbuf(long arg0, long arg1, double arg2, double arg3) {
	try {
		MH_gdk_1cairo_1set_1source_1pixbuf.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1set_1source_1rgba {
	static final MethodHandle MH = FFM.downcall("gdk_cairo_set_source_rgba", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void gdk_cairo_set_source_rgba(long arg0, org.eclipse.swt.internal.gtk.GdkRGBA arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_write(lparg1, arg1);
		MH_gdk_1cairo_1set_1source_1rgba.MH.invokeExact(arg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_read(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cairo_1set_1source_1window {
	static final MethodHandle MH = FFM.downcall("gdk_cairo_set_source_window", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_DOUBLE, JAVA_DOUBLE));
}
public static void gdk_cairo_set_source_window(long arg0, long arg1, int arg2, int arg3) {
	try {
		MH_gdk_1cairo_1set_1source_1window.MH.invokeExact(arg0, arg1, (double) arg2, (double) arg3);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cursor_1new_1from_1name__JLjava_lang_String_2 {
	static final MethodHandle MH = FFM.downcall("gdk_cursor_new_from_name", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static long gdk_cursor_new_from_name(long arg0, String arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.string(arena, arg1);
		long rc = (long) MH_gdk_1cursor_1new_1from_1name__JLjava_lang_String_2.MH.invokeExact(arg0, lparg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cursor_1new_1from_1name__Ljava_lang_String_2J {
	static final MethodHandle MH = FFM.downcall("gdk_cursor_new_from_name", FunctionDescriptor.of(JAVA_LONG, ADDRESS, JAVA_LONG));
}
public static long gdk_cursor_new_from_name(String arg0, long arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.string(arena, arg0);
		long rc = (long) MH_gdk_1cursor_1new_1from_1name__Ljava_lang_String_2J.MH.invokeExact(lparg0, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1cursor_1new_1from_1pixbuf {
	static final MethodHandle MH = FFM.downcall("gdk_cursor_new_from_pixbuf", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static long gdk_cursor_new_from_pixbuf(long arg0, long arg1, int arg2, int arg3) {
	try {
		long rc = (long) MH_gdk_1cursor_1new_1from_1pixbuf.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1device_1get_1associated_1device {
	static final MethodHandle MH = FFM.downcallOptional("gdk_device_get_associated_device", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_device_get_associated_device(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1device_1get_1associated_1device.MH != null) {
			rc = (long) MH_gdk_1device_1get_1associated_1device.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1device_1get_1seat {
	static final MethodHandle MH = FFM.downcall("gdk_device_get_seat", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_device_get_seat(long arg0) {
	try {
		long rc = (long) MH_gdk_1device_1get_1seat.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1device_1get_1surface_1at_1position {
	static final MethodHandle MH = FFM.downcallOptional("gdk_device_get_surface_at_position", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, ADDRESS));
}
public static long gdk_device_get_surface_at_position(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_gdk_1device_1get_1surface_1at_1position.MH != null) {
			rc = (long) MH_gdk_1device_1get_1surface_1at_1position.MH.invokeExact(arg0, lparg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1device_1get_1window_1at_1position {
	static final MethodHandle MH = FFM.downcallOptional("gdk_device_get_window_at_position", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, ADDRESS));
}
public static long gdk_device_get_window_at_position(long arg0, int[] arg1, int[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		long rc = 0;
		if (MH_gdk_1device_1get_1window_1at_1position.MH != null) {
			rc = (long) MH_gdk_1device_1get_1window_1at_1position.MH.invokeExact(arg0, lparg1, lparg2);
		}
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1device_1warp {
	static final MethodHandle MH = FFM.downcallOptional("gdk_device_warp", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void gdk_device_warp(long arg0, long arg1, int arg2, int arg3) {
	try {
		if (MH_gdk_1device_1warp.MH != null) {
			MH_gdk_1device_1warp.MH.invokeExact(arg0, arg1, arg2, arg3);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1beep {
	static final MethodHandle MH = FFM.downcall("gdk_display_beep", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_display_beep(long arg0) {
	try {
		MH_gdk_1display_1beep.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1clipboard {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_clipboard", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_clipboard(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1clipboard.MH != null) {
			rc = (long) MH_gdk_1display_1get_1clipboard.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1default {
	static final MethodHandle MH = FFM.downcall("gdk_display_get_default", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_display_get_default() {
	try {
		long rc = (long) MH_gdk_1display_1get_1default.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1default_1group {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_default_group", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_default_group(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1default_1group.MH != null) {
			rc = (long) MH_gdk_1display_1get_1default_1group.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1default_1seat {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_default_seat", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_default_seat(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1default_1seat.MH != null) {
			rc = (long) MH_gdk_1display_1get_1default_1seat.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1monitor {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_monitor", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT));
}
public static long gdk_display_get_monitor(long arg0, int arg1) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1monitor.MH != null) {
			rc = (long) MH_gdk_1display_1get_1monitor.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1monitor_1at_1point {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_monitor_at_point", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static long gdk_display_get_monitor_at_point(long arg0, int arg1, int arg2) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1monitor_1at_1point.MH != null) {
			rc = (long) MH_gdk_1display_1get_1monitor_1at_1point.MH.invokeExact(arg0, arg1, arg2);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1monitor_1at_1window {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_monitor_at_window", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_monitor_at_window(long arg0, long arg1) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1monitor_1at_1window.MH != null) {
			rc = (long) MH_gdk_1display_1get_1monitor_1at_1window.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1monitors {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_monitors", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_monitors(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1monitors.MH != null) {
			rc = (long) MH_gdk_1display_1get_1monitors.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1n_1monitors {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_n_monitors", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_display_get_n_monitors(long arg0) {
	try {
		int rc = 0;
		if (MH_gdk_1display_1get_1n_1monitors.MH != null) {
			rc = (int) MH_gdk_1display_1get_1n_1monitors.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1primary_1clipboard {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_primary_clipboard", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_primary_clipboard(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1primary_1clipboard.MH != null) {
			rc = (long) MH_gdk_1display_1get_1primary_1clipboard.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1get_1primary_1monitor {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_get_primary_monitor", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_display_get_primary_monitor(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1display_1get_1primary_1monitor.MH != null) {
			rc = (long) MH_gdk_1display_1get_1primary_1monitor.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1is_1composited {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_is_composited", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean gdk_display_is_composited(long arg0) {
	try {
		byte rc = 0;
		if (MH_gdk_1display_1is_1composited.MH != null) {
			rc = (byte) MH_gdk_1display_1is_1composited.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1map_1keyval {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_map_keyval", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG, JAVA_INT, ADDRESS, ADDRESS));
}
public static boolean gdk_display_map_keyval(long arg0, int arg1, long[] arg2, int[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		byte rc = 0;
		if (MH_gdk_1display_1map_1keyval.MH != null) {
			rc = (byte) MH_gdk_1display_1map_1keyval.MH.invokeExact(arg0, arg1, lparg2, lparg3);
		}
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1put_1event {
	static final MethodHandle MH = FFM.downcall("gdk_display_put_event", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void gdk_display_put_event(long arg0, long arg1) {
	try {
		MH_gdk_1display_1put_1event.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1display_1supports_1cursor_1color {
	static final MethodHandle MH = FFM.downcallOptional("gdk_display_supports_cursor_color", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG));
}
public static boolean gdk_display_supports_cursor_color(long arg0) {
	try {
		byte rc = 0;
		if (MH_gdk_1display_1supports_1cursor_1color.MH != null) {
			rc = (byte) MH_gdk_1display_1supports_1cursor_1color.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1drag_1context_1get_1actions {
	static final MethodHandle MH = FFM.downcallOptional("gdk_drag_context_get_actions", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_drag_context_get_actions(long arg0) {
	try {
		int rc = 0;
		if (MH_gdk_1drag_1context_1get_1actions.MH != null) {
			rc = (int) MH_gdk_1drag_1context_1get_1actions.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1drag_1context_1get_1dest_1window {
	static final MethodHandle MH = FFM.downcall("gdk_drag_context_get_dest_window", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_drag_context_get_dest_window(long arg0) {
	try {
		long rc = (long) MH_gdk_1drag_1context_1get_1dest_1window.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1drag_1context_1get_1selected_1action {
	static final MethodHandle MH = FFM.downcallOptional("gdk_drag_context_get_selected_action", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_drag_context_get_selected_action(long arg0) {
	try {
		int rc = 0;
		if (MH_gdk_1drag_1context_1get_1selected_1action.MH != null) {
			rc = (int) MH_gdk_1drag_1context_1get_1selected_1action.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1drag_1context_1list_1targets {
	static final MethodHandle MH = FFM.downcall("gdk_drag_context_list_targets", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_drag_context_list_targets(long arg0) {
	try {
		long rc = (long) MH_gdk_1drag_1context_1list_1targets.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1drag_1status {
	static final MethodHandle MH = FFM.downcall("gdk_drag_status", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void gdk_drag_status(long arg0, int arg1, int arg2) {
	try {
		MH_gdk_1drag_1status.MH.invokeExact(arg0, arg1, arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1copy {
	static final MethodHandle MH = FFM.downcall("gdk_event_copy", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_event_copy(long arg0) {
	try {
		long rc = (long) MH_gdk_1event_1copy.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1free {
	static final MethodHandle MH = FFM.downcall("gdk_event_free", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_event_free(long arg0) {
	try {
		MH_gdk_1event_1free.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get {
	static final MethodHandle MH = FFM.downcall("gdk_event_get", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_event_get() {
	try {
		long rc = (long) MH_gdk_1event_1get.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1button {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_button", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static boolean gdk_event_get_button(long arg0, int[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1event_1get_1button.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1coords {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_coords", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS));
}
public static boolean gdk_event_get_coords(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		int rc = (int) MH_gdk_1event_1get_1coords.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1event_1type {
	static final MethodHandle MH = FFM.downcallOptional("gdk_event_get_event_type", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_event_get_event_type(long arg0) {
	try {
		int rc = 0;
		if (MH_gdk_1event_1get_1event_1type.MH != null) {
			rc = (int) MH_gdk_1event_1get_1event_1type.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1keycode {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_keycode", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static boolean gdk_event_get_keycode(long arg0, short[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1event_1get_1keycode.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1keyval {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_keyval", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static boolean gdk_event_get_keyval(long arg0, int[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1event_1get_1keyval.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1root_1coords {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_root_coords", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS));
}
public static boolean gdk_event_get_root_coords(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		int rc = (int) MH_gdk_1event_1get_1root_1coords.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1scroll_1deltas {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_scroll_deltas", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS));
}
public static boolean gdk_event_get_scroll_deltas(long arg0, double[] arg1, double[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		int rc = (int) MH_gdk_1event_1get_1scroll_1deltas.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1scroll_1direction {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_scroll_direction", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static boolean gdk_event_get_scroll_direction(long arg0, int[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1event_1get_1scroll_1direction.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1seat {
	static final MethodHandle MH = FFM.downcallOptional("gdk_event_get_seat", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_event_get_seat(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1event_1get_1seat.MH != null) {
			rc = (long) MH_gdk_1event_1get_1seat.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1state {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_state", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static boolean gdk_event_get_state(long arg0, int[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1event_1get_1state.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1time {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_time", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_event_get_time(long arg0) {
	try {
		int rc = (int) MH_gdk_1event_1get_1time.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1get_1window {
	static final MethodHandle MH = FFM.downcall("gdk_event_get_window", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_event_get_window(long arg0) {
	try {
		long rc = (long) MH_gdk_1event_1get_1window.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1handler_1set {
	static final MethodHandle MH = FFM.downcallOptional("gdk_event_handler_set", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static void gdk_event_handler_set(long arg0, long arg1, long arg2) {
	try {
		if (MH_gdk_1event_1handler_1set.MH != null) {
			MH_gdk_1event_1handler_1set.MH.invokeExact(arg0, arg1, arg2);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1new {
	static final MethodHandle MH = FFM.downcall("gdk_event_new", FunctionDescriptor.of(JAVA_LONG, JAVA_INT));
}
public static long gdk_event_new(int arg0) {
	try {
		long rc = (long) MH_gdk_1event_1new.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1peek {
	static final MethodHandle MH = FFM.downcall("gdk_event_peek", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_event_peek() {
	try {
		long rc = (long) MH_gdk_1event_1peek.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1put {
	static final MethodHandle MH = FFM.downcall("gdk_event_put", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_event_put(long arg0) {
	try {
		MH_gdk_1event_1put.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1event_1set_1device {
	static final MethodHandle MH = FFM.downcall("gdk_event_set_device", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void gdk_event_set_device(long arg0, long arg1) {
	try {
		MH_gdk_1event_1set_1device.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1get_1default_1root_1window {
	static final MethodHandle MH = FFM.downcall("gdk_get_default_root_window", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_get_default_root_window() {
	try {
		long rc = (long) MH_gdk_1get_1default_1root_1window.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1keymap_1get_1entries_1for_1keyval {
	static final MethodHandle MH = FFM.downcallOptional("gdk_keymap_get_entries_for_keyval", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG, JAVA_INT, ADDRESS, ADDRESS));
}
public static boolean gdk_keymap_get_entries_for_keyval(long arg0, int arg1, long[] arg2, int[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		byte rc = 0;
		if (MH_gdk_1keymap_1get_1entries_1for_1keyval.MH != null) {
			rc = (byte) MH_gdk_1keymap_1get_1entries_1for_1keyval.MH.invokeExact(arg0, arg1, lparg2, lparg3);
		}
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1keymap_1get_1for_1display {
	static final MethodHandle MH = FFM.downcallOptional("gdk_keymap_get_for_display", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_keymap_get_for_display(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1keymap_1get_1for_1display.MH != null) {
			rc = (long) MH_gdk_1keymap_1get_1for_1display.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1keymap_1translate_1keyboard_1state {
	static final MethodHandle MH = FFM.downcallOptional("gdk_keymap_translate_keyboard_state", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS, ADDRESS, ADDRESS));
}
public static boolean gdk_keymap_translate_keyboard_state(long arg0, int arg1, int arg2, int arg3, int[] arg4, int[] arg5, int[] arg6, int[] arg7) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		MemorySegment lparg5 = FFM.copyIn(arena, arg5);
		MemorySegment lparg6 = FFM.copyIn(arena, arg6);
		MemorySegment lparg7 = FFM.copyIn(arena, arg7);
		byte rc = 0;
		if (MH_gdk_1keymap_1translate_1keyboard_1state.MH != null) {
			rc = (byte) MH_gdk_1keymap_1translate_1keyboard_1state.MH.invokeExact(arg0, arg1, arg2, arg3, lparg4, lparg5, lparg6, lparg7);
		}
		FFM.copyOut(lparg7, arg7);
		FFM.copyOut(lparg6, arg6);
		FFM.copyOut(lparg5, arg5);
		FFM.copyOut(lparg4, arg4);
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1keyval_1name {
	static final MethodHandle MH = FFM.downcall("gdk_keyval_name", FunctionDescriptor.of(JAVA_LONG, JAVA_INT));
}
public static long gdk_keyval_name(int arg0) {
	try {
		long rc = (long) MH_gdk_1keyval_1name.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1keyval_1to_1lower {
	static final MethodHandle MH = FFM.downcall("gdk_keyval_to_lower", FunctionDescriptor.of(JAVA_INT, JAVA_INT));
}
public static long gdk_keyval_to_lower(long arg0) {
	try {
		int rc = (int) MH_gdk_1keyval_1to_1lower.MH.invokeExact((int) arg0);
		FFM.checkCallbackException();
		return Integer.toUnsignedLong(rc);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1keyval_1to_1unicode {
	static final MethodHandle MH = FFM.downcall("gdk_keyval_to_unicode", FunctionDescriptor.of(JAVA_INT, JAVA_INT));
}
public static long gdk_keyval_to_unicode(long arg0) {
	try {
		int rc = (int) MH_gdk_1keyval_1to_1unicode.MH.invokeExact((int) arg0);
		FFM.checkCallbackException();
		return Integer.toUnsignedLong(rc);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1monitor_1get_1geometry {
	static final MethodHandle MH = FFM.downcallOptional("gdk_monitor_get_geometry", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void gdk_monitor_get_geometry(long arg0, org.eclipse.swt.internal.gtk.GdkRectangle arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_SIZEOF, 16);
		if (MH_gdk_1monitor_1get_1geometry.MH != null) {
			MH_gdk_1monitor_1get_1geometry.MH.invokeExact(arg0, lparg1);
		}
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_read(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1monitor_1get_1scale_1factor {
	static final MethodHandle MH = FFM.downcallOptional("gdk_monitor_get_scale_factor", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_monitor_get_scale_factor(long arg0) {
	try {
		int rc = 0;
		if (MH_gdk_1monitor_1get_1scale_1factor.MH != null) {
			rc = (int) MH_gdk_1monitor_1get_1scale_1factor.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1monitor_1get_1workarea {
	static final MethodHandle MH = FFM.downcallOptional("gdk_monitor_get_workarea", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void gdk_monitor_get_workarea(long arg0, org.eclipse.swt.internal.gtk.GdkRectangle arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_SIZEOF, 16);
		if (MH_gdk_1monitor_1get_1workarea.MH != null) {
			MH_gdk_1monitor_1get_1workarea.MH.invokeExact(arg0, lparg1);
		}
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_read(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pango_1context_1get {
	static final MethodHandle MH = FFM.downcallOptional("gdk_pango_context_get", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_pango_context_get() {
	try {
		long rc = 0;
		if (MH_gdk_1pango_1context_1get.MH != null) {
			rc = (long) MH_gdk_1pango_1context_1get.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pango_1layout_1get_1clip_1region {
	static final MethodHandle MH = FFM.downcall("gdk_pango_layout_get_clip_region", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT));
}
public static long gdk_pango_layout_get_clip_region(long arg0, int arg1, int arg2, int[] arg3, int arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		long rc = (long) MH_gdk_1pango_1layout_1get_1clip_1region.MH.invokeExact(arg0, arg1, arg2, lparg3, arg4);
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1animation_1get_1iter {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_animation_get_iter", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_animation_get_iter(long arg0, long arg1) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1animation_1get_1iter.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1animation_1get_1static_1image {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_animation_get_static_image", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_animation_get_static_image(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1animation_1get_1static_1image.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1animation_1is_1static_1image {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_animation_is_static_image", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static boolean gdk_pixbuf_animation_is_static_image(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1animation_1is_1static_1image.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1animation_1iter_1advance {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_animation_iter_advance", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static boolean gdk_pixbuf_animation_iter_advance(long arg0, long arg1) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1animation_1iter_1advance.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1animation_1iter_1get_1delay_1time {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_animation_iter_get_delay_time", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_pixbuf_animation_iter_get_delay_time(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1animation_1iter_1get_1delay_1time.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1animation_1iter_1get_1pixbuf {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_animation_iter_get_pixbuf", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_animation_iter_get_pixbuf(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1animation_1iter_1get_1pixbuf.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1copy {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_copy", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_copy(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1copy.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1copy_1area {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_copy_area", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void gdk_pixbuf_copy_area(long arg0, int arg1, int arg2, int arg3, int arg4, long arg5, int arg6, int arg7) {
	try {
		MH_gdk_1pixbuf_1copy_1area.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1format_1get_1name {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_format_get_name", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_format_get_name(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1format_1get_1name.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1bits_1per_1sample {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_bits_per_sample", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_pixbuf_get_bits_per_sample(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1get_1bits_1per_1sample.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1from_1surface {
	static final MethodHandle MH = FFM.downcallOptional("gdk_pixbuf_get_from_surface", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static long gdk_pixbuf_get_from_surface(long arg0, int arg1, int arg2, int arg3, int arg4) {
	try {
		long rc = 0;
		if (MH_gdk_1pixbuf_1get_1from_1surface.MH != null) {
			rc = (long) MH_gdk_1pixbuf_1get_1from_1surface.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1from_1texture {
	static final MethodHandle MH = FFM.downcallOptional("gdk_pixbuf_get_from_texture", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_get_from_texture(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1pixbuf_1get_1from_1texture.MH != null) {
			rc = (long) MH_gdk_1pixbuf_1get_1from_1texture.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1from_1window {
	static final MethodHandle MH = FFM.downcallOptional("gdk_pixbuf_get_from_window", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static long gdk_pixbuf_get_from_window(long arg0, int arg1, int arg2, int arg3, int arg4) {
	try {
		long rc = 0;
		if (MH_gdk_1pixbuf_1get_1from_1window.MH != null) {
			rc = (long) MH_gdk_1pixbuf_1get_1from_1window.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1has_1alpha {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_has_alpha", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static boolean gdk_pixbuf_get_has_alpha(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1get_1has_1alpha.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1height {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_height", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_pixbuf_get_height(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1get_1height.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1n_1channels {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_n_channels", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_pixbuf_get_n_channels(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1get_1n_1channels.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1pixels {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_pixels", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_get_pixels(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1get_1pixels.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1rowstride {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_rowstride", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_pixbuf_get_rowstride(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1get_1rowstride.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1get_1width {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_get_width", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_pixbuf_get_width(long arg0) {
	try {
		int rc = (int) MH_gdk_1pixbuf_1get_1width.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1loader_1close {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_loader_close", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS));
}
public static boolean gdk_pixbuf_loader_close(long arg0, long[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1pixbuf_1loader_1close.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1loader_1get_1animation {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_loader_get_animation", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_loader_get_animation(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1loader_1get_1animation.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1loader_1get_1format {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_loader_get_format", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_loader_get_format(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1loader_1get_1format.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1loader_1get_1pixbuf {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_loader_get_pixbuf", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_loader_get_pixbuf(long arg0) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1loader_1get_1pixbuf.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1loader_1new {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_loader_new", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_pixbuf_loader_new() {
	try {
		long rc = (long) MH_gdk_1pixbuf_1loader_1new.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1loader_1write {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_loader_write", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS));
}
public static boolean gdk_pixbuf_loader_write(long arg0, long arg1, int arg2, long[] arg3) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		int rc = (int) MH_gdk_1pixbuf_1loader_1write.MH.invokeExact(arg0, arg1, (long) arg2, lparg3);
		FFM.copyOut(lparg3, arg3);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1new {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_new", FunctionDescriptor.of(JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static long gdk_pixbuf_new(int arg0, boolean arg1, int arg2, int arg3, int arg4) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1new.MH.invokeExact(arg0, (int) (arg1 ? 1 : 0), arg2, arg3, arg4);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1new_1from_1data {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_new_from_data", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static long gdk_pixbuf_new_from_data(long arg0, int arg1, boolean arg2, int arg3, int arg4, int arg5, int arg6, long arg7, long arg8) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1new_1from_1data.MH.invokeExact(arg0, arg1, (int) (arg2 ? 1 : 0), arg3, arg4, arg5, arg6, arg7, arg8);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1new_1from_1file {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_new_from_file", FunctionDescriptor.of(JAVA_LONG, ADDRESS, ADDRESS));
}
public static long gdk_pixbuf_new_from_file(byte[] arg0, long[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		long rc = (long) MH_gdk_1pixbuf_1new_1from_1file.MH.invokeExact(lparg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1save_1to_1bufferv {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_save_to_bufferv", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS));
}
public static boolean gdk_pixbuf_save_to_bufferv(long arg0, long[] arg1, long[] arg2, byte[] arg3, long[] arg4, long[] arg5, long[] arg6) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		MemorySegment lparg5 = FFM.copyIn(arena, arg5);
		MemorySegment lparg6 = FFM.copyIn(arena, arg6);
		int rc = (int) MH_gdk_1pixbuf_1save_1to_1bufferv.MH.invokeExact(arg0, lparg1, lparg2, lparg3, lparg4, lparg5, lparg6);
		FFM.copyOut(lparg6, arg6);
		FFM.copyOut(lparg5, arg5);
		FFM.copyOut(lparg4, arg4);
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1pixbuf_1scale_1simple {
	static final MethodHandle MH = FFM.downcall("gdk_pixbuf_scale_simple", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static long gdk_pixbuf_scale_simple(long arg0, int arg1, int arg2, int arg3) {
	try {
		long rc = (long) MH_gdk_1pixbuf_1scale_1simple.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1property_1get {
	static final MethodHandle MH = FFM.downcall("gdk_property_get", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_INT, ADDRESS, ADDRESS, ADDRESS, ADDRESS));
}
public static boolean gdk_property_get(long arg0, long arg1, long arg2, long arg3, long arg4, int arg5, long[] arg6, int[] arg7, int[] arg8, long[] arg9) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg6 = FFM.copyIn(arena, arg6);
		MemorySegment lparg7 = FFM.copyIn(arena, arg7);
		MemorySegment lparg8 = FFM.copyIn(arena, arg8);
		MemorySegment lparg9 = FFM.copyIn(arena, arg9);
		int rc = (int) MH_gdk_1property_1get.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, arg5, lparg6, lparg7, lparg8, lparg9);
		FFM.copyOut(lparg9, arg9);
		FFM.copyOut(lparg8, arg8);
		FFM.copyOut(lparg7, arg7);
		FFM.copyOut(lparg6, arg6);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1rgba_1free {
	static final MethodHandle MH = FFM.downcall("gdk_rgba_free", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_rgba_free(long arg0) {
	try {
		MH_gdk_1rgba_1free.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1rgba_1parse {
	static final MethodHandle MH = FFM.downcall("gdk_rgba_parse", FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS));
}
public static long gdk_rgba_parse(org.eclipse.swt.internal.gtk.GdkRGBA arg0, byte[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_write(lparg0, arg0);
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		int rc = (int) MH_gdk_1rgba_1parse.MH.invokeExact(lparg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		if (arg0 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_read(lparg0, arg0);
		FFM.checkCallbackException();
		return (long) rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1rgba_1to_1string {
	static final MethodHandle MH = FFM.downcall("gdk_rgba_to_string", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long gdk_rgba_to_string(org.eclipse.swt.internal.gtk.GdkRGBA arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = arg0 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_SIZEOF, 16);
		if (arg0 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_write(lparg0, arg0);
		long rc = (long) MH_gdk_1rgba_1to_1string.MH.invokeExact(lparg0);
		if (arg0 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRGBA_read(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1screen_1get_1default {
	static final MethodHandle MH = FFM.downcall("gdk_screen_get_default", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_screen_get_default() {
	try {
		long rc = (long) MH_gdk_1screen_1get_1default.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1screen_1get_1resolution {
	static final MethodHandle MH = FFM.downcall("gdk_screen_get_resolution", FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
}
public static double gdk_screen_get_resolution(long arg0) {
	try {
		double rc = (double) MH_gdk_1screen_1get_1resolution.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1screen_1get_1system_1visual {
	static final MethodHandle MH = FFM.downcall("gdk_screen_get_system_visual", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_screen_get_system_visual(long arg0) {
	try {
		long rc = (long) MH_gdk_1screen_1get_1system_1visual.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1screen_1height {
	static final MethodHandle MH = FFM.downcallOptional("gdk_screen_height", FunctionDescriptor.of(JAVA_INT));
}
public static int gdk_screen_height() {
	try {
		int rc = 0;
		if (MH_gdk_1screen_1height.MH != null) {
			rc = (int) MH_gdk_1screen_1height.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1screen_1is_1composited {
	static final MethodHandle MH = FFM.downcall("gdk_screen_is_composited", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static boolean gdk_screen_is_composited(long arg0) {
	try {
		int rc = (int) MH_gdk_1screen_1is_1composited.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1screen_1width {
	static final MethodHandle MH = FFM.downcallOptional("gdk_screen_width", FunctionDescriptor.of(JAVA_INT));
}
public static int gdk_screen_width() {
	try {
		int rc = 0;
		if (MH_gdk_1screen_1width.MH != null) {
			rc = (int) MH_gdk_1screen_1width.MH.invokeExact();
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1seat_1get_1keyboard {
	static final MethodHandle MH = FFM.downcallOptional("gdk_seat_get_keyboard", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_seat_get_keyboard(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1seat_1get_1keyboard.MH != null) {
			rc = (long) MH_gdk_1seat_1get_1keyboard.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1seat_1get_1pointer {
	static final MethodHandle MH = FFM.downcallOptional("gdk_seat_get_pointer", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_seat_get_pointer(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1seat_1get_1pointer.MH != null) {
			rc = (long) MH_gdk_1seat_1get_1pointer.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1seat_1grab {
	static final MethodHandle MH = FFM.downcallOptional("gdk_seat_grab", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_BYTE, JAVA_LONG, JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static int gdk_seat_grab(long arg0, long arg1, int arg2, boolean arg3, long arg4, long arg5, long arg6, long arg7) {
	try {
		int rc = 0;
		if (MH_gdk_1seat_1grab.MH != null) {
			rc = (int) MH_gdk_1seat_1grab.MH.invokeExact(arg0, arg1, arg2, (byte) (arg3 ? 1 : 0), arg4, arg5, arg6, arg7);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1seat_1ungrab {
	static final MethodHandle MH = FFM.downcallOptional("gdk_seat_ungrab", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_seat_ungrab(long arg0) {
	try {
		if (MH_gdk_1seat_1ungrab.MH != null) {
			MH_gdk_1seat_1ungrab.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1selection_1owner_1get {
	static final MethodHandle MH = FFM.downcall("gdk_selection_owner_get", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_selection_owner_get(long arg0) {
	try {
		MH_gdk_1selection_1owner_1get.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1selection_1owner_1set {
	static final MethodHandle MH = FFM.downcall("gdk_selection_owner_set", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void gdk_selection_owner_set(long arg0, long arg1, int arg2, boolean arg3) {
	try {
		MH_gdk_1selection_1owner_1set.MH.invokeExact(arg0, arg1, arg2, (int) (arg3 ? 1 : 0));
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1set_1program_1class {
	static final MethodHandle MH = FFM.downcallOptional("gdk_set_program_class", FunctionDescriptor.ofVoid(ADDRESS));
}
public static void gdk_set_program_class(byte[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		if (MH_gdk_1set_1program_1class.MH != null) {
			MH_gdk_1set_1program_1class.MH.invokeExact(lparg0);
		}
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1surface_1new_1toplevel {
	static final MethodHandle MH = FFM.downcallOptional("gdk_surface_new_toplevel", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_surface_new_toplevel(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1surface_1new_1toplevel.MH != null) {
			rc = (long) MH_gdk_1surface_1new_1toplevel.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1text_1property_1to_1utf8_1list_1for_1display {
	static final MethodHandle MH = FFM.downcall("gdk_text_property_to_utf8_list_for_display", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_LONG, JAVA_INT, ADDRESS));
}
public static int gdk_text_property_to_utf8_list_for_display(long arg0, long arg1, int arg2, long arg3, int arg4, long[] arg5) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg5 = FFM.copyIn(arena, arg5);
		int rc = (int) MH_gdk_1text_1property_1to_1utf8_1list_1for_1display.MH.invokeExact(arg0, arg1, arg2, arg3, arg4, lparg5);
		FFM.copyOut(lparg5, arg5);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1threads_1add_1idle {
	static final MethodHandle MH = FFM.downcall("gdk_threads_add_idle", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static int gdk_threads_add_idle(long arg0, long arg1) {
	try {
		int rc = (int) MH_gdk_1threads_1add_1idle.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1threads_1add_1timeout {
	static final MethodHandle MH = FFM.downcall("gdk_threads_add_timeout", FunctionDescriptor.of(JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_LONG));
}
public static int gdk_threads_add_timeout(int arg0, long arg1, long arg2) {
	try {
		int rc = (int) MH_gdk_1threads_1add_1timeout.MH.invokeExact(arg0, arg1, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1threads_1enter {
	static final MethodHandle MH = FFM.downcall("gdk_threads_enter", FunctionDescriptor.ofVoid());
}
public static void gdk_threads_enter() {
	try {
		MH_gdk_1threads_1enter.MH.invokeExact();
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1threads_1init {
	static final MethodHandle MH = FFM.downcall("gdk_threads_init", FunctionDescriptor.ofVoid());
}
public static void gdk_threads_init() {
	try {
		MH_gdk_1threads_1init.MH.invokeExact();
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1threads_1leave {
	static final MethodHandle MH = FFM.downcall("gdk_threads_leave", FunctionDescriptor.ofVoid());
}
public static void gdk_threads_leave() {
	try {
		MH_gdk_1threads_1leave.MH.invokeExact();
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1toplevel_1layout_1new {
	static final MethodHandle MH = FFM.downcallOptional("gdk_toplevel_layout_new", FunctionDescriptor.of(JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static long gdk_toplevel_layout_new(int arg0, int arg1) {
	try {
		long rc = 0;
		if (MH_gdk_1toplevel_1layout_1new.MH != null) {
			rc = (long) MH_gdk_1toplevel_1layout_1new.MH.invokeExact(arg0, arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1toplevel_1present {
	static final MethodHandle MH = FFM.downcallOptional("gdk_toplevel_present", FunctionDescriptor.of(JAVA_BYTE, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_LONG));
}
public static boolean gdk_toplevel_present(long arg0, int arg1, int arg2, long arg3) {
	try {
		byte rc = 0;
		if (MH_gdk_1toplevel_1present.MH != null) {
			rc = (byte) MH_gdk_1toplevel_1present.MH.invokeExact(arg0, arg1, arg2, arg3);
		}
		FFM.checkCallbackException();
		return (rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1unicode_1to_1keyval {
	static final MethodHandle MH = FFM.downcall("gdk_unicode_to_keyval", FunctionDescriptor.of(JAVA_INT, JAVA_INT));
}
public static int gdk_unicode_to_keyval(int arg0) {
	try {
		int rc = (int) MH_gdk_1unicode_1to_1keyval.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1utf8_1to_1string_1target {
	static final MethodHandle MH = FFM.downcallOptional("gdk_utf8_to_string_target", FunctionDescriptor.of(JAVA_LONG, ADDRESS));
}
public static long gdk_utf8_to_string_target(byte[] arg0) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg0 = FFM.copyIn(arena, arg0);
		long rc = 0;
		if (MH_gdk_1utf8_1to_1string_1target.MH != null) {
			rc = (long) MH_gdk_1utf8_1to_1string_1target.MH.invokeExact(lparg0);
		}
		FFM.copyOut(lparg0, arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1visual_1get_1depth {
	static final MethodHandle MH = FFM.downcall("gdk_visual_get_depth", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_visual_get_depth(long arg0) {
	try {
		int rc = (int) MH_gdk_1visual_1get_1depth.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1create_1similar_1surface {
	static final MethodHandle MH = FFM.downcall("gdk_window_create_similar_surface", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static long gdk_window_create_similar_surface(long arg0, int arg1, int arg2, int arg3) {
	try {
		long rc = (long) MH_gdk_1window_1create_1similar_1surface.MH.invokeExact(arg0, arg1, arg2, arg3);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1destroy {
	static final MethodHandle MH = FFM.downcall("gdk_window_destroy", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_window_destroy(long arg0) {
	try {
		MH_gdk_1window_1destroy.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1focus {
	static final MethodHandle MH = FFM.downcall("gdk_window_focus", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void gdk_window_focus(long arg0, int arg1) {
	try {
		MH_gdk_1window_1focus.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1children {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_children", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_window_get_children(long arg0) {
	try {
		long rc = (long) MH_gdk_1window_1get_1children.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1device_1position {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_device_position", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS, ADDRESS, ADDRESS));
}
public static long gdk_window_get_device_position(long arg0, long arg1, int[] arg2, int[] arg3, int[] arg4) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		long rc = (long) MH_gdk_1window_1get_1device_1position.MH.invokeExact(arg0, arg1, lparg2, lparg3, lparg4);
		FFM.copyOut(lparg4, arg4);
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1display {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_display", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_window_get_display(long arg0) {
	try {
		long rc = (long) MH_gdk_1window_1get_1display.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1events {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_events", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_window_get_events(long arg0) {
	try {
		int rc = (int) MH_gdk_1window_1get_1events.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1frame_1extents {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_frame_extents", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void gdk_window_get_frame_extents(long arg0, org.eclipse.swt.internal.gtk.GdkRectangle arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_SIZEOF, 16);
		MH_gdk_1window_1get_1frame_1extents.MH.invokeExact(arg0, lparg1);
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_read(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1height {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_height", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_window_get_height(long arg0) {
	try {
		int rc = (int) MH_gdk_1window_1get_1height.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1origin {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_origin", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS));
}
public static int gdk_window_get_origin(long arg0, int[] arg1, int[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		int rc = (int) MH_gdk_1window_1get_1origin.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1parent {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_parent", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_window_get_parent(long arg0) {
	try {
		long rc = (long) MH_gdk_1window_1get_1parent.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1root_1origin {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_root_origin", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, ADDRESS));
}
public static void gdk_window_get_root_origin(long arg0, int[] arg1, int[] arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MH_gdk_1window_1get_1root_1origin.MH.invokeExact(arg0, lparg1, lparg2);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1state {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_state", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_window_get_state(long arg0) {
	try {
		int rc = (int) MH_gdk_1window_1get_1state.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1user_1data {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_user_data", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS));
}
public static void gdk_window_get_user_data(long arg0, long[] arg1) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MH_gdk_1window_1get_1user_1data.MH.invokeExact(arg0, lparg1);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1visible_1region {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_visible_region", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_window_get_visible_region(long arg0) {
	try {
		long rc = (long) MH_gdk_1window_1get_1visible_1region.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1get_1width {
	static final MethodHandle MH = FFM.downcall("gdk_window_get_width", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
}
public static int gdk_window_get_width(long arg0) {
	try {
		int rc = (int) MH_gdk_1window_1get_1width.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1hide {
	static final MethodHandle MH = FFM.downcall("gdk_window_hide", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_window_hide(long arg0) {
	try {
		MH_gdk_1window_1hide.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1invalidate_1rect {
	static final MethodHandle MH = FFM.downcall("gdk_window_invalidate_rect", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
}
public static void gdk_window_invalidate_rect(long arg0, org.eclipse.swt.internal.gtk.GdkRectangle arg1, boolean arg2) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = arg1 == null ? MemorySegment.NULL : arena.allocate(org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_SIZEOF, 16);
		if (arg1 != null) org.eclipse.swt.internal.gtk.Structs_FFM.GdkRectangle_write(lparg1, arg1);
		MH_gdk_1window_1invalidate_1rect.MH.invokeExact(arg0, lparg1, (int) (arg2 ? 1 : 0));
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1invalidate_1region {
	static final MethodHandle MH = FFM.downcall("gdk_window_invalidate_region", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT));
}
public static void gdk_window_invalidate_region(long arg0, long arg1, boolean arg2) {
	try {
		MH_gdk_1window_1invalidate_1region.MH.invokeExact(arg0, arg1, (int) (arg2 ? 1 : 0));
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1lower {
	static final MethodHandle MH = FFM.downcall("gdk_window_lower", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_window_lower(long arg0) {
	try {
		MH_gdk_1window_1lower.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1move {
	static final MethodHandle MH = FFM.downcall("gdk_window_move", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void gdk_window_move(long arg0, int arg1, int arg2) {
	try {
		MH_gdk_1window_1move.MH.invokeExact(arg0, arg1, arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1move_1resize {
	static final MethodHandle MH = FFM.downcall("gdk_window_move_resize", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));
}
public static void gdk_window_move_resize(long arg0, int arg1, int arg2, int arg3, int arg4) {
	try {
		MH_gdk_1window_1move_1resize.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1raise {
	static final MethodHandle MH = FFM.downcall("gdk_window_raise", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_window_raise(long arg0) {
	try {
		MH_gdk_1window_1raise.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1resize {
	static final MethodHandle MH = FFM.downcall("gdk_window_resize", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
}
public static void gdk_window_resize(long arg0, int arg1, int arg2) {
	try {
		MH_gdk_1window_1resize.MH.invokeExact(arg0, arg1, arg2);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1restack {
	static final MethodHandle MH = FFM.downcall("gdk_window_restack", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT));
}
public static void gdk_window_restack(long arg0, long arg1, boolean arg2) {
	try {
		MH_gdk_1window_1restack.MH.invokeExact(arg0, arg1, (int) (arg2 ? 1 : 0));
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1set_1cursor {
	static final MethodHandle MH = FFM.downcall("gdk_window_set_cursor", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void gdk_window_set_cursor(long arg0, long arg1) {
	try {
		MH_gdk_1window_1set_1cursor.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1set_1decorations {
	static final MethodHandle MH = FFM.downcall("gdk_window_set_decorations", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void gdk_window_set_decorations(long arg0, int arg1) {
	try {
		MH_gdk_1window_1set_1decorations.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1set_1events {
	static final MethodHandle MH = FFM.downcall("gdk_window_set_events", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void gdk_window_set_events(long arg0, int arg1) {
	try {
		MH_gdk_1window_1set_1events.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1set_1functions {
	static final MethodHandle MH = FFM.downcall("gdk_window_set_functions", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void gdk_window_set_functions(long arg0, int arg1) {
	try {
		MH_gdk_1window_1set_1functions.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1set_1override_1redirect {
	static final MethodHandle MH = FFM.downcall("gdk_window_set_override_redirect", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
}
public static void gdk_window_set_override_redirect(long arg0, boolean arg1) {
	try {
		MH_gdk_1window_1set_1override_1redirect.MH.invokeExact(arg0, (int) (arg1 ? 1 : 0));
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1set_1user_1data {
	static final MethodHandle MH = FFM.downcall("gdk_window_set_user_data", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
}
public static void gdk_window_set_user_data(long arg0, long arg1) {
	try {
		MH_gdk_1window_1set_1user_1data.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1show {
	static final MethodHandle MH = FFM.downcall("gdk_window_show", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_window_show(long arg0) {
	try {
		MH_gdk_1window_1show.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1window_1show_1unraised {
	static final MethodHandle MH = FFM.downcall("gdk_window_show_unraised", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_window_show_unraised(long arg0) {
	try {
		MH_gdk_1window_1show_1unraised.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1display_1error_1trap_1pop_1ignored {
	static final MethodHandle MH = FFM.downcall("gdk_x11_display_error_trap_pop_ignored", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_x11_display_error_trap_pop_ignored(long arg0) {
	try {
		MH_gdk_1x11_1display_1error_1trap_1pop_1ignored.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1display_1error_1trap_1push {
	static final MethodHandle MH = FFM.downcall("gdk_x11_display_error_trap_push", FunctionDescriptor.ofVoid(JAVA_LONG));
}
public static void gdk_x11_display_error_trap_push(long arg0) {
	try {
		MH_gdk_1x11_1display_1error_1trap_1push.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1display_1get_1default_1group {
	static final MethodHandle MH = FFM.downcallOptional("gdk_x11_display_get_default_group", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_x11_display_get_default_group(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1x11_1display_1get_1default_1group.MH != null) {
			rc = (long) MH_gdk_1x11_1display_1get_1default_1group.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1display_1get_1xdisplay {
	static final MethodHandle MH = FFM.downcall("gdk_x11_display_get_xdisplay", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_x11_display_get_xdisplay(long arg0) {
	try {
		long rc = (long) MH_gdk_1x11_1display_1get_1xdisplay.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1display_1utf8_1to_1compound_1text {
	static final MethodHandle MH = FFM.downcall("gdk_x11_display_utf8_to_compound_text", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS));
}
public static boolean gdk_x11_display_utf8_to_compound_text(long arg0, byte[] arg1, long[] arg2, int[] arg3, long[] arg4, int[] arg5) {
	try (Arena arena = Arena.ofConfined()) {
		MemorySegment lparg1 = FFM.copyIn(arena, arg1);
		MemorySegment lparg2 = FFM.copyIn(arena, arg2);
		MemorySegment lparg3 = FFM.copyIn(arena, arg3);
		MemorySegment lparg4 = FFM.copyIn(arena, arg4);
		MemorySegment lparg5 = FFM.copyIn(arena, arg5);
		int rc = (int) MH_gdk_1x11_1display_1utf8_1to_1compound_1text.MH.invokeExact(arg0, lparg1, lparg2, lparg3, lparg4, lparg5);
		FFM.copyOut(lparg5, arg5);
		FFM.copyOut(lparg4, arg4);
		FFM.copyOut(lparg3, arg3);
		FFM.copyOut(lparg2, arg2);
		FFM.copyOut(lparg1, arg1);
		FFM.checkCallbackException();
		return ((byte) rc != 0);
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1get_1default_1xdisplay {
	static final MethodHandle MH = FFM.downcall("gdk_x11_get_default_xdisplay", FunctionDescriptor.of(JAVA_LONG));
}
public static long gdk_x11_get_default_xdisplay() {
	try {
		long rc = (long) MH_gdk_1x11_1get_1default_1xdisplay.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1screen_1get_1window_1manager_1name {
	static final MethodHandle MH = FFM.downcallOptional("gdk_x11_screen_get_window_manager_name", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_x11_screen_get_window_manager_name(long arg0) {
	try {
		long rc = 0;
		if (MH_gdk_1x11_1screen_1get_1window_1manager_1name.MH != null) {
			rc = (long) MH_gdk_1x11_1screen_1get_1window_1manager_1name.MH.invokeExact(arg0);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1screen_1lookup_1visual {
	static final MethodHandle MH = FFM.downcallOptional("gdk_x11_screen_lookup_visual", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static long gdk_x11_screen_lookup_visual(long arg0, int arg1) {
	try {
		long rc = 0;
		if (MH_gdk_1x11_1screen_1lookup_1visual.MH != null) {
			rc = (long) MH_gdk_1x11_1screen_1lookup_1visual.MH.invokeExact(arg0, (long) arg1);
		}
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1window_1get_1xid {
	static final MethodHandle MH = FFM.downcall("gdk_x11_window_get_xid", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
}
public static long gdk_x11_window_get_xid(long arg0) {
	try {
		long rc = (long) MH_gdk_1x11_1window_1get_1xid.MH.invokeExact(arg0);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_gdk_1x11_1window_1lookup_1for_1display {
	static final MethodHandle MH = FFM.downcall("gdk_x11_window_lookup_for_display", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
}
public static long gdk_x11_window_lookup_for_display(long arg0, long arg1) {
	try {
		long rc = (long) MH_gdk_1x11_1window_1lookup_1for_1display.MH.invokeExact(arg0, arg1);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
