/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.gtk;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Graphene_FFM {

private static final class MH_graphene_1rect_1alloc {
	static final MethodHandle MH = FFM.gtk4Only(FFM.downcall("graphene_rect_alloc", FunctionDescriptor.of(JAVA_LONG)), "graphene_rect_alloc");
}
public static long graphene_rect_alloc() {
	try {
		long rc = (long) MH_graphene_1rect_1alloc.MH.invokeExact();
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_graphene_1rect_1free {
	static final MethodHandle MH = FFM.gtk4Only(FFM.downcall("graphene_rect_free", FunctionDescriptor.ofVoid(JAVA_LONG)), "graphene_rect_free");
}
public static void graphene_rect_free(long arg0) {
	try {
		MH_graphene_1rect_1free.MH.invokeExact(arg0);
		FFM.checkCallbackException();
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

private static final class MH_graphene_1rect_1init {
	static final MethodHandle MH = FFM.gtk4Only(FFM.downcall("graphene_rect_init", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT)), "graphene_rect_init");
}
public static long graphene_rect_init(long arg0, float arg1, float arg2, float arg3, float arg4) {
	try {
		long rc = (long) MH_graphene_1rect_1init.MH.invokeExact(arg0, arg1, arg2, arg3, arg4);
		FFM.checkCallbackException();
		return rc;
	} catch (Throwable e) {
		throw FFM.rethrow(e);
	}
}

}
