/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/* Note: This file was auto-generated by org.eclipse.swt.tools.internal.FFMGenerator */
/* DO NOT EDIT - your changes will be lost. */
package org.eclipse.swt.internal.gtk;

import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;

import org.eclipse.swt.internal.ffm.*;

@SuppressWarnings("all")
public final class Structs_FFM {

public static final long GObjectClass_SIZEOF = 136L;

public static void GObjectClass_read(MemorySegment s, org.eclipse.swt.internal.gtk.GObjectClass o) {
	o.constructor = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.set_property = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.get_property = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.dispose = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.finalize = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.dispatch_properties_changed = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.notify = s.get(JAVA_LONG_UNALIGNED, 64L);
}

public static void GObjectClass_write(MemorySegment s, org.eclipse.swt.internal.gtk.GObjectClass o) {
	s.set(JAVA_LONG_UNALIGNED, 16L, o.constructor);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.set_property);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.get_property);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.dispose);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.finalize);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.dispatch_properties_changed);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.notify);
}

public static final long GTypeInfo_SIZEOF = 72L;

public static void GTypeInfo_read(MemorySegment s, org.eclipse.swt.internal.gtk.GTypeInfo o) {
	o.class_size = s.get(JAVA_SHORT_UNALIGNED, 0L);
	o.base_init = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.base_finalize = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.class_init = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.class_finalize = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.class_data = s.get(JAVA_LONG_UNALIGNED, 40L);
	o.instance_size = s.get(JAVA_SHORT_UNALIGNED, 48L);
	o.n_preallocs = s.get(JAVA_SHORT_UNALIGNED, 50L);
	o.instance_init = s.get(JAVA_LONG_UNALIGNED, 56L);
	o.value_table = s.get(JAVA_LONG_UNALIGNED, 64L);
}

public static void GTypeInfo_write(MemorySegment s, org.eclipse.swt.internal.gtk.GTypeInfo o) {
	s.set(JAVA_SHORT_UNALIGNED, 0L, o.class_size);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.base_init);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.base_finalize);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.class_init);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.class_finalize);
	s.set(JAVA_LONG_UNALIGNED, 40L, o.class_data);
	s.set(JAVA_SHORT_UNALIGNED, 48L, o.instance_size);
	s.set(JAVA_SHORT_UNALIGNED, 50L, o.n_preallocs);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.instance_init);
	s.set(JAVA_LONG_UNALIGNED, 64L, o.value_table);
}

public static final long GdkKeymapKey_SIZEOF = 12L;

public static void GdkKeymapKey_read(MemorySegment s, org.eclipse.swt.internal.gtk.GdkKeymapKey o) {
	o.keycode = s.get(JAVA_INT_UNALIGNED, 0L);
	o.group = s.get(JAVA_INT_UNALIGNED, 4L);
	o.level = s.get(JAVA_INT_UNALIGNED, 8L);
}

public static void GdkKeymapKey_write(MemorySegment s, org.eclipse.swt.internal.gtk.GdkKeymapKey o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.keycode);
	s.set(JAVA_INT_UNALIGNED, 4L, o.group);
	s.set(JAVA_INT_UNALIGNED, 8L, o.level);
}

public static final long GdkRGBA_SIZEOF = 32L;

public static void GdkRGBA_read(MemorySegment s, org.eclipse.swt.internal.gtk.GdkRGBA o) {
	o.red = s.get(JAVA_DOUBLE_UNALIGNED, 0L);
	o.green = s.get(JAVA_DOUBLE_UNALIGNED, 8L);
	o.blue = s.get(JAVA_DOUBLE_UNALIGNED, 16L);
	o.alpha = s.get(JAVA_DOUBLE_UNALIGNED, 24L);
}

public static void GdkRGBA_write(MemorySegment s, org.eclipse.swt.internal.gtk.GdkRGBA o) {
	s.set(JAVA_DOUBLE_UNALIGNED, 0L, o.red);
	s.set(JAVA_DOUBLE_UNALIGNED, 8L, o.green);
	s.set(JAVA_DOUBLE_UNALIGNED, 16L, o.blue);
	s.set(JAVA_DOUBLE_UNALIGNED, 24L, o.alpha);
}

public static final long GdkRectangle_SIZEOF = 16L;

public static void GdkRectangle_read(MemorySegment s, org.eclipse.swt.internal.gtk.GdkRectangle o) {
	o.x = s.get(JAVA_INT_UNALIGNED, 0L);
	o.y = s.get(JAVA_INT_UNALIGNED, 4L);
	o.width = s.get(JAVA_INT_UNALIGNED, 8L);
	o.height = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void GdkRectangle_write(MemorySegment s, org.eclipse.swt.internal.gtk.GdkRectangle o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.x);
	s.set(JAVA_INT_UNALIGNED, 4L, o.y);
	s.set(JAVA_INT_UNALIGNED, 8L, o.width);
	s.set(JAVA_INT_UNALIGNED, 12L, o.height);
}

public static final long GtkAllocation_SIZEOF = 16L;

public static void GtkAllocation_read(MemorySegment s, org.eclipse.swt.internal.gtk.GtkAllocation o) {
	o.x = s.get(JAVA_INT_UNALIGNED, 0L);
	o.y = s.get(JAVA_INT_UNALIGNED, 4L);
	o.width = s.get(JAVA_INT_UNALIGNED, 8L);
	o.height = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void GtkAllocation_write(MemorySegment s, org.eclipse.swt.internal.gtk.GtkAllocation o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.x);
	s.set(JAVA_INT_UNALIGNED, 4L, o.y);
	s.set(JAVA_INT_UNALIGNED, 8L, o.width);
	s.set(JAVA_INT_UNALIGNED, 12L, o.height);
}

public static final long GtkBorder_SIZEOF = 8L;

public static void GtkBorder_read(MemorySegment s, org.eclipse.swt.internal.gtk.GtkBorder o) {
	o.left = (int) s.get(JAVA_SHORT_UNALIGNED, 0L);
	o.right = (int) s.get(JAVA_SHORT_UNALIGNED, 2L);
	o.top = (int) s.get(JAVA_SHORT_UNALIGNED, 4L);
	o.bottom = (int) s.get(JAVA_SHORT_UNALIGNED, 6L);
}

public static void GtkBorder_write(MemorySegment s, org.eclipse.swt.internal.gtk.GtkBorder o) {
	s.set(JAVA_SHORT_UNALIGNED, 0L, (short) o.left);
	s.set(JAVA_SHORT_UNALIGNED, 2L, (short) o.right);
	s.set(JAVA_SHORT_UNALIGNED, 4L, (short) o.top);
	s.set(JAVA_SHORT_UNALIGNED, 6L, (short) o.bottom);
}

public static final long GtkCellRendererClass_SIZEOF = 264L;

public static void GtkCellRendererClass_read(MemorySegment s, org.eclipse.swt.internal.gtk.GtkCellRendererClass o) {
	o.render = s.get(JAVA_LONG_UNALIGNED, 192L);
	o.get_preferred_width = s.get(JAVA_LONG_UNALIGNED, 144L);
}

public static void GtkCellRendererClass_write(MemorySegment s, org.eclipse.swt.internal.gtk.GtkCellRendererClass o) {
	s.set(JAVA_LONG_UNALIGNED, 192L, o.render);
	s.set(JAVA_LONG_UNALIGNED, 144L, o.get_preferred_width);
}

public static final long GtkRequisition_SIZEOF = 8L;

public static void GtkRequisition_read(MemorySegment s, org.eclipse.swt.internal.gtk.GtkRequisition o) {
	o.width = s.get(JAVA_INT_UNALIGNED, 0L);
	o.height = s.get(JAVA_INT_UNALIGNED, 4L);
}

public static void GtkRequisition_write(MemorySegment s, org.eclipse.swt.internal.gtk.GtkRequisition o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.width);
	s.set(JAVA_INT_UNALIGNED, 4L, o.height);
}

public static final long GtkWidgetClass_SIZEOF = 824L;

public static void GtkWidgetClass_read(MemorySegment s, org.eclipse.swt.internal.gtk.GtkWidgetClass o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.GObjectClass_read(s, o);
	o.map = s.get(JAVA_LONG_UNALIGNED, 184L);
	o.size_allocate = s.get(JAVA_LONG_UNALIGNED, 216L);
}

public static void GtkWidgetClass_write(MemorySegment s, org.eclipse.swt.internal.gtk.GtkWidgetClass o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.GObjectClass_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 184L, o.map);
	s.set(JAVA_LONG_UNALIGNED, 216L, o.size_allocate);
}

public static final long PangoAttrColor_SIZEOF = 24L;

public static void PangoAttrColor_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoAttrColor o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.PangoAttribute_read(s, o);
	o.color_red = s.get(JAVA_SHORT_UNALIGNED, 16L);
	o.color_green = s.get(JAVA_SHORT_UNALIGNED, 18L);
	o.color_blue = s.get(JAVA_SHORT_UNALIGNED, 20L);
}

public static void PangoAttrColor_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoAttrColor o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.PangoAttribute_write(s, o);
	s.set(JAVA_SHORT_UNALIGNED, 16L, o.color_red);
	s.set(JAVA_SHORT_UNALIGNED, 18L, o.color_green);
	s.set(JAVA_SHORT_UNALIGNED, 20L, o.color_blue);
}

public static final long PangoAttrInt_SIZEOF = 24L;

public static void PangoAttrInt_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoAttrInt o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.PangoAttribute_read(s, o);
	o.value = s.get(JAVA_INT_UNALIGNED, 16L);
}

public static void PangoAttrInt_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoAttrInt o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.PangoAttribute_write(s, o);
	s.set(JAVA_INT_UNALIGNED, 16L, o.value);
}

public static final long PangoAttribute_SIZEOF = 16L;

public static void PangoAttribute_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoAttribute o) {
	o.klass = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.start_index = s.get(JAVA_INT_UNALIGNED, 8L);
	o.end_index = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void PangoAttribute_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoAttribute o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.klass);
	s.set(JAVA_INT_UNALIGNED, 8L, o.start_index);
	s.set(JAVA_INT_UNALIGNED, 12L, o.end_index);
}

public static final long PangoItem_SIZEOF = 64L;

public static void PangoItem_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoItem o) {
	o.offset = s.get(JAVA_INT_UNALIGNED, 0L);
	o.length = s.get(JAVA_INT_UNALIGNED, 4L);
	o.num_chars = s.get(JAVA_INT_UNALIGNED, 8L);
	o.analysis_shape_engine = s.get(JAVA_LONG_UNALIGNED, 16L);
	o.analysis_lang_engine = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.analysis_font = s.get(JAVA_LONG_UNALIGNED, 32L);
	o.analysis_level = s.get(JAVA_BYTE, 40L);
	o.analysis_language = s.get(JAVA_LONG_UNALIGNED, 48L);
	o.analysis_extra_attrs = s.get(JAVA_LONG_UNALIGNED, 56L);
}

public static void PangoItem_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoItem o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.offset);
	s.set(JAVA_INT_UNALIGNED, 4L, o.length);
	s.set(JAVA_INT_UNALIGNED, 8L, o.num_chars);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.analysis_shape_engine);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.analysis_lang_engine);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.analysis_font);
	s.set(JAVA_BYTE, 40L, o.analysis_level);
	s.set(JAVA_LONG_UNALIGNED, 48L, o.analysis_language);
	s.set(JAVA_LONG_UNALIGNED, 56L, o.analysis_extra_attrs);
}

public static final long PangoLayoutLine_SIZEOF = 32L;

public static void PangoLayoutLine_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoLayoutLine o) {
	o.layout = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.start_index = s.get(JAVA_INT_UNALIGNED, 8L);
	o.length = s.get(JAVA_INT_UNALIGNED, 12L);
	o.runs = s.get(JAVA_LONG_UNALIGNED, 16L);
}

public static void PangoLayoutLine_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoLayoutLine o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.layout);
	s.set(JAVA_INT_UNALIGNED, 8L, o.start_index);
	s.set(JAVA_INT_UNALIGNED, 12L, o.length);
	s.set(JAVA_LONG_UNALIGNED, 16L, o.runs);
}

public static final long PangoLayoutRun_SIZEOF = 32L;

public static void PangoLayoutRun_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoLayoutRun o) {
	o.item = s.get(JAVA_LONG_UNALIGNED, 0L);
	o.glyphs = s.get(JAVA_LONG_UNALIGNED, 8L);
}

public static void PangoLayoutRun_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoLayoutRun o) {
	s.set(JAVA_LONG_UNALIGNED, 0L, o.item);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.glyphs);
}

public static final long PangoLogAttr_SIZEOF = 4L;

public static void PangoLogAttr_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoLogAttr o) {
	o.is_line_break = (FFM.getBits(s, 0L, 1) & 1) != 0;
	o.is_mandatory_break = (FFM.getBits(s, 1L, 1) & 1) != 0;
	o.is_char_break = (FFM.getBits(s, 2L, 1) & 1) != 0;
	o.is_white = (FFM.getBits(s, 3L, 1) & 1) != 0;
	o.is_cursor_position = (FFM.getBits(s, 4L, 1) & 1) != 0;
	o.is_word_start = (FFM.getBits(s, 5L, 1) & 1) != 0;
	o.is_word_end = (FFM.getBits(s, 6L, 1) & 1) != 0;
	o.is_sentence_boundary = (FFM.getBits(s, 7L, 1) & 1) != 0;
	o.is_sentence_start = (FFM.getBits(s, 8L, 1) & 1) != 0;
	o.is_sentence_end = (FFM.getBits(s, 9L, 1) & 1) != 0;
}

public static void PangoLogAttr_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoLogAttr o) {
	FFM.setBits(s, 0L, 1, (long) (o.is_line_break ? 1 : 0));
	FFM.setBits(s, 1L, 1, (long) (o.is_mandatory_break ? 1 : 0));
	FFM.setBits(s, 2L, 1, (long) (o.is_char_break ? 1 : 0));
	FFM.setBits(s, 3L, 1, (long) (o.is_white ? 1 : 0));
	FFM.setBits(s, 4L, 1, (long) (o.is_cursor_position ? 1 : 0));
	FFM.setBits(s, 5L, 1, (long) (o.is_word_start ? 1 : 0));
	FFM.setBits(s, 6L, 1, (long) (o.is_word_end ? 1 : 0));
	FFM.setBits(s, 7L, 1, (long) (o.is_sentence_boundary ? 1 : 0));
	FFM.setBits(s, 8L, 1, (long) (o.is_sentence_start ? 1 : 0));
	FFM.setBits(s, 9L, 1, (long) (o.is_sentence_end ? 1 : 0));
}

public static final long PangoRectangle_SIZEOF = 16L;

public static void PangoRectangle_read(MemorySegment s, org.eclipse.swt.internal.gtk.PangoRectangle o) {
	o.x = s.get(JAVA_INT_UNALIGNED, 0L);
	o.y = s.get(JAVA_INT_UNALIGNED, 4L);
	o.width = s.get(JAVA_INT_UNALIGNED, 8L);
	o.height = s.get(JAVA_INT_UNALIGNED, 12L);
}

public static void PangoRectangle_write(MemorySegment s, org.eclipse.swt.internal.gtk.PangoRectangle o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.x);
	s.set(JAVA_INT_UNALIGNED, 4L, o.y);
	s.set(JAVA_INT_UNALIGNED, 8L, o.width);
	s.set(JAVA_INT_UNALIGNED, 12L, o.height);
}

public static final long XAnyEvent_SIZEOF = 40L;

public static void XAnyEvent_read(MemorySegment s, org.eclipse.swt.internal.gtk.XAnyEvent o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.XEvent_read(s, o);
	o.serial = s.get(JAVA_LONG_UNALIGNED, 8L);
	o.send_event = s.get(JAVA_INT_UNALIGNED, 16L);
	o.display = s.get(JAVA_LONG_UNALIGNED, 24L);
	o.window = s.get(JAVA_LONG_UNALIGNED, 32L);
}

public static void XAnyEvent_write(MemorySegment s, org.eclipse.swt.internal.gtk.XAnyEvent o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.XEvent_write(s, o);
	s.set(JAVA_LONG_UNALIGNED, 8L, o.serial);
	s.set(JAVA_INT_UNALIGNED, 16L, o.send_event);
	s.set(JAVA_LONG_UNALIGNED, 24L, o.display);
	s.set(JAVA_LONG_UNALIGNED, 32L, o.window);
}

public static final long XEvent_SIZEOF = 192L;

public static void XEvent_read(MemorySegment s, org.eclipse.swt.internal.gtk.XEvent o) {
	o.type = s.get(JAVA_INT_UNALIGNED, 0L);
}

public static void XEvent_write(MemorySegment s, org.eclipse.swt.internal.gtk.XEvent o) {
	s.set(JAVA_INT_UNALIGNED, 0L, o.type);
}

public static final long XExposeEvent_SIZEOF = 64L;

public static void XExposeEvent_read(MemorySegment s, org.eclipse.swt.internal.gtk.XExposeEvent o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.XAnyEvent_read(s, o);
	o.x = s.get(JAVA_INT_UNALIGNED, 40L);
	o.y = s.get(JAVA_INT_UNALIGNED, 44L);
	o.width = s.get(JAVA_INT_UNALIGNED, 48L);
	o.height = s.get(JAVA_INT_UNALIGNED, 52L);
	o.count = s.get(JAVA_INT_UNALIGNED, 56L);
}

public static void XExposeEvent_write(MemorySegment s, org.eclipse.swt.internal.gtk.XExposeEvent o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.XAnyEvent_write(s, o);
	s.set(JAVA_INT_UNALIGNED, 40L, o.x);
	s.set(JAVA_INT_UNALIGNED, 44L, o.y);
	s.set(JAVA_INT_UNALIGNED, 48L, o.width);
	s.set(JAVA_INT_UNALIGNED, 52L, o.height);
	s.set(JAVA_INT_UNALIGNED, 56L, o.count);
}

public static final long XFocusChangeEvent_SIZEOF = 48L;

public static void XFocusChangeEvent_read(MemorySegment s, org.eclipse.swt.internal.gtk.XFocusChangeEvent o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.XAnyEvent_read(s, o);
	o.mode = s.get(JAVA_INT_UNALIGNED, 40L);
	o.detail = s.get(JAVA_INT_UNALIGNED, 44L);
}

public static void XFocusChangeEvent_write(MemorySegment s, org.eclipse.swt.internal.gtk.XFocusChangeEvent o) {
	org.eclipse.swt.internal.gtk.Structs_FFM.XAnyEvent_write(s, o);
	s.set(JAVA_INT_UNALIGNED, 40L, o.mode);
	s.set(JAVA_INT_UNALIGNED, 44L, o.detail);
}

}
